/**
 * Hintergrund-Bausteine für den Würfel am Feld „Hintergrund" – **je Genre eine
 * eigene Liste zu 100 Einträgen**.
 *
 * Das ist bewusst eine andere Struktur als bei den Berufen. Ein Beruf lässt
 * sich markieren („Schmied" passt in vier Genres), ein Lebenslauf nicht: eine
 * Kindheit im Fabrikviertel und eine im fensterlosen Wohnblock beschreiben
 * dieselbe Armut, aber in Worten, die sich nicht austauschen lassen. Sechs
 * getrennte Listen sind ehrlicher als eine Liste mit sechs Markierungen, in der
 * am Ende doch nur die blassen Einträge in allen Genres stünden.
 *
 * Rein lokal, ohne API – wie `names.ts` und `professions.ts`. Der Knopf lebt
 * davon, dass man ihn mehrmals drückt.
 *
 * Die Einträge sind Verbalphrasen ohne Subjekt („floh aus der Heimat"), damit
 * sie sich aneinanderreihen lassen und kein Geschlecht festlegen.
 */

import { pickSome } from "./inspiration";

/** Gegenwart: Schule, Jobs, Mieten, Trennungen, Netz. */
export const GEGENWART_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs in einer Plattenbausiedlung am Stadtrand auf",
  "wurde zwischen zwei geschiedenen Elternhäusern hin- und hergereicht",
  "verbrachte die Kindheit in einem Dorf ohne Busanbindung",
  "kam als Kind ins Land und lernte die Sprache auf dem Schulhof",
  "wuchs im Hinterzimmer des elterlichen Imbisses auf",
  "war das erste Kind der Familie mit Abitur",
  "wurde von einem Elternteil großgezogen, das drei Jobs hatte",
  "wuchs in einer Pflegefamilie auf",
  "verbrachte jeden Sommer bei Verwandten auf dem Land",
  "wuchs mit einem Elternteil auf, das nie über früher sprach",
  "war in der Schule immer das neue Kind",
  "wuchs in einem Haushalt auf, in dem über Geld nie gesprochen wurde",
  "musste schon als Kind die Post der Eltern übersetzen",
  "wuchs mit einem schwer kranken Geschwisterkind auf",
  "verbrachte die Nachmittage allein vor dem Rechner",
  "wurde in der Schule jahrelang gemobbt",
  "war das Kind, dem alle Lehrer etwas zutrauten",
  "flog von zwei Schulen",
  "wuchs streng religiös auf und brach damit",
  "hat Eltern, die bis heute nicht wissen, womit das Geld verdient wird",

  // Ausbildung & Arbeit
  "brach das Studium im dritten Semester ab",
  "hat einen Abschluss, der im Lebenslauf nie eine Rolle spielte",
  "arbeitete sich vom Praktikum in die Festanstellung hoch",
  "wurde nach fünfzehn Jahren wegrationalisiert",
  "kündigte von einem Tag auf den anderen",
  "machte ein Hobby zum Beruf und verlor es dadurch",
  "pendelt seit Jahren zwei Stunden am Tag",
  "arbeitet in einem Beruf, den es bald nicht mehr geben wird",
  "hat drei Nebenjobs und trotzdem zu wenig",
  "wurde befördert und war danach unglücklicher als zuvor",
  "gab eine Laufbahn für ein Versprechen auf",
  "übernahm den elterlichen Betrieb ohne Begeisterung",
  "gründete eine Firma, die nach zwei Jahren scheiterte",
  "hat eine Idee, die jemand anderes verkauft hat",
  "arbeitete jahrelang schwarz",
  "wurde bei einem Fehler erwischt, den alle machten",
  "deckte einen Betrug auf und verlor den Job",
  "unterschrieb eine Verschwiegenheitserklärung",
  "lebt von einer Abfindung",
  "hat den Rechner voller unfertiger Projekte",

  // Brüche & Verluste
  "zog für einen Menschen in eine fremde Stadt und blieb nach dem Ende",
  "kehrte nach zehn Jahren in die Heimatstadt zurück",
  "verlor die Wohnung und schlief ein halbes Jahr bei Bekannten",
  "verkaufte alles und lebte ein Jahr aus einem Rucksack",
  "überlebte einen schweren Autounfall",
  "kam nach einem Zusammenbruch anders zurück",
  "hat eine Diagnose, von der kaum jemand weiß",
  "pflegte einen Elternteil bis zu dessen Tod",
  "räumte nach einem Todesfall allein die Wohnung leer",
  "wurde von der eigenen Familie um ein Erbe gebracht",
  "steckt in einer Bürgschaft für jemanden fest",
  "schuldet einer Bank mehr, als je zurückzuzahlen ist",
  "wurde von der Versicherung im Stich gelassen",
  "verlor bei einem Hochwasser das Haus",
  "musste die alte Wohnung wegen der Miete aufgeben",
  "wanderte aus und kam nach drei Jahren zurück",
  "hat einen Pass, mit dem manche Grenzen kompliziert sind",
  "wartete jahrelang auf einen Bescheid",
  "wohnte länger bei jemandem, als beiden guttat",
  "schläft seit dem letzten Umzug schlecht",

  // Bindungen
  "war zwölf Jahre verheiratet und ist es seit zweien nicht mehr",
  "hat ein Kind, das jedes zweite Wochenende da ist",
  "wurde per Nachricht verlassen",
  "hält zu niemandem aus der alten Clique noch Kontakt",
  "hat einen besten Freund, mit dem seit einem Streit nichts mehr ist",
  "verliebte sich in die falsche Person am Arbeitsplatz",
  "lernte den Partner online kennen und erzählt es ungern",
  "zog mit jemandem zusammen, bevor es tragfähig war",
  "hat Geschwister, die nur noch bei Beerdigungen zusammenkommen",
  "spricht seit Jahren nicht mehr mit einem Elternteil",
  "adoptierte ein Kind nach langem Verfahren",
  "wollte Kinder und bekam keine",
  "blieb aus Rücksicht in einer Beziehung, die längst vorbei war",
  "hat einen Hund, der die letzten schweren Jahre mitgetragen hat",
  "wohnt allein und hat sich daran gewöhnt",
  "schreibt seit Jahren Nachrichten, die nie abgeschickt werden",
  "traf eine Jugendliebe zufällig wieder",
  "hat ein Foto im Portemonnaie, das niemand sehen darf",
  "lernte spät, um Hilfe zu bitten",
  "geht seit zwei Jahren zur Therapie und spricht nicht darüber",

  // Öffentlichkeit, Schuld, Antrieb
  "wurde einmal im Netz öffentlich zerrissen",
  "löschte alle Konten und begann von vorn",
  "war einmal für fünfzehn Minuten landesweit bekannt",
  "hat ein Video im Netz, das nie verschwinden wird",
  "betreibt anonym eine Seite, die vielen etwas bedeutet",
  "sagte vor Gericht aus und bereut es",
  "hat eine Vorstrafe aus jungen Jahren",
  "wurde in eine Ermittlung hineingezogen, ohne beteiligt zu sein",
  "saß in Untersuchungshaft und kam wieder frei",
  "fuhr einmal betrunken und hatte Glück",
  "gab einen anonymen Hinweis, der jemanden alles kostete",
  "hat einen Nachbarn angezeigt und wohnt noch immer nebenan",
  "wurde Zeuge einer Straftat und schwieg",
  "arbeitete kurz für Leute, über die man nichts Genaues wissen wollte",
  "spielte einmal alles Ersparte an einem Abend weg",
  "trank ein paar Jahre lang zu viel und hörte auf",
  "hält seit tausend Tagen etwas durch und zählt mit",
  "läuft jeden Morgen dieselbe Strecke, seit alles auseinanderfiel",
  "spart auf etwas, das nie gekauft wird",
  "hat einen Plan für ein anderes Leben in einer Schublade",
];

/** Fantasy: Höfe, Orden, Magie, Ungeheuer, Schwüre. */
export const FANTASY_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs im Schatten einer Burgmauer auf",
  "wurde als Findelkind vor einem Tempel abgelegt",
  "stammt aus einem Dorf, das auf keiner Karte steht",
  "ist das siebte Kind eines siebten Kindes",
  "wuchs beim fahrenden Volk auf",
  "wurde von einer Kräuterhexe großgezogen",
  "wuchs im Waisenhaus eines Klosters auf",
  "stammt aus einem Geschlecht, dessen Wappen niemand mehr kennt",
  "wurde als Kind einem Orden übergeben",
  "wuchs unter einem Volk auf, das nicht das eigene war",
  "kam in einer Nacht zur Welt, über die man im Dorf noch redet",
  "wurde bei der Geburt mit einem Fluch bedacht",
  "trägt ein Mal, das die Alten zu deuten wussten",
  "diente als Kind im Haushalt eines Magiers",
  "lernte lesen an geraubten Büchern",
  "wuchs in einem Bergwerksdorf auf",
  "hütete als Kind Ziegen am Rand des Waldes",
  "wurde von Wölfen nicht angerührt und gilt seither als seltsam",
  "arbeitete als Kind in der Burgküche",
  "wuchs am Hafen auf, zwischen Netzen und fremden Sprachen",

  // Lehre, Orden, Magie
  "brach die Lehre bei einem Magier ab",
  "wurde aus der Akademie verwiesen",
  "beherrscht einen einzigen Zauber, und den vollkommen",
  "verlor die Gabe nach einem Unglück",
  "verweigert die Magie, obwohl sie da ist",
  "schwor einem Orden Treue und diente zehn Jahre",
  "wurde aus dem Orden ausgestoßen",
  "legte ein Schweigegelübde ab und hielt es sieben Jahre",
  "las ein Buch, das nicht gelesen werden sollte",
  "trägt einen Ring, den abzunehmen nicht gelingt",
  "schloss einen Vertrag mit etwas, das keinen Namen trägt",
  "schuldet einer Fee einen Gefallen",
  "wurde von einem Gott angesprochen und weiß nicht, warum",
  "verlor den Glauben an die eigene Gottheit",
  "dient einer Gottheit, die kaum noch verehrt wird",
  "ging vor den letzten Gelübden aus dem Kloster",
  "hatte einen Meister, der auf ungeklärte Weise starb",
  "erbte den Stab eines Toten",
  "kann etwas, das anderen unheimlich ist",
  "hört seit einer Nacht im Wald Stimmen, die recht behalten",

  // Krieg, Ungeheuer, Gewalt
  "überlebte als Einziges einen Drachenangriff",
  "verlor das Dorf an Plünderer",
  "diente in der Leibgarde eines Fürsten",
  "desertierte aus dem Heer des Königs",
  "focht in einer Schlacht, die verloren ging",
  "tötete zum ersten Mal mit sechzehn",
  "trägt eine Wunde, die nicht heilen will",
  "wurde von einem Werwesen gebissen und überlebte",
  "jagte jahrelang das falsche Ungeheuer",
  "rettete ein Dorf und wurde dafür verjagt",
  "hielt einen Pass drei Tage lang allein",
  "verlor die Schwertkameraden alle in einer Nacht",
  "verbrachte ein Jahr in Gefangenschaft bei Feinden",
  "wurde von Räubern aufgenommen statt getötet",
  "führte einen Zug in die Berge, von dem die Hälfte zurückkam",
  "hat einen Kopfpreis in zwei Fürstentümern",
  "schlug ein Duell aus und trägt die Schande",
  "gewann ein Turnier, das nicht zu gewinnen war",
  "brach einen Eid auf dem Schlachtfeld",
  "verschonte einen Feind und bereut es",

  // Hof, Gilde, Politik
  "war Mündel an einem fremden Hof",
  "wurde als Geisel zwischen zwei Häusern getauscht",
  "gehört einer Familie an, die ihren Titel verlor",
  "ist ein uneheliches Kind aus adligem Haus",
  "wurde vom Hof verbannt",
  "fiel bei der Königin in Ungnade",
  "verhandelte einen Frieden, der zwei Jahre hielt",
  "steht bei einer Gilde in der Schuld",
  "wurde aus der Gilde ausgeschlossen",
  "arbeitete für die Diebesgilde und stieg aus",
  "schmuggelte über Jahre, ohne erwischt zu werden",
  "kennt ein Geheimnis über die Thronfolge",
  "überbrachte eine Botschaft, die einen Krieg auslöste",
  "diente einem Herrn, der sich als Ungeheuer erwies",
  "verweigerte einem Fürsten den Gehorsam",
  "wurde für Verrat verurteilt und begnadigt",
  "trägt einen Namen, der in einer Stadt Türen öffnet und in einer anderen schließt",
  "hat einen Bruder, der auf der anderen Seite steht",
  "erbte eine Fehde",
  "beendete eine Fehde durch Heirat",

  // Reisen, Verlust, Antrieb
  "zog jahrelang mit einer Gauklertruppe",
  "fuhr auf einem Schiff bis ans Ende der bekannten Karten",
  "überquerte allein ein Gebirge",
  "lebte einen Winter lang in einer Höhle",
  "fand Ruinen, von denen niemand hören will",
  "brachte etwas aus einem Grab mit",
  "verkaufte ein Erbstück und will es zurück",
  "sucht ein Schwert, das der Familie gehörte",
  "sucht den Bruder, der in den Krieg zog und nie schrieb",
  "sucht den Ort aus einem wiederkehrenden Traum",
  "verlor die Erinnerung an drei Jahre",
  "wurde für tot erklärt und kam zurück",
  "altert seit einem Vorfall langsamer als andere",
  "gibt jedem Bettler etwas, seit einer Nacht im Regen",
  "trägt die Asche eines Menschen mit sich",
  "hat ein Versprechen an einen Sterbenden nicht eingelöst",
  "hütet das Grab eines Fremden",
  "schuldet einem Toten noch eine Antwort",
  "will den eigenen Namen in einem Lied hören",
  "will nur noch ein Stück Land und Ruhe",
];

/** Steampunk: Fabriken, Akademien, Luftschiffe, Stand und Ruß. */
export const STEAMPUNK_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs im Rauch der Fabrikviertel auf",
  "arbeitete als Kind unter den Webstühlen",
  "wuchs im Kesselhaus einer Werft auf",
  "stammt aus einer Familie von Uhrmachern",
  "wurde im Armenhaus großgezogen",
  "wuchs als Kind von Dienstboten im Herrenhaus auf",
  "verlor mit neun einen Finger an eine Maschine",
  "wuchs neben dem Rangierbahnhof auf",
  "stammt aus gutem Hause und schämt sich dafür",
  "wurde von einem Erfinder als Gehilfe aufgenommen",
  "wuchs zwischen Blaupausen und Schuldscheinen auf",
  "lernte lesen an Bedienungsanleitungen",
  "wuchs in einer Kolonie auf und kam spät ins Mutterland",
  "trug als Kind Telegramme aus",
  "wuchs unter den Bögen einer Eisenbahnbrücke auf",
  "wurde in einem Internat zurechtgebogen",
  "musste die Schule verlassen, als der Vater starb",
  "wuchs mit einem Vater auf, der von einer Erfindung träumte",
  "hat eine Mutter, die als Erste in der Familie schreiben lernte",
  "wuchs im Schatten eines berühmten Namens auf",

  // Werkstatt & Wissenschaft
  "wurde von der Akademie abgelehnt und lernte allein weiter",
  "veröffentlichte eine Arbeit unter fremdem Namen",
  "hat ein Patent, das jemand anderes hält",
  "baute eine Maschine, die funktionierte und niemanden interessierte",
  "verlor bei einem Versuch das Gehör auf einem Ohr",
  "sprengte im Selbstversuch eine Werkstatt",
  "arbeitet seit Jahren an einem Apparat, der nie fertig wird",
  "widerlegte den eigenen Lehrer öffentlich",
  "wurde aus der Gesellschaft der Ingenieure ausgeschlossen",
  "hat eine Formel im Kopf und nichts auf dem Papier",
  "verbrannte alle eigenen Aufzeichnungen",
  "trägt eine Prothese aus eigener Fertigung",
  "hält einen Rekord, den niemand mehr erwähnt",
  "wurde für eine Fehlkonstruktion verantwortlich gemacht",
  "bekam eine Auszeichnung und gab sie zurück",
  "arbeitete an etwas für das Kriegsministerium",
  "weiß, warum ein Kessel wirklich explodierte",
  "fälschte den Bericht über ein Unglück",
  "war beim ersten Flug einer Maschine an Bord",
  "reparierte einmal etwas, das nicht zu reparieren war",

  // Fabrik, Stand, Geld
  "organisierte einen Streik und verlor",
  "steht seit dem Streik auf jeder Liste",
  "verlor die Anstellung an eine Maschine",
  "stieg vom Heizer zum Maschinisten auf",
  "arbeitete zwanzig Jahre in derselben Halle",
  "kaufte sich mit Schulden in eine Werkstatt ein",
  "verlor das Vermögen bei einer Eisenbahnspekulation",
  "heiratete über den eigenen Stand und wurde nie angenommen",
  "heiratete unter den eigenen Stand und wurde enterbt",
  "spricht in Gesellschaft eine Sprache, die nicht die eigene ist",
  "hat einen Akzent, der jede Tür halb schließt",
  "lebt von einer Rente, die kaum reicht",
  "verpfändete die Werkzeuge und kaufte sie zurück",
  "schuldet einem Geldverleiher mehr, als der Betrieb wert ist",
  "verkaufte den Namen der Familie an eine Gesellschaft",
  "brachte einen Betrieb durch die Krise und wurde hinausgedrängt",
  "beschäftigt Leute, die sonst niemand einstellt",
  "wurde beim Fälschen von Papieren erwischt",
  "schmuggelte Bauteile über den Kanal",
  "lieferte einmal an beide Seiten",

  // Luftschiffe, Reisen, Expedition
  "fuhr drei Jahre auf Luftschiffen",
  "überlebte den Absturz eines Luftschiffs",
  "navigierte eine Expedition ins Eis",
  "kehrte als Einziges von einer Expedition zurück",
  "kartierte einen Fluss, den vorher niemand befuhr",
  "verbrachte ein Jahr in einer Forschungsstation",
  "brachte etwas aus Übersee mit, das nicht hätte mitkommen sollen",
  "war beim Bau einer Bahnstrecke durch das Gebirge dabei",
  "arbeitete in einem Bergwerk, das absoff",
  "überlebte ein Grubenunglück",
  "fuhr auf einem Frachter zur See",
  "wurde in einem fremden Hafen zurückgelassen",
  "lernte Maschinen an einem Ort kennen, den es nicht mehr gibt",
  "überflog in einer einzigen Nacht die Front",
  "berichtete für eine Zeitung aus dem Feld",
  "diente in einem Kolonialregiment und kam verändert zurück",
  "sah zu, wie eine Stadt in einer Woche entstand",
  "kennt jeden Kanal unter der Stadt",
  "wohnte ein halbes Jahr in einem stillgelegten Wasserturm",
  "richtete sich in einem ausgemusterten Waggon ein",

  // Gesellschaft, Geheimnis, Antrieb
  "gehört einem Klub an, dessen Mitglieder einander nicht kennen",
  "wurde in einen Zirkel aufgenommen und wieder hinausgeworfen",
  "hält Séancen für Unsinn und geht trotzdem hin",
  "war einmal Medium bei einer Sitzung und weiß, wie es gemacht wird",
  "sammelt Zeitungsausschnitte über einen einzigen Fall",
  "schreibt anonym Leserbriefe an eine Zeitung",
  "veröffentlichte Fortsetzungsromane unter fremdem Namen",
  "gewann einen Prozess und verlor alles dabei",
  "sagte gegen den eigenen Arbeitgeber aus",
  "deckte eine Vertuschung auf und wurde für verrückt erklärt",
  "verbrachte Monate in einer Anstalt",
  "nimmt seit einer Operation ein Mittel, das schwer zu bekommen ist",
  "trägt eine Uhr, die stehen geblieben ist und nicht gerichtet wird",
  "hat einen Brief nie geöffnet",
  "sucht den Konstrukteur einer Maschine, die alles zerstörte",
  "will beweisen, dass der Vater kein Betrüger war",
  "will eine Erfindung fertigstellen, die vom Meister blieb",
  "spart auf eine Überfahrt, die nie angetreten wird",
  "ließ den eigenen Namen aus dem Register streichen",
  "führt seit zwanzig Jahren dasselbe Notizbuch",
];

/** Cyberpunk: Konzerne, Implantate, Netz, Blocks. */
export const CYBERPUNK_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs in einem Wohnblock ohne Fenster auf",
  "wurde als Kind von einem Konzern adoptiert und ausgebildet",
  "wuchs in der Arkologie auf und hat den Boden nie gesehen",
  "stammt aus einem Viertel, das offiziell nicht existiert",
  "wurde in einer Klinik geboren, deren Akten verschwunden sind",
  "wuchs unter Maschinenaufsicht auf, weil beide Eltern schichteten",
  "war als Kind Testperson für ein Programm",
  "wuchs im Umfeld einer Straßengang auf",
  "lernte lesen an gecrackten Datenpaketen",
  "wuchs mit einem Elternteil auf, das sich zu Tode arbeitete",
  "hat Geschwister, die für einen anderen Konzern arbeiten",
  "wurde als Kind gegen Schulden verpfändet",
  "wuchs in einer Sekte auf, die die Netzabkehr predigte",
  "kam aus der Provinz in die Stadt und blieb",
  "wuchs außerhalb der Kuppel auf",
  "gehört zu den Kindern, die nie registriert wurden",
  "hat einen Geburtsdatensatz, der zweimal existiert",
  "wuchs in einem Flüchtlingsblock auf",
  "verlor die Familie bei einer Räumung",
  "wurde von einem Ripperdoc aufgezogen",

  // Konzern & Arbeit
  "arbeitete zwölf Jahre für einen Konzern und ging mit nichts",
  "wurde bei einer Umstrukturierung gestrichen",
  "unterschrieb einen Vertrag mit einer Klausel, die noch gilt",
  "verlor eine Kündigungsklage",
  "war in der mittleren Führungsebene und stieg aus",
  "tauschte den Konzernausweis gegen ein Leben ohne Papiere",
  "wurde abgeworben und danach fallen gelassen",
  "arbeitete an einem Projekt, das eingestellt und gelöscht wurde",
  "weiß, was in einer bestimmten Datenbank steht",
  "hat Belege für etwas, das nie ans Licht kam",
  "verkaufte einmal Daten und lebt seither davon",
  "wurde als Whistleblower enttarnt",
  "steht auf der Liste eines Sicherheitsdienstes",
  "schuldet einer Klinik den Preis eines Implantats",
  "zahlt seit Jahren an einer Lizenz für den eigenen Körper",
  "least das eigene Auge",
  "hat eine Software im Kopf, die Updates verlangt",
  "musste sich Implantate wieder herausnehmen lassen",
  "arbeitete als Testkörper für Prototypen",
  "verlor eine Hand und bekam eine bessere",

  // Netz, Daten, Identität
  "löschte die eigene Identität und legte eine neue an",
  "lebt unter dem Namen einer Toten",
  "hat drei Legenden, von denen zwei noch tragen",
  "wurde einmal vollständig entblößt: alles öffentlich",
  "brannte sich beim Tauchen ins Netz etwas weg",
  "verlor bei einem Braincheck zwei Wochen Erinnerung",
  "hat eine Sicherung des eigenen Kopfes und nie hineingesehen",
  "hat einen Doppelgänger im Netz, der weitermacht",
  "spricht mit einer Stimme, die nicht die eigene ist",
  "betreibt ein Board für Leute, die niemand sucht",
  "knackte einmal etwas, das nicht zu knacken war",
  "wurde von einer KI angesprochen und weiß nicht, warum",
  "arbeitete für einen Datenhehler",
  "hat einen Zugang, den niemand geschlossen hat",
  "bekommt seit Jahren Nachrichten von einem toten Konto",
  "verlor jemanden bei einem Blackout",
  "war beim großen Netzausfall im Turm eingeschlossen",
  "hat einen Ausweis, der an fünf Türen funktioniert",
  "verkaufte einmal eigene Erinnerungen",
  "hat eine Erinnerung, die nachweislich nicht stattgefunden hat",

  // Straße, Gangs, Gewalt
  "lief ein paar Jahre für eine Gang",
  "stieg aus einer Gang aus und zahlt noch dafür",
  "hat ein Tattoo, das in manchen Blocks Ärger bedeutet",
  "überlebte eine Räumung durch die Konzernsicherheit",
  "war bei einem Aufstand dabei und schweigt darüber",
  "saß in einem privaten Gefängnis ein",
  "arbeitete die Strafe in einer Fabrik ab",
  "tötete einmal in Notwehr und wurde nie belangt",
  "wurde angeschossen und in einer Hinterzimmerklinik geflickt",
  "hat eine Kugel im Körper, die drinbleibt",
  "transportierte Ware, ohne sie je zu öffnen",
  "verlor den Partner bei einem Job, der schieflief",
  "kam als Einziges von einem Team zurück",
  "brach einen Auftrag ab und behielt den Vorschuss",
  "schuldet einem Fixer einen Gefallen ohne Frist",
  "steht bei einer Familie in der Schuld",
  "verpfiff einmal jemanden und lebt damit",
  "wurde verpfiffen und weiß von wem",
  "hat einen Kopfpreis, der jedes Jahr steigt",
  "wechselt alle paar Monate den Block",

  // Körper, Sucht, Antrieb
  "ist seit einem Umbau nicht mehr ganz derselbe Mensch",
  "lehnt Implantate grundsätzlich ab",
  "hat mehr Metall im Körper als vertretbar",
  "nimmt Mittel gegen die Abstoßung, die schwer zu bekommen sind",
  "hing ein paar Jahre an Sim-Drogen",
  "kam davon los und geht jeden Tag daran vorbei",
  "schläft seit dem Umbau nur noch drei Stunden",
  "spürt Kälte nur noch auf einer Seite",
  "hat Schmerzen, für die es keine Ursache gibt",
  "ließ sich das Gesicht ändern",
  "erkennt sich auf alten Bildern nicht wieder",
  "sucht den Menschen, dessen Daten im eigenen Kopf liegen",
  "sucht das Kind, das eine Klinik weitergegeben hat",
  "sucht den Arzt, der den Umbau verpfuscht hat",
  "will einmal echten Himmel sehen",
  "spart auf ein Ticket aus der Stadt",
  "hat einen Ort außerhalb, von dem niemand weiß",
  "hält an einem Gegenstand aus Papier fest",
  "hat einen Namen im Kopf und einen Vorsatz dazu",
  "will, dass ein bestimmter Name gelöscht wird",
];

/** Historisch: reale Epochen, Stand, Zunft, Kirche, Krieg – ohne Übernatürliches. */
export const HISTORISCH_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs auf einem Bauernhof in der dritten Generation auf",
  "wurde als Kind in Dienst gegeben",
  "wuchs im Haus eines Handwerksmeisters auf",
  "stammt aus einer Kaufmannsfamilie",
  "kam ins Kloster, weil die Familie ein Kind zu viel hatte",
  "wurde in eine Sippe niederen Adels geboren",
  "wuchs in einer Garnisonsstadt auf",
  "verlor drei Geschwister vor deren fünftem Jahr",
  "wuchs als uneheliches Kind im Dorf auf",
  "lernte lesen bei einem Pfarrer",
  "durfte als Einziges der Kinder zur Schule",
  "wuchs im Hafenviertel zwischen Fremden auf",
  "stammt aus einer Familie von Wanderarbeitern",
  "wuchs in einer Mühle auf",
  "wurde von einer Amme großgezogen und liebte sie mehr",
  "wuchs in einem Land auf, das es heute nicht mehr gibt",
  "spricht die Sprache der Eltern nur noch schlecht",
  "wuchs in einer Minderheit auf, die geduldet wurde",
  "wurde früh verlobt und wehrte sich",
  "musste mit zwölf die Eltern ersetzen",

  // Handwerk, Stand, Geld
  "schloss die Lehre ab und wanderte drei Jahre",
  "wurde nie in die Zunft aufgenommen",
  "übernahm die Werkstatt und hielt sie zwanzig Jahre",
  "verlor das Geschäft an einen Gläubiger",
  "verkaufte den letzten Grundbesitz",
  "stieg durch eine Heirat auf",
  "wurde durch eine Heirat unglücklich versorgt",
  "verlor den Stand durch einen Prozess",
  "kaufte sich frei",
  "war leibeigen und ging fort",
  "arbeitete als Tagelöhner von Ernte zu Ernte",
  "schrieb für andere Briefe gegen Bezahlung",
  "führte die Bücher eines Hauses, das betrog",
  "wurde beim Fälschen eines Siegels ertappt",
  "schmuggelte Salz über die Grenze",
  "hielt eine Schankwirtschaft",
  "verlor alles bei einem Brand in der Stadt",
  "sammelte nach einem Krieg auf den Feldern",
  "zog mit einem Heer im Tross mit",
  "verdiente am Krieg und schweigt darüber",

  // Krieg, Krankheit, Katastrophe
  "überlebte eine Seuche, die das halbe Dorf nahm",
  "pflegte Kranke, bis niemand mehr da war",
  "überlebte als Kind eine Belagerung",
  "wurde als Rekrut ausgehoben",
  "desertierte und kam davon",
  "kämpfte in einer Schlacht, deren Namen alle kennen",
  "geriet in Gefangenschaft und wurde ausgetauscht",
  "kam mit einem steifen Bein aus dem Feld zurück",
  "verlor die halbe Familie in einem einzigen Jahr",
  "überstand einen Hungerwinter",
  "sah eine Stadt brennen",
  "war beim Einzug einer fremden Armee dabei",
  "wurde vertrieben und kam nie zurück",
  "floh über einen zugefrorenen Fluss",
  "überlebte eine Überfahrt, die viele nicht überlebten",
  "wanderte aus und kehrte gescheitert zurück",
  "kam in ein Land, dessen Sprache fremd blieb",
  "war Jahre auf See und kannte kein Land",
  "wurde von Piraten aufgebracht",
  "überlebte einen Schiffbruch",

  // Kirche, Recht, Obrigkeit
  "trat in einen Orden ein und wieder aus",
  "wurde der Ketzerei verdächtigt",
  "widerrief öffentlich und schämt sich dafür",
  "wurde aus der Kirche ausgeschlossen",
  "verlor den Glauben in einem einzigen Jahr",
  "las Bücher, die auf dem Index standen",
  "wurde wegen einer Schrift verfolgt",
  "saß im Schuldturm",
  "wurde an den Pranger gestellt",
  "wurde freigesprochen und trotzdem gemieden",
  "sagte gegen einen Nachbarn aus",
  "rettete jemanden vor einem Prozess",
  "wurde von der Obrigkeit geduldet, nicht anerkannt",
  "bestach einmal einen Beamten und kam davon",
  "verlor ein Verfahren gegen eine Familie mit Namen",
  "überbrachte eine Bittschrift an den Hof",
  "wurde beim Herrn vorgelassen und abgewiesen",
  "gehörte zu denen, die eine Petition unterschrieben",
  "war bei einem Aufstand dabei",
  "wurde nach dem Aufstand begnadigt",

  // Bindungen, Wissen, Antrieb
  "heiratete auf Anordnung der Eltern",
  "liebte jemanden aus dem falschen Haus",
  "wurde vor der Trauung sitzengelassen",
  "verlor ein Kind in dessen erstem Jahr",
  "zog die Kinder eines Verstorbenen mit auf",
  "lebte jahrelang getrennt vom Ehepartner",
  "schrieb Briefe, die nie ankamen",
  "wartete sieben Jahre auf eine Rückkehr",
  "hat einen Bruder, der nach Übersee ging",
  "besitzt das einzige Bild eines Toten",
  "lernte ein Handwerk von jemandem, der es nicht lehren durfte",
  "sammelte Kräuterwissen und wurde beargwöhnt",
  "kann rechnen und wird deshalb gebraucht",
  "spricht drei Sprachen und verschweigt zwei",
  "führte über Jahre ein Tagebuch",
  "hütet die Papiere einer Familie",
  "weiß, wo etwas vergraben liegt",
  "will den Namen der Familie wiederherstellen",
  "will einmal die Hauptstadt sehen",
  "arbeitet auf ein eigenes Stück Land hin",
];

/** Western: Trecks, Ranches, Claims, Sterne und Steckbriefe. */
export const WESTERN_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs auf einer Ranch am Rand des Territoriums auf",
  "kam als Kind mit einem Treck nach Westen",
  "wurde in einem Planwagen geboren",
  "wuchs in einer Stadt auf, die nach zwei Jahren leer stand",
  "verlor die Familie unterwegs an das Fieber",
  "wuchs bei einem Onkel auf, der trank",
  "wuchs zwischen zwei Völkern auf und gehörte zu keinem",
  "wurde in einer Missionsschule aufgenommen",
  "wuchs im Hinterzimmer eines Saloons auf",
  "arbeitete ab dem zehnten Jahr im Stall",
  "kannte Pferde, bevor es Buchstaben gab",
  "stammt aus dem Osten und redet noch immer anders",
  "kam als Kind über den Ozean und dann noch weiter",
  "wuchs an der Grenze zweier Sprachen auf",
  "überlebte als Kind einen Überfall auf einen Treck",
  "verlor den Vater an ein Grubenunglück",
  "wuchs in einem Zeltlager am Fluss auf",
  "hat eine Mutter, die die Ranch allein hielt",
  "floh mit der Familie vor dem Krieg nach Westen",
  "wuchs auf, während der Krieg zu Ende ging",

  // Arbeit, Ranch, Trail
  "ritt sechs Jahre lang Viehtriebe",
  "verlor eine Herde in einem Sturm",
  "arbeitete auf der Ranch eines Mannes, der niemandem zahlte",
  "war Vorarbeiter und wurde ersetzt",
  "zog einen Zaun um Land, das nicht gehörte",
  "gab das Gehöft nach drei Dürrejahren auf",
  "wurde von der Bank vom eigenen Land geholt",
  "verkaufte alles und begann noch einmal",
  "arbeitete beim Bau der Eisenbahn",
  "fuhr eine Postkutsche über einen gefährlichen Abschnitt",
  "arbeitete im Telegrafenamt",
  "suchte zwei Jahre Gold und fand fast genug",
  "verkaufte den Claim einen Monat zu früh",
  "arbeitete im Bergwerk, bis die Lunge streikte",
  "hielt einen Laden am Leben, als die Stadt starb",
  "brannte selbst Whiskey und verkaufte ihn",
  "brach Pferde zu, bis das Knie nicht mehr mitmachte",
  "trieb Vieh über die Grenze, ohne zu fragen",
  "jagte Büffel und hörte damit auf",
  "war Kundschafter für die Armee",

  // Gewalt, Gesetz, Schuld
  "trug einmal einen Stern und legte ihn ab",
  "war Hilfssheriff in einer Stadt, die sich selbst regierte",
  "hängte einen Mann und schläft seither schlecht",
  "verhinderte einmal eine Lynchjustiz",
  "erschoss jemanden im Streit um nichts",
  "überlebte einen Hinterhalt am Fluss",
  "wurde angeschossen und von Fremden gepflegt",
  "saß drei Jahre im Territorialgefängnis",
  "brach aus und wurde nie wieder gesucht",
  "ritt eine Zeit lang mit einer Bande",
  "stieg aus der Bande aus, bevor es endete",
  "hat einen Steckbrief in einem anderen Territorium",
  "wurde für etwas gesucht, das ein Bruder tat",
  "jagte einen Mann über drei Staaten",
  "gab die Verfolgung auf und weiß nicht, ob es richtig war",
  "sagte vor Gericht gegen einen Freund aus",
  "wurde zum Duell gefordert und ging nicht hin",
  "gewann einmal ein Duell und redet nie darüber",
  "überfiel einmal einen Zug",
  "gab das Geld zurück, aber zu spät",

  // Land, Konflikt, Gemeinschaft
  "geriet zwischen Rancher und Siedler",
  "verlor Freunde in einem Weidekrieg",
  "handelte einen Frieden mit einem Stamm aus",
  "brach ein Abkommen und trägt daran",
  "dolmetschte zwischen zwei Seiten",
  "wurde von einem Stamm aufgenommen und zog wieder fort",
  "sah zu, wie ein Dorf geräumt wurde, und tat nichts",
  "weigerte sich, an einem Feldzug teilzunehmen",
  "deckte einmal einen Flüchtenden",
  "brachte einen Verletzten durch die Wüste",
  "gründete mit anderen eine Stadt, die es noch gibt",
  "war beim ersten Gottesdienst in einer Bretterkirche dabei",
  "begrub mehr Nachbarn als gewünscht",
  "hielt das Wasserrecht gegen die halbe Ebene",
  "verkaufte Land an die Eisenbahn und bereut es",
  "wurde aus der Stadt gebeten",
  "kam nach zehn Jahren zurück und wurde nicht erkannt",
  "trägt in drei Städten einen anderen Namen",
  "lebte einen Winter allein in den Bergen",
  "überstand einen Winter, in dem andere es nicht taten",

  // Bindungen, Verlust, Antrieb
  "heiratete in eine Familie, die das Land besaß",
  "verlor den Ehepartner im ersten gemeinsamen Jahr",
  "zieht ein Kind allein groß",
  "hat ein Kind, das im Osten bei Verwandten lebt",
  "schreibt jeden Monat einen Brief und bekommt keinen",
  "ritt jemandem nach und kam zu spät",
  "verlor den Bruder bei einem Überfall",
  "hatte einen Partner, der beim Trieb ertrank",
  "teilte jahrelang das Lager mit demselben Menschen",
  "wurde von einem Fremden gerettet und fand ihn nie wieder",
  "schuldet einem Wirt mehr als Geld",
  "hat ein Pferd, das der einzige verbliebene Besitz ist",
  "trägt eine Uhr, die einem Toten gehörte",
  "hat eine Bibel mit fremden Namen darin",
  "spielte einmal alles weg und hörte auf",
  "trank ein paar Jahre und trinkt seither nicht",
  "sucht das Grab eines Menschen",
  "sucht den Mann, der die Familie auf dem Gewissen hat",
  "will nach Westen, bis das Meer kommt",
  "will ein Stück Land, ein Dach und keine Fragen mehr",
];

/** Genre-Id aus `templates.ts` → passende Hintergründe. */
/** Science Fiction: Herkunft, Ausbildung, Dienst, Reise, Brüche, Bindungen. */
export const SCIFI_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs in einem Habitatring auf, in dem alle einander kannten",
  "wurde an Bord geboren und hat nie festen Boden betreten",
  "wuchs unter einer Kuppel auf, deren Himmel projiziert war",
  "kam als Kind mit einem Kolonistenschiff an",
  "wuchs in der dritten Generation einer Bergbaukolonie auf",
  "verbrachte die Kindheit auf einer Station ohne Tag und Nacht",
  "wuchs bei anderer Schwerkraft auf und merkt es bis heute",
  "wurde in einer Familie von Vertragsarbeitern groß",
  "wuchs neben einem Raumhafen auf und kannte die Fahrpläne auswendig",
  "verbrachte die ersten Jahre im Kälteschlaf, ohne es zu wissen",
  "wuchs zwischen zwei Kolonien hin- und hergerissen auf",
  "stammt von der Erde und spricht selten davon",
  "wurde in einer Kolonie geboren, die es heute nicht mehr gibt",
  "wuchs im Frachtdeck eines Handelsschiffs auf",
  "war das erste Kind, das auf dieser Welt geboren wurde",
  "wuchs in einem Habitat auf, dessen Vorräte immer knapp waren",

  // Ausbildung & Lernen
  "wurde für eine Aufgabe ausgebildet, die inzwischen Maschinen erledigen",
  "hat die Ausbildung abgebrochen und schuldet sie bis heute",
  "lernte Instandhaltung, weil es die einzige freie Stelle war",
  "wurde für den Außendienst ausgewählt und hat es nie bereut",
  "studierte auf Kosten eines Konzerns und blieb ihm verpflichtet",
  "bekam eine Ausbildung, die auf keiner anderen Welt anerkannt wird",
  "lernte drei Sprachen, weil die Station drei Belegschaften hatte",
  "wurde als Kind auf Eignung geprüft und anders eingeteilt als gewünscht",
  "brachte sich Navigation selbst bei, aus alten Handbüchern",
  "wurde für die Heilkunde ausgebildet und hat nie eine richtige Klinik gesehen",
  "lernte den Beruf im Schatten eines Älteren, der nichts erklärte",
  "wurde für die Verwaltung geschult und wollte immer zur Wartung",
  "hat eine Prüfung dreimal wiederholt und dann bestanden",
  "wurde befördert, weil jemand anderes ausfiel",

  // Arbeit & Dienst
  "arbeitete jahrelang in Schichten von acht Monaten",
  "war auf einem Frachter angeheuert, der nie pünktlich ankam",
  "diente in einer Flotte, über die niemand mehr spricht",
  "arbeitete in der Aufbereitung und riecht es angeblich noch",
  "war für die Luftversorgung eines ganzen Decks zuständig",
  "hat einen Vertrag abgearbeitet, der zehn Jahre lief",
  "arbeitete auf einer Station, die in dieser Zeit geräumt wurde",
  "grub auf einem Mond mit nur zwei Ausgängen",
  "flog Versorgungsrouten, die sonst niemand fliegen wollte",
  "arbeitete im Hafen und kannte jede Ladung, ohne zu fragen",
  "gehörte zu einer Besatzung, die sich in vier Jahren nie stritt",
  "hielt eine Sendestation besetzt, zu zweit",
  "war für Quarantänekontrollen zuständig und hat sie einmal umgangen",
  "arbeitete in einem Labor, dessen Zweck nie erklärt wurde",
  "verdiente das Geld mit Reparaturen, die eigentlich verboten waren",
  "war Vorarbeiter und wurde dafür gehasst",

  // Reise & Ferne
  "hat drei Systeme gesehen und keines länger als ein Jahr",
  "war lange genug im Kälteschlaf, dass die Freunde gealtert sind",
  "verließ die Heimatwelt und kam nie zurück",
  "reiste als blinder Passagier zum ersten Mal fort",
  "war auf einem Generationenschiff und stieg unterwegs aus",
  "kennt Wege durch ein Trümmerfeld, die sonst niemand kennt",
  "verbrachte ein Jahr auf einem Schiff ohne Sichtfenster",
  "wurde bei einer Evakuierung von der Familie getrennt",
  "kam mit einem Konvoi an und blieb, als er weiterzog",
  "hat einen Sprungpunkt passiert, der danach geschlossen wurde",
  "wartete elf Jahre auf eine Antwort von zu Hause",
  "floh von einer Welt, die inzwischen unbewohnbar ist",
  "hat eine Reise hinter sich, für die es keine Papiere gibt",
  "kennt den Weg zurück und nimmt ihn nicht",

  // Brüche & Verluste
  "überlebte ein Leck, aus dem die Schicht davor nicht herauskam",
  "verlor einen Arm bei einer Wartung und die Stelle gleich mit",
  "wurde nach einem Unfall für dienstuntauglich erklärt",
  "war an Bord, als der Reaktor stillstand",
  "hat einen Vertrag gebrochen und trägt die Folgen",
  "wurde ausgewiesen und in einem anderen System aufgenommen",
  "verlor die Familie bei einer Evakuierung, für die die Plätze fehlten",
  "hat eine Untersuchung überstanden, die zwei Kollegen nicht überstanden",
  "war der einzige Überlebende und wurde dafür wochenlang befragt",
  "hat einen Fehler gemacht, der in keinem Protokoll steht",
  "verlor die Zulassung nach einem Vorfall, den man ihm anlastete",
  "musste jemanden draußen zurücklassen",
  "wurde für tot erklärt und kam zurück",
  "verlor die Heimatkolonie an einen Vertrag, den andere schlossen",
  "war lange krank in einer Zeit, in der Kranke nicht bleiben durften",
  "hat Schulden aus einer Behandlung, die nichts brachte",

  // Bindungen
  "war einmal verheiratet, auf einer anderen Welt",
  "hat Kinder, die in einem anderen System aufwachsen",
  "hält eine Freundschaft, die nur über Funk besteht",
  "schuldet jemandem das Leben und weiß nicht, wo er ist",
  "hat ein Geschwister in der Verwaltung und spricht nicht mit ihm",
  "wurde von einer Besatzung aufgenommen wie von einer Familie",
  "arbeitet mit jemandem zusammen, mit dem alles anfing",
  "bürgt für jemanden, der es nicht verdient hat",
  "hatte einen Mentor, der später verurteilt wurde",
  "hält Kontakt zu genau einem Menschen von früher",
  "gehört einer Gruppe an, die es offiziell nicht gibt",
  "hat ein Kind, das für die Gegenseite arbeitet",
  "hat jemanden zurückgelassen und schreibt trotzdem",
  "teilt seit Jahren eine Kabine mit derselben Person",

  // Jetzt
  "hat gerade einen Vertrag beendet und keinen neuen",
  "wartet auf eine Zuteilung, die nicht kommt",
  "sucht jemanden, dessen Spur in einem Hafen endet",
  "hat sich für einen Flug beworben, von dem niemand zurückkehrt",
  "verwaltet einen Nachlass, der nur aus Daten besteht",
  "hat gekündigt und darf trotzdem nicht gehen",
  "will registriert werden und wird abgelehnt",
  "spart auf eine Passage, die jedes Jahr teurer wird",
  "gibt sich seit der letzten Kontrolle als jemand anderes aus",
  "hat etwas gefunden und noch niemandem gemeldet",
];

/** Märchen: Herkunft, Lehre, Aufbruch, Begegnungen, Prüfungen, Wendungen. */
export const MAERCHEN_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs als jüngstes von sieben Geschwistern auf",
  "wurde als Findelkind vor einer Mühle abgelegt",
  "wuchs bei einer Großmutter am Waldrand auf",
  "war das einzige Kind eines Holzfällers",
  "wurde großgezogen von jemandem, der nie erklärte, warum",
  "wuchs in einem Dorf auf, das seinen Namen gewechselt hat",
  "kam zur Welt, als der Vater längst fort war",
  "wurde einem Kloster übergeben, ehe man sprechen konnte",
  "wuchs im Wirtshaus an der Landstraße auf",
  "galt als Wechselbalg und hörte es täglich",
  "wuchs zwischen Tieren auf und bei wenigen Menschen",
  "wurde bei der Geburt einem Fremden versprochen",
  "wuchs auf einem Hof auf, der drei Kinder nicht ernähren konnte",
  "kam in einem Winter zur Welt, den keiner vergaß",
  "wuchs in einem Schloss auf, ohne dazuzugehören",
  "wurde als Kind aus dem Wasser gezogen und behalten",

  // Lehre & Dienst
  "ging als Kind in die Lehre bei einem strengen Meister",
  "diente sieben Jahre für einen Lohn, der nie ausgezahlt wurde",
  "lernte das Handwerk vom Vater und wollte es nie",
  "hütete jahrelang die Gänse und lernte dabei zuzuhören",
  "wurde an einen fremden Hof in Dienst gegeben",
  "lernte die Kräuter bei einer Alten, die dafür verrufen war",
  "arbeitete in der Küche eines Herrn und sah alles",
  "zog drei Jahre als Geselle über Land",
  "wurde beim Schmied angenommen, weil sonst niemand blieb",
  "diente einer Herrschaft, die nie zufrieden war",
  "lernte Lesen von einem Mönch, der es nicht durfte",
  "wurde Soldat, weil das Los darauf fiel",
  "hütete das Vieh auf der Alm, jeden Sommer allein",
  "trug Botschaften über Land und kannte alle Wege",

  // Aufbruch & Wanderschaft
  "zog aus, weil zu Hause kein Platz mehr war",
  "verließ das Dorf am Morgen nach einer Beerdigung",
  "folgte einem Rat, den ein Fremder gab",
  "brach auf, um ein Geschwister zu suchen",
  "wurde fortgeschickt und durfte nicht zurück",
  "ging fort, um das Glück zu suchen, wie man es dort nannte",
  "floh vor einer Heirat, die längst beschlossen war",
  "wanderte drei Jahre, ohne irgendwo zu bleiben",
  "reiste einem Versprechen hinterher",
  "lief davon und wurde nicht gesucht",
  "verließ das Land nach einer Missernte",
  "ging in den Wald und kam anders wieder heraus",
  "wurde von einem Fuhrmann mitgenommen und blieb in der nächsten Stadt",
  "suchte einen Ort, von dem nur erzählt wurde",

  // Begegnungen
  "half einem Alten am Wegrand und bekam etwas dafür",
  "teilte das letzte Brot mit einem Fremden",
  "traf jemanden am Kreuzweg und schlug den Rat aus",
  "wurde von einem Tier gewarnt und hörte darauf",
  "begegnete jemandem, der nach dem Namen fragte",
  "wurde einmal gerettet und weiß bis heute nicht von wem",
  "schloss einen Handel, dessen Preis noch offen ist",
  "bekam eine Gabe geschenkt und weiß nicht, wozu",
  "hat einen Wunsch frei und hebt ihn auf",
  "wurde in einem fremden Haus aufgenommen und blieb zu lange",
  "traf jemanden, der schon einmal fort gewesen war",
  "bekam drei Ratschläge und befolgte zwei",
  "wurde von einer weisen Frau erkannt",
  "schuldet jemandem eine Antwort",

  // Prüfungen & Verluste
  "bestand eine Aufgabe, an der zwei Ältere gescheitert waren",
  "verlor bei einer Wette mehr als das Eingesetzte",
  "schwieg ein Jahr lang, weil es verlangt wurde",
  "sah zurück, obwohl es verboten war",
  "hat eine Frist versäumt und trägt es seither",
  "verlor ein Geschwister im Wald",
  "war verzaubert und weiß nicht mehr, wie lange",
  "hat einen Namen genannt, der nicht genannt werden durfte",
  "wurde vertrieben, weil ein Vorwurf im Raum stand",
  "verlor die Stimme und bekam sie wieder",
  "hat einen Fluch getragen und ihn erfüllt",
  "wurde für schuldig gehalten und nie freigesprochen",
  "schlief länger, als ein Leben dauert",
  "hat sich einmal geweigert und alles verloren",
  "bezahlte für eine Heilung mit etwas anderem",
  "wurde geprüft, ohne zu wissen, dass es eine Prüfung war",

  // Stand & Wendung
  "war reich und ist es nicht mehr",
  "war arm und wurde für eine Tat belohnt",
  "heiratete über den Stand und bezahlt dafür",
  "bekam einen Hof, der einem anderen zustand",
  "diente einmal in einem Haus, das jetzt leer steht",
  "wurde von einem Herrn ausgezeichnet und danach vergessen",
  "trägt einen Titel, den niemand anerkennt",
  "lebte am Hof und ging freiwillig",
  "wurde Erbe, nachdem alle anderen fortgingen",
  "war lange verkleidet unterwegs",
  "gilt im Dorf als Sonderling und stört sich nicht daran",
  "hat sich vom Knecht zum Meister gearbeitet",
  "wurde begnadigt und weiß nicht, von wem",
  "kam zu Geld und hat es nicht behalten",
  "wurde vom Herrn gerufen und nicht wieder entlassen",
  "verlor den Hof an einen Schuldschein",

  // Jetzt
  "wartet seit Jahren auf eine Rückkehr",
  "hütet ein Versprechen, dessen Frist bald abläuft",
  "sucht einen Weg, den es nur einmal im Jahr gibt",
  "bewahrt etwas auf, das nicht ihm gehört",
  "kennt ein Geheimnis über den Herrn des Ortes",
  "wird im Dorf gemieden, seit etwas geschah",
  "hat drei Töchter und keine Aussteuer",
  "sucht jemanden, der einen Namen nennen kann",
  "schuldet dem Müller mehr, als der Hof wert ist",
  "wartet darauf, dass jemand die richtige Frage stellt",
];

/** Superhelden: Herkunft, Beruf, der Bruch, Einsätze, Behörden, Verluste. */
export const SUPERHELDEN_BACKGROUNDS: string[] = [
  // Herkunft & Kindheit
  "wuchs in einem Viertel auf, das zweimal evakuiert wurde",
  "wurde von den Großeltern großgezogen, nachdem die Eltern verschwanden",
  "wuchs im Schatten eines berühmten Namens auf",
  "verbrachte die Kindheit in einer Notunterkunft",
  "wuchs in einer Kleinstadt auf, in der nie etwas geschah",
  "war das Kind einer Streifenpolizistin",
  "wuchs neben dem Werksgelände auf und kannte die Sirene",
  "kam als Kind in die Stadt und hat sich nie ganz eingewöhnt",
  "wuchs in einem Heim auf, aus dem viele wegliefen",
  "war das einzige Kind der Familie ohne Auffälligkeiten",
  "wuchs mit einem Geschwister auf, das früh berühmt wurde",
  "verlor die Eltern bei einem Vorfall, der nie aufgeklärt wurde",
  "wuchs bei einem Elternteil auf, der für einen Konzern arbeitete",
  "wurde in einem Klinikflügel geboren, der später geschlossen wurde",
  "wuchs in einem Haushalt auf, in dem über den Vorfall nicht gesprochen wurde",
  "war Nachbarskind von jemandem, den heute jeder kennt",

  // Ausbildung & Beruf
  "studierte Chemie und arbeitet in der Qualitätssicherung",
  "wurde Rettungssanitäter, weil es schnell ging",
  "hat Journalismus studiert und schreibt Lokalnachrichten",
  "arbeitete sich in einem Konzern nach oben und stieg wieder aus",
  "wurde bei der Polizei ausgebildet und quittierte den Dienst",
  "lernte Elektriker und kennt die Stadt von unten",
  "behandelte in der Physiotherapie Leute, die nicht reden durften",
  "war beim Militär und hat nicht zu Ende gedient",
  "unterrichtet an einer Schule mit zwei Sicherheitsschleusen",
  "arbeitete in der Verwaltung und hat Akten gesehen",
  "vertritt vor Gericht Fälle, die sonst niemand annimmt",
  "betreibt eine Werkstatt und repariert, was gebracht wird",
  "arbeitete im Labor an etwas, das nie veröffentlicht wurde",
  "war bei der Feuerwehr in dem Jahr, in dem es dreimal brannte",
  "arbeitet nachts als Wachdienst und tagsüber gar nicht",
  "macht Sozialarbeit in einem Bezirk ohne Budget",

  // Der Bruch
  "war bei einem Unfall dabei, aus dem drei Leute anders herauskamen",
  "wurde als Freiwilliger für eine Studie angeworben",
  "überlebte einen Einsturz, den zwölf andere nicht überlebten",
  "wachte im Krankenhaus auf und konnte etwas, das vorher nicht ging",
  "erbte eine Fähigkeit, die eine Generation übersprungen hatte",
  "wurde in einem Labor behandelt und nie wieder einbestellt",
  "hat etwas gefunden, das nicht gefunden werden sollte",
  "war zur falschen Zeit am richtigen Ort",
  "wurde gerettet und wollte danach dasselbe tun",
  "merkte es zuerst an Kleinigkeiten und wartete Monate ab",
  "wurde als Kind getestet, und die Ergebnisse verschwanden",
  "war eines der wenigen Kinder, die den Vorfall überstanden",
  "hat sich die Fähigkeiten selbst gebaut, aus Ersatzteilen",
  "kam nach einem Jahr Abwesenheit verändert zurück",
  "übernahm die Rolle von jemandem, der aufgehört hat",
  "wurde ausgebildet, ohne zu erfahren wofür",

  // Einsätze & Öffentlichkeit
  "griff das erste Mal ein, ohne es geplant zu haben",
  "wurde bei einem Einsatz gefilmt und danach erkannt",
  "arbeitete jahrelang, ohne dass jemand davon wusste",
  "gehörte zu einer Gruppe, die sich zerstritt",
  "trägt einen Namen, den die Zeitungen vergeben haben",
  "wurde einmal gefeiert und danach verantwortlich gemacht",
  "rettete jemanden, der es bis heute bestreitet",
  "hat einen Einsatz abgebrochen und lebt damit",
  "wurde von der Stadt unter Vertrag genommen",
  "gab ein Interview, das alles veränderte",
  "hat einen Fall gelöst, den die Polizei geschlossen hatte",
  "wurde von einer Gruppe abgelehnt, der man beitreten wollte",
  "arbeitet mit der Polizei zusammen, inoffiziell",
  "hat zwei Jahre lang nichts getan",

  // Recht & Behörden
  "weigerte sich, sich registrieren zu lassen",
  "ließ sich registrieren und bereut es",
  "wird andernorts noch mit Haftbefehl gesucht",
  "sagte vor einem Ausschuss aus und nannte keinen Namen",
  "wurde freigesprochen und nie rehabilitiert",
  "saß ein Jahr in einer Anstalt für Leute mit Fähigkeiten",
  "steht auf einer Liste, die nicht öffentlich ist",
  "verlor die Zulassung nach einem Zwischenfall",
  "wurde verpflichtet und diente die Zeit ab",
  "hat mit einer Behörde einen Handel geschlossen",
  "wurde begnadigt, ohne darum gebeten zu haben",
  "arbeitet unter Auflagen, die monatlich geprüft werden",
  "flog kurz vor dem Abschluss aus dem Programm",
  "erstattete Anzeige gegen jemanden aus den eigenen Reihen",

  // Verluste
  "verlor einen Partner bei einem Einsatz",
  "konnte jemanden nicht retten und redet nicht darüber",
  "wurde von der eigenen Familie enttarnt",
  "verlor die Fähigkeiten und behielt die Feinde",
  "musste umziehen, nachdem die Adresse bekannt wurde",
  "verlor die Arbeit, als die Fehlzeiten auffielen",
  "hat ein Kind, das die Herkunft nicht kennt",
  "wurde von einem Freund verraten, der Geld brauchte",
  "lebte zwei Jahre unter falschem Namen",
  "hatte einen Mentor, der die Seite gewechselt hat",
  "verlor ein einziges Mal die Beherrschung",
  "musste eine Stadt verlassen, in der man beliebt war",

  // Jetzt
  "hat sich zurückgezogen und wird trotzdem gerufen",
  "sucht jemanden, der vor Jahren verschwand",
  "bildet jemanden aus, der zu schnell lernt",
  "arbeitet an einer Aufnahme, die alles beweisen würde",
  "wartet auf ein Urteil, das im Frühjahr fällt",
  "sammelt Belege gegen einen Konzern",
  "lebt in einem Viertel, das die eigene Vergangenheit kennt",
  "hat ein Angebot bekommen und noch nicht abgelehnt",
  "führt ein doppeltes Leben, das gerade nicht mehr aufgeht",
  "wird beobachtet und weiß nicht von wem",
  "hat einen alten Fall wieder aufgemacht",
  "versucht, ein Versprechen zu halten, das zu groß war",
];

export const BACKGROUNDS_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_BACKGROUNDS,
  fantasy: FANTASY_BACKGROUNDS,
  steampunk: STEAMPUNK_BACKGROUNDS,
  cyberpunk: CYBERPUNK_BACKGROUNDS,
  historisch: HISTORISCH_BACKGROUNDS,
  western: WESTERN_BACKGROUNDS,
  scifi: SCIFI_BACKGROUNDS,
  maerchen: MAERCHEN_BACKGROUNDS,
  superhelden: SUPERHELDEN_BACKGROUNDS,
};

/**
 * Ein bis drei prägende Ereignisse aus dem Vorrat des Genres.
 *
 * Ohne bekanntes Genre fällt die Wahl auf „Gegenwart" – anders als bei den
 * Berufen wird **nicht** über alle Listen gemischt: ein Konzernvertrag neben
 * einem gebrochenen Lehnseid wäre kein Charakter, sondern zwei.
 *
 * Getrennt durch Semikolon, nicht durch Komma: die Einträge enthalten selbst
 * Kommas („gewann einen Prozess und verlor alles dabei"), und mit Komma
 * verbunden verschwämme die Grenze zwischen zwei Ereignissen.
 */
export function randomBackground(genre?: string): string {
  const pool = BACKGROUNDS_BY_GENRE[genre ?? ""] ?? GEGENWART_BACKGROUNDS;
  return pickSome(pool, 1, 3).join("; ");
}
