import { pickSome } from "./inspiration";

/**
 * Orte für den Würfel am Szenario-Feld „Ort" – **je Genre eine eigene Liste zu
 * 100 Einträgen**.
 *
 * Aufgebaut wie `backgrounds.ts` und aus demselben Grund nach Genre getrennt
 * statt markiert: ein Ort trägt sein Genre in sich. „Ein Wohnblock, dessen
 * Aufzug seit Jahren steht" und „ein Turm, in dem die Treppe endet, bevor sie
 * oben ankommt" beschreiben dieselbe Enge – aber in Bildern, die sich nicht
 * austauschen lassen.
 *
 * Rein lokal, ohne API, wie alle Würfel im Projekt.
 *
 * Jeder Eintrag nennt den Ort **und ein Detail, das ihn kippen lässt** – etwas
 * Kaputtes, Verschwiegenes oder Unfertiges. Ein Ort ohne Riss ist eine Kulisse;
 * einer mit Riss ist ein Anfang.
 *
 * **Zwei Ebenen je Genre.** Hier stand einmal: „Ein Eintrag ist ein
 * vollständiger Ort, kein Baustein … ein Szenario spielt an einem Ort, nicht an
 * zweieinhalb." Das galt, solange das Feld einen Schauplatz aufnahm. Inzwischen
 * beschreibt es ein **Gebiet mit mehreren Orten darin** – eine Geschichte
 * spielt selten an einem einzigen Punkt –, und dafür braucht der Würfel die
 * Unterscheidung:
 *
 * - `*_AREAS` – **Rahmen**: worin gespielt wird. Stadt, Landstrich, Siedlung,
 *   Station. Die Antwort auf „wo spielt das?".
 * - `*_SPOTS` – **Schauplätze**: Orte *darin*, an denen sich fremde Leben
 *   kreuzen. Arbeitsplätze, Einrichtungen, Wege, Werkstätten.
 *
 * `*_PLACES` bleibt als Zusammenfassung beider bestehen, damit nichts bricht,
 * was die ganze Liste will (etwa die Formbeispiele in `scenarioSamples.ts`).
 *
 * Die Teilung ist **keine neue Textarbeit**, sondern die Gliederung, die in
 * diesen Listen von Anfang an als Rubrik-Kommentar stand („Stadt", „Provinz &
 * Land" gegen „Arbeitsplätze", „Einrichtungen"). Sie ist damit auch nur so
 * genau wie diese Rubriken: Ein einzelner Eintrag kann auf der falschen Ebene
 * sitzen. Für den Würfel reicht das – er ist ein Anfang, kein Ergebnis.
 */

/** Gegenwart: Stadt, Provinz, Arbeitsplätze, Einrichtungen, Unterwegs. */
export const GEGENWART_AREAS: string[] = [
  // Stadt
    "Ein Altbauviertel, in dem die letzten alten Mieter zwischen sanierten Wohnungen ausharren",
    "Eine Hochhaussiedlung am Stadtrand, deren Einkaufszentrum zur Hälfte leer steht",
    "Ein Hafenviertel, in dem die Kräne stillstehen und die Mieten trotzdem steigen",
    "Eine Innenstadt, in der jeden Monat ein weiteres Ladenlokal zum Späti wird",
    "Ein Bahnhofsviertel, das nach zweiundzwanzig Uhr einer anderen Stadt gehört",
    "Eine Straße mit zwei Moscheen, einer Kirche und keinem Supermarkt",
    "Ein Studentenviertel, aus dem die Studenten längst weggezogen sind",
    "Ein Neubaugebiet, in dem noch kein Baum groß genug für Schatten ist",
    "Ein Gewerbegebiet mit einer einzigen Bushaltestelle und drei Schichten",
    "Ein Stadtteil, der seit dreißig Jahren auf die versprochene U-Bahn wartet",
    "Ein Häuserblock, in dem alle einander kennen und niemand miteinander spricht",
    "Eine Fußgängerzone, die abends von Sicherheitsdiensten geräumt wird",
    "Ein Kleingartenverein, eingekesselt zwischen Autobahn und Baugrube",
    "Ein Viertel, in dem gerade der erste Concept Store aufgemacht hat",
    "Eine Hinterhofwerkstatt zwischen zwei Galerien, noch nicht verdrängt",
    "Ein Wohnblock, dessen Aufzug seit zwei Jahren stillsteht",
    "Ein Platz, auf dem sich morgens die Tagelöhner und mittags die Touristen sammeln",
    "Eine Ausfallstraße, an der jedes zweite Haus einen Schallschutz-Antrag laufen hat",
    "Ein Stadtteil, in dem die Feuerwehr zu zweit ausrückt und die Polizei zu viert",
    "Ein Wohnhaus mit sieben Klingelschildern und elf Briefkästen",
  // Provinz & Land
    "Ein Dorf, dessen letzte Kneipe zum Wohnhaus umgebaut wurde",
    "Eine Kleinstadt, in der die Fabrik zumachte und die Straßennamen blieben",
    "Ein Ort mit einem Freibad, das nur noch an Wochenenden aufmacht",
    "Ein Weiler, in dem drei Höfe bewirtschaftet werden und neun leer stehen",
    "Eine Gemeinde, die um jeden Schüler kämpft, damit die Schule bleibt",
    "Ein Küstenort, der neun Monate im Jahr sich selbst gehört",
    "Ein Kurort, dessen Klinik verkauft wurde und dessen Gäste ausblieben",
    "Ein Bergdorf, das im Winter über eine einzige Straße erreichbar ist",
    "Ein Ort direkt an der Grenze, wo man zum Einkaufen ins Nachbarland fährt",
    "Eine Streusiedlung, in der der Bus zweimal am Tag fährt, außer in den Ferien",
    "Ein Dorf mit einem Windpark, über den seit acht Jahren gestritten wird",
    "Eine Kleinstadt, in der alle im selben Werk arbeiten oder gearbeitet haben",
    "Ein Ort, dessen Jugend am Freitag in die nächste Stadt fährt und sonntags zurück",
    "Eine Marschlandschaft, in der die Deiche jedes Jahr etwas höher werden",
    "Ein Tagebaurand, an dem drei Dörfer auf ihre Umsiedlung warten",
    "Ein Dorf, in dem seit dem Hochwasser jeder weiß, wer wem geholfen hat",
    "Eine Insel, auf der die Fähre den Takt des Tages vorgibt",
    "Ein Talort, durch den täglich vierhundert Lastwagen fahren",
    "Eine Gegend, in der die Handynetze an der Kreisgrenze enden",
    "Ein Ort mit einem neuen Logistikzentrum und keiner Wohnung mehr unter tausend Euro",
];

export const GEGENWART_SPOTS: string[] = [
  // Arbeitsplätze
    "Eine Großküche, in der sieben Sprachen gesprochen und keine gelernt wird",
    "Ein Callcenter im dritten Stock über einem Möbelhaus",
    "Eine Lagerhalle, in der ein Scanner den Takt vorgibt",
    "Eine Werkstatt, die vom Sohn übernommen wurde, der sie nicht wollte",
    "Ein Krankenhaus, dessen Station seit Monaten in Unterbesetzung fährt",
    "Ein Labor in einem Institut, dessen Förderung im Sommer ausläuft",
    "Eine Redaktion, die von zwölf auf vier Leute geschrumpft ist",
    "Ein Hotel, das eine Kette gekauft hat und nun anders heißt",
    "Ein Familienbetrieb, in dem drei Generationen dieselbe Werkbank benutzen",
    "Eine Baustelle, auf der vier Subunternehmer nebeneinanderher arbeiten",
    "Ein Restaurant mit einem Stern und einer Küchenbrigade am Anschlag",
    "Ein Coworking-Space, in dem jeder von seinem eigenen Projekt lebt",
    "Eine Molkerei, die als Letzte in der Region noch annimmt",
    "Ein Recyclinghof, an dem man mehr über die Stadt erfährt als im Rathaus",
    "Eine Schreinerei, deren Auftragsbuch voll und deren Nachfolge offen ist",
    "Ein Taxiunternehmen mit sechs Wagen und zwei Fahrern, die alles machen",
    "Ein Fotostudio, das von Bewerbungsbildern und Beerdigungen lebt",
    "Eine Apotheke, die die halbe Nachbarschaft beim Vornamen kennt",
    "Ein Kino mit zwei Sälen und einem Betreiber, der nicht aufgeben will",
    "Ein Musikstudio im Keller, dessen Miete drei Leute zusammenlegen",
  // Einrichtungen
    "Eine Gesamtschule, an der jedes Jahr die Hälfte der Referendare geht",
    "Ein Pflegeheim, in dem der Frühdienst um halb sechs allein beginnt",
    "Eine Sozialstation, deren Warteliste länger ist als ihr Kalender",
    "Ein Jugendzentrum, dessen Förderung Jahr für Jahr neu beantragt wird",
    "Eine Bibliothek, die zur Wärmestube geworden ist, ohne dass es jemand ausspricht",
    "Ein Amt, in dem Termine sechs Wochen vorher vergeben werden",
    "Eine Kirchengemeinde mit einer vollen Tafel und einem leeren Gottesdienst",
    "Ein Sportverein, der über den einen Trainer zusammenhält",
    "Ein Gericht, dessen Verfahren sich seit Jahren stauen",
    "Eine Unterkunft, die als Provisorium gebaut wurde und im achten Jahr steht",
    "Ein Tierheim, das keine Katzen mehr aufnehmen kann",
    "Eine Musikschule im Gebäude der stillgelegten Grundschule",
    "Ein Hospiz mit Blick auf einen Parkplatz",
    "Eine Suchtberatung im Erdgeschoss, direkt neben einem Wettbüro",
    "Ein Frauenhaus, dessen Adresse alle im Ort kennen",
    "Eine Volkshochschule, deren beliebtester Kurs Deutsch ist",
    "Ein Wahllokal in einer Turnhalle, in der es nach Bohnerwachs riecht",
    "Ein Forschungsschiff im Winterhafen, mit halber Besatzung",
    "Eine Justizvollzugsanstalt am Ortsrand, um die ein Radweg führt",
    "Ein Rechenzentrum auf einem Acker, das keinen einzigen Arbeitsplatz brachte",
  // Unterwegs & Dazwischen
    "Ein Nachtzug, in dem sich dieselben Leute jede Woche begegnen",
    "Eine Autobahnraststätte, die nachts ihr eigenes Publikum hat",
    "Ein Fernbus auf der Strecke zwischen zwei Ländern",
    "Ein Flughafen-Transitbereich, in dem jemand seit vier Tagen wartet",
    "Eine Fähre, die zweimal täglich dieselben Gesichter transportiert",
    "Ein Wohnmobil auf einem Stellplatz, der als Dauerlösung gilt",
    "Eine Ferienwohnung, die zwischen zwei Buchungen leer steht",
    "Ein Pilgerweg, auf dem im Herbst nur noch die Ernsthaften gehen",
    "Ein Campingplatz, dessen Dauercamper eine eigene Ordnung haben",
    "Eine Umsteigestation, an der man nachts vierzig Minuten wartet",
    "Ein Frachtschiff, auf dem der Koch die einzige Konstante ist",
    "Ein Ferienhaus im Februar, ohne Nachbarn im Umkreis von zwei Kilometern",
    "Ein Zeltplatz nach dem Festival, an dem die Hälfte stehen gelassen wurde",
    "Ein Krankentransport, der täglich dieselbe Strecke fährt",
    "Eine Parkbucht mit Blick, auf der abends immer dieselben Autos stehen",
    "Ein Straßenzug, durch den seit dem Umbau kein Auto mehr fährt",
    "Ein Baumarktparkplatz, auf dem sich morgens um sieben etwas anderes abspielt",
    "Ein Waldstück am Stadtrand, in dem seit Wochen jemand wohnt",
    "Eine Brücke, unter der jemand seine Sachen ordentlich stapelt",
    "Ein Grenzübergang, an dem seit dem Sommer wieder kontrolliert wird",
];

export const GEGENWART_PLACES: string[] = [
  ...GEGENWART_AREAS,
  ...GEGENWART_SPOTS,
];

/** Fantasy: Siedlungen, Wildnis, Bauwerke, Zwielicht, Heiliges. */
export const FANTASY_AREAS: string[] = [
  // Siedlungen
    "Ein Dorf am Waldrand, dessen Zaun jedes Jahr ein Stück näher an die Häuser rückt",
    "Eine Handelsstadt an einer Furt, die den Zoll selbst festlegt",
    "Ein Bergwerksort, dessen tiefster Stollen zugemauert wurde und über den niemand redet",
    "Eine Hafenstadt mit zwei Häfen: einem für Waren, einem für alles andere",
    "Ein Dorf, das sein Getreide dem Fluss verdankt und sein Schweigen dem Herrn",
    "Eine Stadt mit einer Mauer, die für die doppelte Einwohnerzahl gebaut wurde",
    "Ein Weiler auf einer Lichtung, den man ohne Führer nicht wiederfindet",
    "Eine Grenzstadt, in der zwei Sprachen und drei Gesetze gelten",
    "Ein Fischerdorf, dessen Boote nachts nicht auslaufen",
    "Eine Karawanserei am Wüstenrand, in der Waffen an der Tür bleiben",
    "Ein Dorf, das um einen Brunnen gebaut wurde, der seit dem Frühjahr trocken liegt",
    "Eine Stadt, in der die Gilden mehr entscheiden als der Rat",
    "Ein Bergdorf, das im Winter von der Welt abgeschnitten ist und das mag",
    "Eine Siedlung von Vertriebenen, die niemand offiziell zur Kenntnis nimmt",
    "Ein Marktflecken, an dem sich vier Straßen und vier Zuständigkeiten kreuzen",
    "Eine Pfahlbausiedlung im Sumpf, erreichbar über Stege, die man kennen muss",
    "Ein Dorf mit einer Schmiede, die nie kalt wird, und einer Kirche, die selten warm ist",
    "Eine Stadt, die auf den Ruinen einer älteren steht und deren Keller tiefer reichen als bekannt",
    "Ein Ort, in dem alle denselben Nachnamen tragen",
    "Eine Siedlung entlang einer alten Heerstraße, die niemand mehr instand hält",
  // Wildnis
    "Ein Wald, in dem die Wege sich nach der Jahreszeit ändern",
    "Ein Moor, das im Sommer Torf und im Winter Vermisste hergibt",
    "Ein Hochpass, der drei Monate im Jahr offen ist",
    "Eine Steppe, über die zweimal jährlich die Herden und einmal die Reiter ziehen",
    "Ein Küstenstreifen mit Klippen, an denen regelmäßig Wrackgut anlandet",
    "Ein Tal, in dem es früher dunkel wird als überall sonst",
    "Ein Urwald, dessen Bäume älter sind als jedes Königreich der Gegend",
    "Ein Gletscher, der jedes Jahr etwas freigibt, was besser eingefroren geblieben wäre",
    "Eine Insel, die auf keiner beiden Seekarten gleich eingezeichnet ist",
    "Ein Flusstal, das alle sieben Jahre über die Ufer tritt, immer im selben Monat",
    "Eine Wüste mit einer Straße aus Steinplatten, die von niemandem stammt",
    "Ein Sumpfgebiet, in dem Feuer nicht brennen will",
    "Eine Heide, auf der das Vieh gedeiht und die Menschen nicht bleiben",
    "Ein Höhlensystem, das weiter reicht als jede Karte behauptet",
    "Ein See, dessen Grund niemand ausgelotet hat",
    "Ein Wald, den die Dörfler nur zu dritt betreten",
    "Eine Schlucht mit einer einzigen Brücke und einem Wärter",
    "Eine Vulkaninsel, deren Boden alles wachsen lässt und alle nervös macht",
    "Ein Tal voller Steinsäulen, um die man einen Bogen macht",
    "Eine Küste, an der die Ebbe einen Weg freigibt und die Flut ihn nimmt",
];

export const FANTASY_SPOTS: string[] = [
  // Bauwerke
    "Eine Burg, die zwei Belagerungen überstand und den Frieden kaum",
    "Ein Turm, dessen obere Stockwerke seit Generationen verschlossen sind",
    "Eine Festung an einer Grenze, die es nicht mehr gibt",
    "Ein Palast, in dem mehr Diener leben als Herrschaft",
    "Eine Brücke aus alter Zeit, die niemand nachbauen könnte",
    "Ein Leuchtturm, dessen Feuer seit dem Herbst nicht mehr brennt",
    "Ein Aquädukt, das eine Stadt versorgt, die nicht mehr steht",
    "Eine Bibliothek, deren Katalog vollständiger ist als ihr Bestand",
    "Ein Wachturm auf einem Pass, besetzt von vier Leuten und einem Hund",
    "Eine Zitadelle mitten in der Stadt, die nach innen zeigt statt nach außen",
    "Ein Bergwerk, dessen Förderturm noch steht und dessen Schacht geflutet ist",
    "Eine Ruine, in der ein Dorf sein Vieh unterstellt",
    "Ein Kanalsystem unter der Stadt, älter als die Stadt",
    "Eine Grabanlage, die als Steinbruch benutzt wird",
    "Ein Herrenhaus, dessen Besitzer seit drei Jahren niemand gesehen hat",
    "Eine Mühle am Fluss, die dem Müller gehört und über die alle reden",
    "Ein Torhaus, an dem jeder zahlt außer denen, die es nicht müssen",
    "Eine Arena, die man zum Getreidespeicher umgebaut hat",
    "Ein Observatorium auf einem Berg, aus dem seit Jahren niemand herunterkam",
    "Ein Kloster mit einer Mauer, die eher nach innen als nach außen gerichtet scheint",
  // Zwielicht
    "Eine Diebesgilde, die sich als Fuhrunternehmen führt",
    "Ein Wirtshaus, in dem an einem Tisch nie jemand sitzt",
    "Ein Schwarzmarkt, der jede Woche den Ort wechselt",
    "Ein Hafenlager, dessen Inventar nicht mit den Zollbüchern übereinstimmt",
    "Eine Spielhölle, in der man auch mit anderem als Geld bezahlt",
    "Ein Badehaus, in dem mehr verhandelt als gebadet wird",
    "Ein Bordell mit den besten Informationen der Stadt",
    "Eine Kaschemme im Kellergewölbe, mit zwei Ausgängen und einer Regel",
    "Ein Pfandhaus, das die halbe Stadt in Büchern hat",
    "Eine Schmugglerbucht, die nur bei bestimmtem Wind anzulaufen ist",
    "Ein Söldnerlager vor den Toren, das man nicht wegschicken kann",
    "Ein Sklavenmarkt, der offiziell abgeschafft ist",
    "Eine Gasse, in der die Stadtwache zu zweit nicht mehr hineingeht",
    "Ein Gasthof an der Straße, aus dem regelmäßig Gäste nicht weiterreisen",
    "Ein Alchemistenviertel, dessen Rauch die Nachbarschaft vertrieben hat",
    "Ein Fälscherhaus, das Siegel für vier Königreiche führt",
    "Eine Arena für verbotene Kämpfe, unter einer legalen",
    "Ein Kartenhaus, in dem Karten gezeichnet werden, die es nicht geben darf",
    "Ein Kontor, das Waren versichert, die nie verschifft wurden",
    "Ein Tunnel unter der Stadtmauer, den alle kennen und niemand meldet",
  // Heiliges & Unheimliches
    "Ein Tempel, dessen Priesterschaft sich in zwei Auslegungen gespalten hat",
    "Ein heiliger Hain, in dem seit dem Frühling nicht mehr geopfert wird",
    "Eine Wallfahrtsstätte, deren Wunder ausgeblieben sind",
    "Ein Schrein an einer Wegkreuzung, an dem jeder etwas ablegt",
    "Ein Kloster, das Zuflucht gewährt und keine Fragen stellt",
    "Eine Kathedrale, die seit sechzig Jahren im Bau ist",
    "Ein Orden, dessen Regel strenger geworden ist als sein Glaube",
    "Ein Friedhof, auf dem die Gräber nach Westen zeigen, alle bis auf eins",
    "Eine Quelle, der man Heilkraft nachsagt und deren Wasser man abkocht",
    "Ein Steinkreis, um den herum gepflügt wird",
    "Ein Turm der Magier, der Lehrgeld verlangt und keine Fragen beantwortet",
    "Eine Akademie, an der zwei Schulen unterrichtet werden, die einander verachten",
    "Ein verlassenes Heiligtum, in dem noch Kerzen brennen",
    "Ein Ossarium unter einer Kirche, dessen Zugang nur der Küster kennt",
    "Eine Insel der Eremiten, die einmal im Jahr Besuch dulden",
    "Ein Ort, an dem Eide gelten und alle das ernst nehmen",
    "Eine Krypta, die man geöffnet hat, weil Platz gebraucht wurde",
    "Ein Berg, den zu besteigen als Frevel gilt und den doch jeder Hirte kennt",
    "Ein Waldheiligtum, das zwei Dörfer für sich beanspruchen",
    "Ein Baum am Dorfplatz, unter dem Recht gesprochen wird",
];

export const FANTASY_PLACES: string[] = [
  ...FANTASY_AREAS,
  ...FANTASY_SPOTS,
];

/** Steampunk: Industriestadt, Verkehr, Werkstätten, Gesellschaft, Untergrund. */
export const STEAMPUNK_AREAS: string[] = [
  // Industriestadt
    "Ein Fabrikviertel, über dem der Rauch tiefer hängt als die Dächer",
    "Eine Stadt mit einer Uhr, nach der sich alle Schichten richten",
    "Ein Werksgelände mit eigenem Bahnanschluss und eigener Gerichtsbarkeit",
    "Eine Arbeitersiedlung, die der Fabrik gehört, samt Läden und Schule",
    "Ein Kesselhaus, das die halbe Stadt mit Dampf versorgt",
    "Ein Hüttenwerk, dessen Feuer seit vierzig Jahren nicht aus war",
    "Ein Viertel, in dem die Wäsche grau von der Leine kommt",
    "Eine Gasanstalt am Fluss, deren Geruch bis in die Oberstadt zieht",
    "Ein Kanal, an dem Lastkähne im Minutentakt vorbeiziehen",
    "Eine Stadt auf zwei Ebenen: unten die Rohre, oben die Fassaden",
    "Ein Bahnbetriebswerk mit dreihundert Beschäftigten und einer Werksgewerkschaft",
    "Eine Spinnerei, in der der Lärm das Sprechen ersetzt hat",
    "Ein Kohlenhafen, dessen Staub sich in allem absetzt",
    "Ein Hochofenwerk, um das ein ganzer Ort gewachsen ist",
    "Eine Manufaktur, die auf Feinmechanik umgestellt hat und die Hälfte entließ",
    "Ein Elektrizitätswerk, das erst wenige Straßen versorgt und alle Interessen weckt",
    "Ein Viertel, in dem die Zisternen wichtiger sind als die Brunnen",
    "Eine Werft, die vom Segelbau auf Dampf umstellt und beide Zünfte gegen sich hat",
    "Eine Bergarbeiterstadt, deren Halden höher sind als ihre Kirche",
    "Ein Industrierevier, in dem drei Firmen alles besitzen außer den Menschen",
];

export const STEAMPUNK_SPOTS: string[] = [
  // Verkehr & Luft
    "Ein Luftschiffhafen, dessen Türme über den Fabrikschloten stehen",
    "Ein Kopfbahnhof mit Glasdach und einer Halle, in der man sich verliert",
    "Ein Rangierbahnhof, auf dem nachts mehr los ist als tagsüber",
    "Eine Bergbahn, die vier Dörfer erschließt und drei ruiniert hat",
    "Eine Zeppelinwerft, an der zweitausend Menschen arbeiten und niemand versichert ist",
    "Ein Hafen, in dem Segler und Dampfer um jeden Liegeplatz streiten",
    "Eine Pneumatikpost, deren Röhren unter der ganzen Innenstadt liegen",
    "Ein Schleusenwerk, das den Warenfluss zweier Provinzen regelt",
    "Eine Untergrundbahn, deren erste Linie gerade eröffnet wurde",
    "Ein Postkutschenwechsel, den die Eisenbahn überflüssig gemacht hat",
    "Ein Tunnel durch den Berg, an dem seit neun Jahren gebaut wird",
    "Eine Schwebebahn über einem Fluss, die als Wunder gilt und als Zumutung",
    "Ein Kanalhafen mit Kränen, die noch von Hand bedient werden",
    "Eine Straßenbahnremise, deren Pferde gerade durch Motoren ersetzt werden",
    "Ein Frachtluftschiff auf Zwischenlandung, mit Ladung ohne Papiere",
    "Ein Leuchtfeuerturm mit Dampfsirene, die man drei Meilen weit hört",
    "Eine Eisenbahnbrücke, die man für doppelte Last freigegeben hat",
    "Ein Depot, in dem Lokomotiven abgestellt sind, für die es keine Strecke gibt",
    "Ein Umschlagplatz, an dem Schiene, Kanal und Straße aufeinandertreffen",
    "Eine Ballonstation auf einem Hügel, von der aus die Stadt vermessen wird",
  // Werkstätten & Labore
    "Eine Werkstatt für Feinmechanik, in der drei Uhrmacher und ein Erfinder sitzen",
    "Ein Laboratorium im Dachgeschoss, dessen Vermieter nichts weiß",
    "Ein Patentamt, dessen Archiv niemand mehr überblickt",
    "Eine Erfinderwerkstatt, die von einem einzigen Geldgeber abhängt",
    "Ein anatomisches Theater, in dem öffentlich vorgeführt wird",
    "Eine Prothesenwerkstatt gegenüber dem Werkstor",
    "Ein chemisches Institut, dessen Abwässer in den Stadtfluss gehen",
    "Ein Observatorium mit einem Instrument, das größer ist als sein Etat",
    "Eine Maschinenhalle, in der Prototypen stehen, die nie liefen",
    "Ein Konstruktionsbüro, in dem an einer Sache gearbeitet wird, die niemand benennt",
    "Eine Werkstatt für Automaten, deren Auftraggeber anonym bleiben",
    "Ein Kesselschmiede-Hof, auf dem die Prüfstelle nie erscheint",
    "Ein Institut für Elektrizität, das mit Spenden und Aufsehen finanziert wird",
    "Eine Druckerei mit einer Rotationsmaschine und zwei Konkurrenzblättern",
    "Eine Fotografenwerkstatt, in der Verfahren erprobt werden, die noch giftig sind",
    "Ein Uhrturm, dessen Werk ein Mann allein instand hält",
    "Eine Waffenmanufaktur mit einem Auftrag, der die Stadt ernährt",
    "Ein Ballonlabor, in dem Gasgemische ausprobiert werden",
    "Eine Werkstatt für Rechenmaschinen, deren Bestellungen aus einer Behörde kommen",
    "Ein Prüfstand außerhalb der Stadt, dessen Lärm nachts zu hören ist",
  // Gesellschaft
    "Ein Herrenclub, in dem über Konzessionen entschieden wird",
    "Eine Handelskammer, die mehr Macht hat als der Stadtrat",
    "Ein Opernhaus, das ein Fabrikant gestiftet und nach sich benannt hat",
    "Ein Kurbad, in das die Industriellen fahren, wenn der Rauch zu dick wird",
    "Eine Villenkolonie auf der windzugewandten Seite der Stadt",
    "Ein Vortragssaal, in dem Fortschritt und Empörung dasselbe Publikum haben",
    "Eine Weltausstellungshalle, drei Monate vor der Eröffnung",
    "Ein Bankhaus, das drei Werke finanziert und alle drei kontrolliert",
    "Ein Rathaus, dessen Bauamt seit Jahren dieselben Genehmigungen erteilt",
    "Eine Zeitungsredaktion, die von Anzeigen der Fabriken lebt",
    "Ein Gewerkschaftshaus, das man zweimal geräumt hat",
    "Ein Armenhaus, das die Stadt betreibt und die Kirche verwaltet",
    "Eine Bergwerksdirektion, die dreißig Kilometer von jedem Schacht entfernt liegt",
    "Ein Kaufhaus mit elektrischem Licht und Personal, das im Dachgeschoss schläft",
    "Ein Kolonialkontor, dessen Waren keiner nach ihrer Herkunft fragt",
    "Eine Akademie, an der Ingenieure und Militärs zusammen ausgebildet werden",
    "Ein Gerichtssaal, in dem gerade der erste Prozess um einen Arbeitsunfall läuft",
    "Ein Kaffeehaus, in dem Aktienkurse ausgerufen werden",
    "Ein Krankenhaus, das eine Stiftung trägt und ein Werksarzt leitet",
    "Ein Waisenhaus, dessen Zöglinge mit vierzehn in die Fabrik gehen",
  // Untergrund
    "Ein Kanalnetz, in dem Menschen leben, die dort nicht gemeldet sind",
    "Eine stillgelegte Strecke, die ein anderes Gewerbe übernommen hat",
    "Ein Schmugglerlager unter einem Kohlenhof",
    "Eine Kellerkneipe, in der die Streikkasse verwaltet wird",
    "Ein aufgelassener Schacht, durch den man unter die Stadtmauer kommt",
    "Eine Untergrundpresse in einer Kellerdruckerei",
    "Ein Lager für gestohlene Bauteile, sortiert wie ein Ersatzteillager",
    "Eine Boxarena unter einem Lagerhaus, mit Wetteinnahmen für drei Parteien",
    "Ein Netz von Kriechgängen zwischen den Kesselhäusern",
    "Ein Opiumhaus im Hafenviertel, mit einer Hintertür zur Zollstraße",
    "Ein Depot mit Sprengstoff, für das niemand zuständig sein will",
    "Ein Versammlungsraum ohne Fenster, dessen Adresse mündlich weitergegeben wird",
    "Eine Werkstatt, die Fabrikmarken fälscht",
    "Ein Tunnel, den die Arbeiter selbst gegraben haben, um den Werksschutz zu umgehen",
    "Ein Zwischenboden über einer Halle, in dem jemand wohnt",
    "Eine Kammer im Fundament, die auf keinem Bauplan steht",
    "Eine Zisterne, die als Versammlungsort dient, weil sie den Schall schluckt",
    "Ein Abwasserstollen, durch den man in drei Viertel gleichzeitig kommt",
    "Ein Kohlenkeller mit doppeltem Boden",
    "Ein Katakombenabschnitt, in dem eine Werkstatt ohne Konzession arbeitet",
];

export const STEAMPUNK_PLACES: string[] = [
  ...STEAMPUNK_AREAS,
  ...STEAMPUNK_SPOTS,
];

/** Cyberpunk: Megacity, Konzern, Slums, Netz, Ödland. */
export const CYBERPUNK_AREAS: string[] = [
  // Megacity
    "Ein Stadtblock, dessen unterste zwölf Etagen kein Tageslicht sehen",
    "Ein Viertel, in dem die Werbeflächen heller sind als jede Straßenlaterne",
    "Ein Wohnturm mit dreitausend Einheiten und einem funktionierenden Aufzug",
    "Eine Sperrzone, die nach einem Chemieunfall nie freigegeben wurde",
    "Ein Distrikt, in dem drei Sicherheitsfirmen konkurrierende Zuständigkeiten haben",
    "Ein Kapselhotel-Komplex, in dem Leute seit Jahren wohnen",
    "Ein Marktviertel unter einer Hochstraße, mit eigener Stromversorgung",
    "Eine Zone, in der die Netzabdeckung absichtlich abgeschaltet wurde",
    "Ein Hochhaus, dessen obere Hälfte einer Firma und untere niemandem gehört",
    "Ein Stadtteil, der offiziell abgerissen ist und in dem vierzigtausend leben",
    "Eine Uferpromenade, die man drei Meter höher neu gebaut hat",
    "Ein Verkehrsknoten mit vier Ebenen, an dem sich alles trifft, was sich sonst meidet",
    "Ein Viertel, in dem Mieten in Rechenleistung bezahlt werden",
    "Eine Altstadt unter einer Kuppel, konserviert und eintrittspflichtig",
    "Ein Bezirk, dessen Wasserversorgung privatisiert wurde und stundenweise läuft",
    "Ein Wohnkomplex mit Gesichtserkennung an jedem Treppenhaus",
    "Ein Hafen, der vollautomatisch läuft und in dem trotzdem tausend Menschen arbeiten",
    "Eine Straße, die von zwei Banden auf halber Länge geteilt wird",
    "Ein Viertel, in dem die Klimaanlagen mehr Strom brauchen als die Wohnungen",
    "Ein Stadtgebiet, das nach dem Sturm nie wieder ans Netz ging",
  // Ödland & Draußen
    "Ein Autobahnkreuz, um das eine Siedlung gewachsen ist",
    "Eine Industriebrache, auf der nichts wächst und trotzdem jemand wohnt",
    "Ein Solarfeld in der Wüste, bewacht von zwei Leuten und einer Drohne",
    "Ein ausgetrocknetes Flussbett, auf dem Konvois fahren",
    "Eine Küstenstadt, deren untere Straßen bei Flut unter Wasser stehen",
    "Ein Farmkomplex, der einem Konzern gehört und keine Nachbarn duldet",
    "Ein Windpark, dessen Wartungsmannschaft seit Monaten nicht abgelöst wurde",
    "Eine Schnellstraße durch verlassenes Land, mit Tankstellen alle zweihundert Kilometer",
    "Eine Bergbaustadt, die abgebaut wurde und deren Loch geblieben ist",
    "Ein Grenzposten zwischen zwei Konzerngebieten",
    "Ein Frachtflughafen mitten im Nichts, nachts hell erleuchtet",
    "Eine Wasseraufbereitungsanlage, um die drei Siedlungen streiten",
    "Ein Truck-Stopp, der zugleich Markt, Klinik und Gericht ist",
    "Eine Geisterstadt mit funktionierendem Netzanschluss",
    "Ein Bahndamm, entlang dessen sich eine Siedlung zieht",
    "Ein aufgegebenes Kraftwerk, in dem eine Gemeinschaft Strom abzweigt",
    "Ein Küstenstreifen voller Schiffswracks, die zerlegt werden",
    "Ein Testgelände, das seit Jahren nicht mehr genutzt und nie freigegeben wurde",
    "Eine Sperrzone um einen Reaktor, in der Menschen leben, die dorthin gehören",
    "Ein Hochplateau mit einer Antennenanlage und zwölf Bewohnern",
];

export const CYBERPUNK_SPOTS: string[] = [
  // Konzern
    "Ein Firmencampus mit eigener Werkssicherheit und eigenem Arbeitsrecht",
    "Ein Konzernturm, dessen oberste Etagen keinen Aufzugsknopf haben",
    "Ein Forschungslabor, dessen Existenz in keiner Bilanz auftaucht",
    "Eine Fertigungsanlage, in der zwölf Menschen und viertausend Maschinen arbeiten",
    "Ein Rechenzentrum, das mit Flusswasser gekühlt wird und den Fluss aufheizt",
    "Eine Konzernklinik, in der Behandlung an den Arbeitsvertrag gekoppelt ist",
    "Ein Ausbildungszentrum, dessen Absolventen sieben Jahre gebunden sind",
    "Ein Rohstofflager mit einer Sicherung, die teurer war als der Inhalt",
    "Ein Bürokomplex, in dem zwei Abteilungen einander bespitzeln",
    "Eine Teststrecke außerhalb der Stadt, hinter drei Zäunen",
    "Ein Serverraum, dessen Zugang nur vier Personen haben und einer davon ist tot",
    "Ein Vorstandsgebäude mit einem Hubschrauberdach und keinem Erdgeschoss",
    "Eine Konzernsiedlung, in der Wohnen, Einkaufen und Schule von einer Firma kommen",
    "Ein Werk, das nach einem Streik durch Roboter ersetzt wurde",
    "Eine Zulieferhalle, die drei Konzerne gleichzeitig beliefert und keinem gehört",
    "Ein Archivgebäude, dessen Bestände nie digitalisiert wurden, mit Absicht",
    "Eine Recyclinganlage, in der Prototypen vernichtet werden sollen",
    "Ein Hochsicherheitslabor unter einem gewöhnlichen Bürogebäude",
    "Eine Konzernbotschaft in einem Staat, der den Konzern nicht kontrolliert",
    "Ein Firmenhotel, in dem Verhandlungen stattfinden, die es offiziell nicht gibt",
  // Slums & Ränder
    "Eine Wellblechstadt auf dem Dach eines Parkhauses",
    "Ein Viertel ohne Postadressen, in dem Pakete trotzdem ankommen",
    "Eine Siedlung in einer stillgelegten U-Bahn-Station",
    "Ein Elendsquartier auf aufgeschüttetem Müll, dreißig Jahre alt",
    "Ein Block, in dem eine Klinik ohne Zulassung die einzige medizinische Versorgung ist",
    "Ein Markt, auf dem gebrauchte Implantate gehandelt werden",
    "Ein Viertel, dessen Strom von einer selbstgebauten Leitung kommt",
    "Eine Zeltstadt vor dem Werkstor, seit dem letzten Massenabbau",
    "Ein Containerdorf im Hafen, das als Übergangslösung errichtet wurde",
    "Ein Wohnschiff, das nicht auslaufen darf und nicht abgewrackt wird",
    "Eine Brachfläche, auf der eine Gemeinschaft Gemüse anbaut und es verteidigt",
    "Ein Häuserblock, den die Bewohner selbst instand halten, weil niemand kommt",
    "Ein Tunnelabschnitt, in dem eine Schule ohne Genehmigung betrieben wird",
    "Eine Kanalisation, in der eine Gruppe seit Jahren lebt und Regeln hat",
    "Ein Viertel, in dem Wasser teurer ist als Bandbreite",
    "Ein Areal, das nach einem Brand abgesperrt wurde und wieder bewohnt ist",
    "Ein Bordellkomplex mit angeschlossener Klinik, beide vom selben Betreiber",
    "Ein Fabrikgelände, das eine Familie besetzt hält und als Werkstatt betreibt",
    "Ein Hochhaus mit einem Wachdienst, den die Bewohner selbst bezahlen",
    "Eine Straße, in der jede Kamera zerschlagen wird, sobald sie hängt",
  // Netz & Untergrund
    "Ein Datenhafen in einem Land ohne Auslieferungsabkommen",
    "Ein Kellerlabor, in dem Implantate ohne Papiere eingesetzt werden",
    "Ein Netzknoten, den eine Gruppe kontrolliert und wie eine Mautstelle betreibt",
    "Ein Serverkeller unter einer Wäscherei",
    "Ein Schwarzmarkt für Identitäten, aufgebaut wie ein Reisebüro",
    "Eine Werkstatt, in der Fahrzeuge ihre Kennung verlieren",
    "Ein Piratensender, dessen Standort wöchentlich wechselt",
    "Ein Umschlagplatz für Daten, physisch, auf Trägern, per Kurier",
    "Ein Hackerkollektiv in einer ehemaligen Bibliothek",
    "Ein Simulationslokal, in dem man Erinnerungen kaufen kann",
    "Eine Klinik, die Implantate entfernt und keine Fragen stellt",
    "Eine Fälscherwerkstatt für Arbeitsnachweise",
    "Ein Bunker aus einem alten Krieg, jetzt mit eigener Stromversorgung",
    "Ein Depot für Hardware, die auf keiner Zollliste steht",
    "Ein Netzwerkraum, der nur analog erreichbar ist",
    "Eine Untergrundbörse, an der Sicherheitslücken gehandelt werden",
    "Ein Treffpunkt für Aussteiger aus Konzernverträgen",
    "Ein Lager mit Waffen aus einer aufgelösten Sicherheitsfirma",
    "Ein Datenfriedhof, auf dem Träger verschrottet werden sollen und nicht werden",
    "Ein Raum ohne jede Elektronik, in dem deshalb verhandelt wird",
];

export const CYBERPUNK_PLACES: string[] = [
  ...CYBERPUNK_AREAS,
  ...CYBERPUNK_SPOTS,
];

/** Historisch: Stadt, Land, Hof & Kloster, Handel & Meer, Krieg & Grenze. */
export const HISTORISCH_AREAS: string[] = [
  // Stadt
    "Eine Reichsstadt, deren Rat aus zwölf Familien besteht",
    "Ein Handwerkerviertel, in dem die Zunft strenger ist als die Obrigkeit",
    "Eine Universitätsstadt mit zweitausend Studenten und ohne Polizei",
    "Ein Judenviertel, dessen Tore bei Einbruch der Dunkelheit geschlossen werden",
    "Eine Hafenstadt, in der die Pest ausgebrochen ist und niemand es zugibt",
    "Ein Marktplatz mit Pranger, Waage und Brunnen",
    "Eine Stadt, die zwei Herren Abgaben zahlt und beide für illegitim hält",
    "Ein Gerberviertel am Unterlauf des Flusses, wo sonst niemand wohnen will",
    "Eine Festungsstadt, in der mehr Soldaten als Bürger leben",
    "Ein Viertel der Tuchhändler, in dem die Häuser fünf Stockwerke haben",
    "Eine Stadt nach dem Brand, halb wieder aufgebaut, halb Asche",
    "Ein Rathaus, in dem die Ratsprotokolle seit zwei Jahren fehlen",
    "Eine Bischofsstadt, in der weltliche und geistliche Gerichte konkurrieren",
    "Ein Armenviertel vor der Mauer, das im Krieg zuerst abgerissen wird",
    "Eine Residenzstadt, die für den Hof gebaut wurde und ohne ihn leer wäre",
    "Ein Badhaus-Viertel mit einem schlechten Ruf und guten Geschäften",
    "Eine Stadt, deren Zunftordnung Frauen ausschließt und deren Werkstätten Frauen führen",
    "Ein Quartier der Fuhrleute vor dem Stadttor",
    "Eine Messestadt, die zweimal im Jahr ihre Einwohnerzahl verdoppelt",
    "Eine Stadt unter Belagerung, in der dritte Woche",
  // Land
    "Ein Dorf, das im Dreifelderbau wirtschaftet und dessen Allmende strittig ist",
    "Ein Gutshof mit vierzig Tagelöhnern und einem abwesenden Herrn",
    "Ein Weiler in den Bergen, dessen Bewohner im Winter wandern",
    "Ein Fischerdorf, dessen Fang dem Kloster gehört",
    "Ein Bauerndorf nach drei Missernten",
    "Eine Siedlung von Neusiedlern in gerodetem Wald",
    "Ein Dorf, das gerade seinen letzten Zehnten verweigert hat",
    "Ein Weinort an einem Südhang, im Jahr einer Rekordernte",
    "Ein Marschendorf hinter einem Deich, der im Herbst brach",
    "Ein Almgebiet, in dem den Sommer über niemand die Obrigkeit sieht",
    "Ein Dorf mit einer Mühle, an der alle mahlen müssen",
    "Eine Hufe am Waldrand, seit zwei Generationen in derselben Familie",
    "Ein Dorf, in dem Vieh gestorben ist und der Verdacht umgeht",
    "Ein Weiler an einer Pilgerstraße, der vom Durchgangsverkehr lebt",
    "Ein Bergbauort, in dem der Silberertrag nachlässt",
    "Ein Dorf, dessen Bewohner alle einem Kloster gehören",
    "Eine Köhlersiedlung im Wald, drei Tagesmärsche von der nächsten Straße",
    "Ein Gestüt, das dem Landesherrn gehört und den Hafer der Umgebung frisst",
    "Ein Dorf im Grenzgebiet, das jedes Jahrzehnt die Herrschaft wechselt",
    "Ein Ort mit einer Furt, an der Zoll erhoben wird, seit niemand weiß wann",
];

export const HISTORISCH_SPOTS: string[] = [
  // Hof & Kloster
    "Ein Fürstenhof, an dem drei Parteien um die Nachfolge ringen",
    "Eine Residenz, in der der Herrscher seit Monaten nicht öffentlich auftrat",
    "Ein Kloster mit einer Bibliothek und einem Abt, der nicht hineinlässt",
    "Ein Nonnenkloster, in dem Töchter des Adels versorgt werden",
    "Ein Bischofspalast, dessen Bauherr sich verschuldet hat",
    "Ein Hoflager, das alle drei Monate weiterzieht",
    "Eine Burg, auf der eine Witwe die Herrschaft führt und dafür angefeindet wird",
    "Ein Kanzleigebäude, in dem alle Urkunden des Landes lagern",
    "Ein Kloster, das Kranke aufnimmt und dabei selbst verarmt",
    "Eine Kommende eines Ritterordens, weit von jedem Kriegsschauplatz",
    "Ein Hofgericht, das seit Jahren dieselbe Erbsache verhandelt",
    "Ein Palast mit einem Garten, für den drei Dörfer weichen mussten",
    "Ein Skriptorium, in dem an einer Chronik geschrieben wird, die schmeichelt",
    "Eine Domschule, an der Söhne aus dem ganzen Land ausgebildet werden",
    "Ein Jagdschloss, das nur sechs Wochen im Jahr benutzt wird",
    "Ein Konvent, der sich von der Ordensleitung losgesagt hat",
    "Ein Hofstaat, in dem der Kanzler mehr regiert als der Fürst",
    "Eine Abtei mit eigenem Gericht, eigener Münze und eigenem Heer",
    "Ein Sommersitz, an dem der Hof den Seuchenmonaten ausweicht",
    "Ein Kloster, dessen Reliquie Pilger anzieht und dessen Echtheit angezweifelt wird",
  // Handel & Meer
    "Ein Kontor einer auswärtigen Handelsgesellschaft, mit eigenen Privilegien",
    "Ein Hafen, in dem die Schiffe auf günstigen Wind warten, seit drei Wochen",
    "Eine Werft, an der ein Schiff für eine Reise gebaut wird, von der man nicht spricht",
    "Ein Zollhaus an einer Flussenge, das ein Drittel jeder Ladung nimmt",
    "Ein Warenlager, in dem Gewürze und Waffen nebeneinanderliegen",
    "Eine Handelsstraße durch das Gebirge, im letzten Monat vor dem Schnee",
    "Ein Umschlagplatz, an dem drei Währungen im Umlauf sind",
    "Ein Kaufmannshaus, dessen Bücher zwei Fassungen haben",
    "Eine Karawanenstation, an der Wasser teurer ist als Seide",
    "Ein Fährhaus an einem Strom, das das Monopol hat",
    "Ein Fernhandelsschiff im Hafen, mit halber Mannschaft und voller Ladung",
    "Eine Bank, die einem Fürsten Geld geliehen hat und es nicht wiedersieht",
    "Ein Sklavenmarkt in einer Hafenstadt, in der es dafür Gesetze gibt",
    "Eine Insel als Zwischenstation, deren Gouverneur seit Jahren keine Post bekam",
    "Ein Salzhandelsort, an dem die Straßen nach den Fuhrleuten benannt sind",
    "Eine Faktorei an einer fremden Küste, dreihundert Menschen weit von zu Hause",
    "Ein Leuchtturmhafen, in den man nur bei Tag einlaufen kann",
    "Ein Hansekontor, dessen Privilegien gerade aufgekündigt wurden",
    "Ein Warenhof, in dem die Fremden wohnen müssen und nicht mit Einheimischen handeln dürfen",
    "Ein Hafen, aus dem eine Flotte ausgelaufen und nicht zurückgekehrt ist",
  // Krieg & Grenze
    "Ein Feldlager im Winterquartier, mit mehr Kranken als Kämpfern",
    "Eine Grenzfeste, deren Besatzung seit acht Monaten keinen Sold sah",
    "Ein Schlachtfeld, drei Tage danach",
    "Ein Landstrich, durch den zweimal ein Heer gezogen ist",
    "Eine belagerte Stadt, in der über Übergabe verhandelt wird",
    "Ein Söldnerlager, dessen Hauptmann auf Bezahlung wartet",
    "Ein Lazarett in einer beschlagnahmten Kirche",
    "Eine Marktstadt, die als Etappenort dient und ausgeplündert wird",
    "Ein Pass, den zweihundert Mann gegen zehntausend halten sollen",
    "Ein Gebiet unter Waffenstillstand, in dem beide Seiten Vorräte sammeln",
    "Ein Dorf zwischen den Linien, das beiden Seiten liefert",
    "Eine Wachburg an einer Grenze, an der seit Jahrzehnten nichts geschah",
    "Ein Feldherrnquartier in einem requirierten Gutshaus",
    "Eine Straße voller Flüchtender, in beide Richtungen",
    "Ein Waffenplatz, an dem ein Heer aufgestellt wird",
    "Eine Festung, die man für uneinnehmbar hält und deren Brunnen versiegt",
    "Ein Grenzfluss, über den man nachts übersetzt",
    "Ein besetzter Landstrich mit einer Verwaltung, die niemand anerkennt",
    "Ein Gefangenenlager, in dem Adlige auf Lösegeld warten",
    "Ein Ort, an dem ein Friedensvertrag ausgehandelt wird und alle bewaffnet sind",
];

export const HISTORISCH_PLACES: string[] = [
  ...HISTORISCH_AREAS,
  ...HISTORISCH_SPOTS,
];

/** Western: Town, Ranch & Weide, Trail, Grenze, Bergbau & Eisenbahn. */
export const WESTERN_AREAS: string[] = [
  // Town
    "Eine Stadt mit einer Hauptstraße, zwei Saloons und keinem Arzt",
    "Ein Ort, dessen Sheriff vor sechs Wochen weggeritten ist",
    "Eine Kleinstadt, in der ein Rancher den Laden, die Bank und den Richter bezahlt",
    "Eine Endstation der Bahnlinie, seit einem Jahr, bis sie weitergebaut wird",
    "Ein Ort, in dem an einem Tag mehr Waffen als Menschen ankommen",
    "Eine Stadt mit einer Kirche ohne Prediger und einem Saloon mit drei",
    "Ein Grenzort, in dem zwei Sprachen gesprochen und drei Rechtsauffassungen gelebt werden",
    "Eine Stadt am Fluss, deren Fähre der einzige Übergang auf hundert Meilen ist",
    "Ein Ort, in dem seit dem Streik die Hälfte der Läden zu ist",
    "Eine Stadt, die nach einem Brand komplett neu gebaut wurde, in vier Monaten",
    "Ein Nest mit einem Telegrafenamt, das die einzige Verbindung nach draußen ist",
    "Eine Stadt, die um eine Quelle herum entstand und deren Wasserrechte strittig sind",
    "Ein Ort mit einem Friedhof, der schneller wächst als die Einwohnerzahl",
    "Eine Stadt, in der zwei Familien seit zwölf Jahren nicht miteinander sprechen",
    "Ein Handelsposten, der zugleich Post, Gericht und Schenke ist",
    "Eine Stadt mit einem neuen Hotel und keiner Nachfrage danach",
    "Ein Ort, der eine Bürgerwehr aufgestellt hat und sie nicht mehr los wird",
    "Eine Stadt, deren Bank zum dritten Mal ausgeraubt wurde",
    "Ein Ort mit einer Schule, in die vier Kinder gehen und ein Lehrer fährt",
    "Eine Stadt, in der die Viehtriebsaison begonnen hat und alles ausgebucht ist",
  // Grenze & Land
    "Ein Reservat, dessen Rationslieferung seit zwei Monaten ausbleibt",
    "Ein Grenzstreifen zu Mexiko, auf dem niemandes Gesetz durchsetzbar ist",
    "Ein Armeeposten mit vierzig Soldaten und einem Offizier ohne Erfahrung",
    "Ein Indianerdorf, dessen Land gerade neu vermessen wurde",
    "Ein Vertragsgebiet, das man in diesem Jahr zum dritten Mal verkleinert hat",
    "Ein Fort an einem Fluss, das Handel treibt und Krieg vorbereitet",
    "Ein Landstrich, für den zwei Regierungen Urkunden ausgestellt haben",
    "Ein Missionsposten zwischen zwei Welten und beiden verdächtig",
    "Ein Weidegebiet, das Siedler beanspruchen und Nomaden befahren",
    "Ein Grenzfluss, über den in beide Richtungen geschmuggelt wird",
    "Ein Agenturposten, dessen Verwalter die Lieferungen selbst verkauft",
    "Ein Jagdgebiet, in dem die Bisons ausgeblieben sind",
    "Ein Übergang, an dem Zoll erhoben wird, ohne rechtliche Grundlage",
    "Ein Landvermesserlager, das seit Wochen bewacht werden muss",
    "Ein Gebiet, dem gerade der Status als Territorium zugesprochen wurde",
    "Ein Fort, das aufgegeben wurde und in dem jemand wohnt",
    "Ein Handelsplatz, an dem Waffen gegen Pelze getauscht werden",
    "Ein Dorf, das zwischen zwei Kriegsparteien neutral bleiben will",
    "Ein Landstück, das eine Eisenbahngesellschaft geschenkt bekam",
    "Ein Grenzort, in dem Gesuchte aus zwei Ländern gleichzeitig sicher sind",
];

export const WESTERN_SPOTS: string[] = [
  // Ranch & Weide
    "Eine Ranch, die dreimal so viel Land beansprucht wie sie besitzt",
    "Ein Weidegebiet, das seit dem Stacheldraht umkämpft ist",
    "Eine Rinderfarm, deren Besitzer starb und deren Erben streiten",
    "Ein Gehöft am Ende eines Tals, mit einer Familie und vier Hunden",
    "Eine Ranch, auf der die Hälfte der Männer im Frühjahr nicht wiederkam",
    "Ein Wasserloch, um das drei Rancher prozessieren",
    "Eine Schafweide neben einer Rinderweide, mit dem üblichen Ergebnis",
    "Ein Pferdegestüt, das die Armee beliefert und dafür geschnitten wird",
    "Eine Farm, die nach zwei Dürrejahren verkauft werden soll",
    "Eine Ranch mit einem Bunkhouse voller Männer, die niemand kennt",
    "Ein Homestead, dessen Anspruch angefochten wird",
    "Ein Gehöft, das nach dem Überfall halb abgebrannt und wieder bewohnt ist",
    "Eine Weide, auf der Vieh mit fremdem Brandzeichen steht",
    "Ein Ranchhaus, in dem eine Witwe dreißig Männer beschäftigt",
    "Ein Tal, in dem sich drei Familien das Wasser einer Quelle teilen sollen",
    "Ein Winterlager der Cowhands, weit oben, mit Vorräten für zwei Monate",
    "Eine Farm mit einem neuen Brunnen, den alle Nachbarn benutzen wollen",
    "Ein Corral, in dem gerade Wildpferde eingeritten werden",
    "Ein Gehöft an der Grenze zum Reservatsland",
    "Eine Ranch, deren Grenzzaun jede Woche an derselben Stelle durchtrennt wird",
  // Trail
    "Ein Viehtriebweg, auf dem zweitausend Rinder nach Norden ziehen",
    "Eine Flussfurt, an der sich die Herden stauen",
    "Ein Wagenzug, dessen Führer die Route zum ersten Mal fährt",
    "Ein Pass, den man vor dem ersten Schnee überqueren muss",
    "Eine Postkutschenstation mit frischen Pferden und altem Streit",
    "Ein Wasserstelle, die als Einzige auf zwei Tagesritte eingezeichnet ist",
    "Ein Lagerplatz am Trail, an dem regelmäßig Vieh verschwindet",
    "Eine Salzebene, die man nur nachts durchquert",
    "Ein Canyon, durch den der Weg führt und in dem er sich verengt",
    "Ein Handelsposten mitten auf der Strecke, ohne Nachbarn",
    "Ein ausgetrocknetes Flussbett, dem man vierzig Meilen folgt",
    "Eine Brücke, die eingestürzt ist, mit einem Umweg von drei Tagen",
    "Ein Trail, auf dem sich zwei Herden begegnen und keine ausweichen will",
    "Ein Rastplatz mit Gräbern, die alle dasselbe Jahr tragen",
    "Ein Bergpfad, auf dem ein Wagen nicht wenden kann",
    "Ein Fährbetrieb, dessen Besitzer den Preis nach Ungeduld staffelt",
    "Ein Lagerfeuer am Trail, an dem drei Gruppen zusammentreffen",
    "Eine Wegkreuzung mit einem Schild, das jemand gedreht hat",
    "Ein Sturmgebiet, in dem die Herde in der Nacht durchgegangen ist",
    "Eine Quelle, die vergiftet wurde, und niemand weiß von wem",
  // Bergbau & Eisenbahn
    "Eine Goldgräberstadt, ein Jahr nach dem Fund und sechs Monate nach dem Höhepunkt",
    "Ein Camp am Fluss, in dem dreihundert Männer und vier Frauen leben",
    "Eine Silbermine, deren Ader schmaler wird und deren Besitzer schweigt",
    "Eine Gesellschaftsmine, die den Claim eines Einzelnen aufgekauft hat",
    "Ein Bergwerksort, dessen Wasser vom Abraum grau ist",
    "Ein aufgegebenes Camp, in dem noch drei Leute waschen",
    "Eine Streckenbaustelle der Eisenbahn, mit tausend Arbeitern und zwei Ärzten",
    "Ein Eisenbahnlager, das alle zwei Wochen weiterzieht",
    "Ein Tunnelbau durch den Berg, im vierzehnten Monat",
    "Eine Bahnstation im Nichts, mit einem Wassertank und einem Wärter",
    "Eine Boomtown, in der Claims mehr wert sind als Gold",
    "Ein Mineneingang, der nach einem Einsturz nicht wieder geöffnet wurde",
    "Ein Camp, in dem die Versorgung ausgeblieben ist und der Winter kommt",
    "Eine Erzmühle, die den ganzen Tag lärmt und den ganzen Ort ernährt",
    "Ein Ort, an dem die Bahnlinie vorbeigeführt wurde, zwei Meilen entfernt",
    "Ein Bergbaudistrikt mit einer eigenen, selbstgegebenen Rechtsordnung",
    "Ein Camp chinesischer Arbeiter, das am Ortsrand liegen muss",
    "Ein Depot mit Sprengstoff für den Streckenbau, unbewacht",
    "Eine Mine, in der es seit dem Unglück im Frühjahr spukt, sagen die Leute",
    "Ein Ort, in dem eine Eisenbahngesellschaft das Land unter den Häusern gekauft hat",
];

export const WESTERN_PLACES: string[] = [
  ...WESTERN_AREAS,
  ...WESTERN_SPOTS,
];

/** Science Fiction: Stationen, Kolonien, Städte, Schiffe, Anlagen, Grenzräume. */
export const SCIFI_AREAS: string[] = [
  // Stationen & Habitate
    "Eine Orbitalstation, deren äußerer Ring seit einem Leck abgeriegelt ist",
    "Ein Habitatzylinder, in dem die künstliche Sonne eine Stunde zu spät angeht",
    "Eine Raumstation, an der dreimal so viele Schiffe hängen wie Liegeplätze",
    "Ein Wohnring, dessen Rotation nachjustiert werden müsste und nicht wird",
    "Eine Umlaufstation, die offiziell nur der Forschung dient",
    "Ein Habitat, in dem der Luftfilter lauter geworden ist und niemand nachsieht",
    "Eine Station am Lagrangepunkt, die keiner Gerichtsbarkeit unterliegt",
    "Ein Generationenschiff im vierten Jahrhundert seiner Reise, dessen Ziel zur Erzählung geworden ist",
    "Ein Frachtdepot im Orbit, in dem Container stehen, die niemand deklariert hat",
    "Eine Werftstation, die Schiffe baut, für die es keine Käufer mehr gibt",
    "Ein Kuppelhabitat, dessen Außenhaut geflickt aussieht wie ein Netz",
    "Eine Station, deren Bevölkerung zur Hälfte aus Durchreisenden besteht",
    "Ein Ringhabitat mit zwei Schwerkraftzonen und zwei Gesellschaften",
    "Eine alte Militärstation, die zu Wohnraum umgewidmet wurde",
    "Ein Vorposten an einem Sprungtor, der von Zöllen lebt",
    "Eine Station, deren Uhren nach einem Planeten gehen, den keiner gesehen hat",
    "Ein Habitat, in dem Wasser rationiert ist und Luft nicht, aus historischen Gründen",
    "Eine Umlaufkolonie, die ihren Müll seit Jahren nur umlagert",
  // Planeten & Kolonien
    "Eine Kolonie auf einem Planeten, dessen Tag achtzig Stunden dauert",
    "Eine Wüstenwelt, deren einziger Reichtum unter der Kruste liegt",
    "Ein Terraforming-Projekt im zweiten Jahrzehnt, halb Wald, halb Staub",
    "Eine Eiswelt mit einer einzigen Bohrstadt und keinem zweiten Weg hinaus",
    "Ein Mond, auf dem die Kuppeln älter sind als die Verträge",
    "Eine Kolonie, deren Nachschubschiff seit vierzehn Monaten ausbleibt",
    "Ein Planet mit atembarer Luft und einer Flora, die nichts davon teilt",
    "Eine Ozeanwelt, auf der die Städte schwimmen und die Reichen tiefer wohnen",
    "Ein Bergbaumond, dessen Belegschaft in Schichten von acht Monaten lebt",
    "Eine Kolonie, die ihre Unabhängigkeit erklärt hat und auf Antwort wartet",
    "Ein Planet, dessen Atmosphäre nachmittags giftig wird",
    "Eine Siedlung am Rand einer Zone, in der Geräte nicht funktionieren",
    "Eine Agrarwelt, die drei Systeme ernährt und selbst importiert",
    "Ein Vulkanplanet mit Kraftwerken statt Städten",
    "Eine Kolonie, in der die zweite Generation die erste nicht mehr versteht",
    "Ein aufgegebener Terraforming-Standort, in dem Leute leben, die nirgends gemeldet sind",
    "Eine Welt mit zwei Sonnen und einer Bevölkerung, die nachts arbeitet",
    "Ein Planet unter Quarantäne, deren Grund nur im Archiv steht",
    "Eine Grenzkolonie, deren Verteidigung aus einem Vertrag besteht",
    "Ein Mond, dessen Ringschatten alle sechs Tage einen Winter bringt",
  // Städte
    "Eine Megastadt unter einer Kuppel, die zu klein geworden ist",
    "Eine Hauptstadt, deren Unterstadt auf keiner offiziellen Karte steht",
    "Eine Hafenstadt an einem Orbitallift, der nur eine Richtung billig macht",
    "Eine Stadt, in der jeder Bewohner ein Sauerstoffkontingent hat",
    "Eine Siedlung aus ausgeschlachteten Landefähren",
    "Eine Stadt, die um einen Reaktor herum gewachsen ist und von seiner Wärme lebt",
    "Ein Verwaltungsdistrikt, in dem mehr Archive stehen als Wohnungen",
    "Eine Stadt mit einer Mauer gegen den Staub und einer gegen die Menschen",
    "Ein Raumhafenviertel, in dem drei Zeitzonen gleichzeitig gelten",
    "Eine Kuppelstadt, deren Reparaturbudget seit Jahren umgewidmet wird",
    "Eine Stadt, in der Wasser gehandelt wird wie anderswo Anteile",
    "Ein Elendsviertel an der Außenwand, wo die Kälte durch die Nähte kommt",
    "Eine Planhauptstadt, in der jede Straße nach einem Ingenieur heißt",
    "Eine Stadt, deren Bevölkerung zu einem Drittel aus Vertragsarbeitern besteht",
    "Ein Viertel, das nach einem Unglück evakuiert wurde und wieder bewohnt ist",
    "Eine Stadt unter dem Eis, deren oberste Ebene aufgegeben wurde",
  // Grenzräume
    "Ein Asteroidengürtel mit mehr Claims als Gestein",
    "Eine entmilitarisierte Zone zwischen zwei Systemen, in der beide patrouillieren",
    "Ein Trümmerfeld, das früher ein Habitat war",
    "Ein Sprungpunkt, an dem Schiffe verschwinden und die Statistik schweigt",
    "Ein Grenzposten, dessen Vorschriften älter sind als der Vertrag",
    "Ein Freihafen, in dem kein Gesetz gilt außer dem der Liegegebühr",
    "Ein System ohne Regierung, aber mit drei Steuereintreibern",
    "Eine Region, in der ein Funkspruch zwei Tage braucht",
    "Ein Wrackfriedhof, den offiziell niemand betreibt",
    "Eine Zone, aus der Sonden zurückkommen und Menschen nicht",
    "Ein Randsystem, das auf zwei Karten verschieden eingezeichnet ist",
    "Ein alter Kolonieweg, auf dem alle hundert Lichtjahre eine Boje steht",
    "Ein Tor, das in beide Richtungen führt, von dem aber nur eine kontrolliert wird",
    "Ein Nebel, in dem keine Ortung funktioniert und darum viel gehandelt wird",
];

export const SCIFI_SPOTS: string[] = [
  // Schiffe & Unterwegs
    "Ein Frachter mit sieben Mann Besatzung und Platz für siebzig",
    "Ein Passagierschiff, auf dem die unteren Decks kein Fenster haben",
    "Ein Schlepper, der Wracks birgt und keine Fragen stellt",
    "Ein Forschungsschiff, dessen Auftraggeber im Vertrag nicht steht",
    "Ein Konvoi, der seit sechs Wochen nicht angehalten hat",
    "Ein Kolonistenschiff im Anflug, dessen Ziel sich in der Zwischenzeit verändert hat",
    "Ein Sprungtor mit Wartezeiten von vierzig Tagen",
    "Eine Rettungsfähre mit Vorräten für zwölf und siebzehn Leuten darin",
    "Ein Kriegsschiff im Friedensdienst, das seine Waffen behalten durfte",
    "Ein Wrack im Driftfeld, in dem noch Licht brennt",
    "Ein Handelsschiff, das zwei Papiere führt, je nach Hafen",
    "Ein Tanker voll Wasser, der als Erzfrachter gemeldet ist",
    "Eine Fähre zwischen zwei Monden, die niemand mehr wartet",
    "Ein Langstreckenschiff, auf dem ein Drittel der Besatzung im Kälteschlaf bleibt",
    "Ein Schmugglerpfad durch ein Trümmerfeld, den nur drei Piloten kennen",
    "Ein Rettungsboot mit Kurs auf einen Ort ohne Namen",
  // Anlagen & Arbeit
    "Eine Forschungsanlage, deren untere Ebenen nur mit Freigabe erreichbar sind",
    "Ein Rechenzentrum, das mehr Kühlung braucht als die Stadt daneben",
    "Eine Fabrik, in der Maschinen Maschinen bauen und drei Menschen zusehen",
    "Ein Kraftwerk, dessen Abschaltung seit Jahren angekündigt ist",
    "Eine Klinik, die Prothesen anpasst und die Verträge gleich mit",
    "Ein Archiv voller Daten, für die es keine Lesegeräte mehr gibt",
    "Ein Ausbildungslager für Kolonisten, dessen Absolventen selten schreiben",
    "Ein Labor auf einem Mond, dessen Personal alle acht Monate wechselt",
    "Eine Recyclinganlage, durch die alles geht, was die Station verlässt",
    "Eine Sendestation am Rand des Systems, besetzt mit zwei Leuten",
    "Ein Testgelände, größer als das Land, dem es gehört",
    "Eine Aufbereitungsanlage, die Wasser liefert und Abhängigkeit",
    "Ein Depot, dessen Inventarliste zweimal geführt wird",
    "Eine Quarantänestation, in der niemand länger arbeitet als nötig",
    "Ein Observatorium, das seit acht Jahren dasselbe Signal aufzeichnet",
    "Eine Serverfarm im Eis, betrieben von einem Konzern ohne Anschrift",
];

export const SCIFI_PLACES: string[] = [
  ...SCIFI_AREAS,
  ...SCIFI_SPOTS,
];

/** Märchen: Dörfer, Wald, Burgen, Wege, Werkstätten, Anderswelt. */
export const MAERCHEN_AREAS: string[] = [
  // Siedlungen & Häuser
    "Ein Dorf, in dem jedes Haus einen Riegel an der Innenseite der Tür hat",
    "Eine Hütte am Waldrand, in der die Kerze brennt, ehe jemand sie anzündet",
    "Ein Müllerhaus am Bach, dessen Rad sich auch ohne Wasser dreht",
    "Ein Wirtshaus an der Kreuzung, in dem für einen Gast immer gedeckt ist",
    "Ein Bauernhof mit sieben Söhnen und Land für einen",
    "Ein Häuschen aus Zuckerwerk, das nach Rauch riecht",
    "Ein Dorf, das seine Glocke vergraben hat, damit man es nicht findet",
    "Ein Haus am Ende der Gasse, auf dem kein Schnee liegen bleibt",
    "Eine Schmiede, in der das Feuer seit drei Menschenaltern nicht ausging",
    "Ein Weiler, dessen Brunnen man abends nicht mehr betritt",
    "Ein Backhaus, in dem einmal im Jahr ein Laib zu viel entsteht",
    "Ein Gehöft, auf dem die Tiere sprechen, wenn niemand zusieht",
    "Ein Dorf, in dem alle denselben Traum hatten und keiner davon anfängt",
    "Eine Kate, vor der ein Paar Schuhe steht, das zu keinem Fuß im Ort passt",
    "Ein Ort, dessen Kirchturm keine Uhr hat und nie eine hatte",
    "Ein Marktflecken, auf dem sonntags mehr Leute sind, als dort wohnen",
    "Ein Haus mit sieben Türen, von denen sechs in denselben Raum führen",
    "Ein Dorf, in dem man Fremden Brot gibt und keine Auskunft",
  // Wald & Wildnis
    "Ein Wald, in dem der Weg zurück nie so lang ist wie der Weg hinein",
    "Eine Lichtung, auf der das Gras in einem Kreis niedriger steht",
    "Ein Wald, dessen Bäume Namen tragen, die niemand mehr ausspricht",
    "Ein Dickicht, aus dem man nur singend wieder herausfindet",
    "Ein Moor, das jedes Jahr ein Stück mehr vom Weideland nimmt",
    "Ein Tannenwald, in dem es keine Vögel gibt und trotzdem nicht still ist",
    "Eine Waldschneise, die geradewegs auf nichts zuläuft",
    "Ein Erlenbruch, in dem drei Wege beginnen und zwei nirgends enden",
    "Ein alter Baum am Kreuzweg, an den man nichts binden soll",
    "Ein Wald, den man nur betreten darf, wenn man um Erlaubnis fragt",
    "Eine Höhle im Berg, aus der es im Winter warm herausweht",
    "Ein Bergpass, auf dem ein Fuhrwerk steht, seit niemand weiß, wann",
    "Ein Tal, in das die Sonne nur im Hochsommer fällt",
    "Ein Fluss, der an einer Stelle rückwärts fließt",
    "Ein See, auf dem sich nichts spiegelt",
    "Ein Felsen, der aussieht wie eine kniende Frau und einmal keiner war",
    "Ein Wald am Ende der Felder, hinter dem die Karte aufhört",
    "Ein Sumpf mit Lichtern, denen man nicht nachgehen soll",
  // Anderswelt
    "Ein Hügel, der sich in bestimmten Nächten öffnet",
    "Ein Garten hinter einer Mauer, in dem alles reif ist, gleich zu welcher Zeit",
    "Ein Reich unter dem See, von dem die Fischer nicht sprechen",
    "Ein Land, in dem ein Tag draußen ein Jahr drinnen ist",
    "Ein Spiegelsaal mit einer Tür, die es außen nicht gibt",
    "Eine Insel, die man nur findet, wenn man sie nicht sucht",
    "Ein Wald hinter dem Wald, in den drei Schritte zu weit führen",
    "Ein Berg aus Glas, an dem alle Aufstiege gezählt werden",
    "Ein Hof, auf dem die Zeit stehen geblieben ist und das Essen warm",
    "Ein Gebiet, in dem ausgesprochene Wünsche zählen wie Verträge",
    "Eine Stadt am Meeresgrund, deren Glocken man bei Sturm hört",
    "Ein Tal, in dem alle Menschen einander gleichen",
    "Ein Land ohne Winter, das dafür etwas anderes nimmt",
    "Ein Wald, in dem die Tiere Recht sprechen",
    "Ein Haus zwischen zwei Häusern, das nur manchen auffällt",
    "Ein Ort, an dem verlorene Dinge liegen und bewacht werden",
];

export const MAERCHEN_SPOTS: string[] = [
  // Burgen & Herrschaft
    "Ein Schloss mit hundert Fenstern und einem, das immer offen steht",
    "Eine Burg, in der seit dem Winter niemand mehr Musik gehört hat",
    "Ein Königshof, an dem das Lachen verboten wurde und niemand weiß, seit wann",
    "Ein Turm ohne Tür, aber mit einem Fenster in guter Höhe",
    "Ein Schloss, das schläft, und ein Dorf davor, das wach bleiben muss",
    "Eine Residenz, an der drei Töchter und ein Erbe zu verteilen sind",
    "Ein Palast mit einem Saal, den zu betreten niemandem gesagt wurde",
    "Eine Burgruine, in der abends Licht brennt und morgens Asche liegt",
    "Ein Königreich mit zwei Kronen und einem König",
    "Ein Hof, an dem der Narr der Einzige ist, der die Wahrheit sagen darf",
    "Ein Schloss, dessen Garten im Winter blüht",
    "Eine Festung, in der ein Zimmer immer leer gehalten wird",
    "Ein Fürstensitz, dessen Herr ein Versprechen schuldet und die Frist läuft ab",
    "Ein Schloss am Meer, dessen Treppen unter Wasser weitergehen",
    "Ein Landsitz, von dem jedes Jahr ein Diener zu wenig zurückkehrt",
    "Ein Königshaus, in dem seit drei Geschlechtern kein Erstgeborener alt wurde",
  // Wege & Übergänge
    "Eine Brücke, für deren Überquerung ein Preis genannt wird",
    "Ein Kreuzweg mit vier Wegen und drei Wegweisern",
    "Eine Straße, die drei Tage dauert und niemanden begegnen lässt",
    "Ein Hohlweg, in dem das Echo eine Silbe zu spät kommt",
    "Ein Grenzstein, hinter dem andere Regeln gelten und keiner sie kennt",
    "Ein Fährmann an einem Fluss, der immer schon dort war",
    "Ein Tor in einer Mauer, die es sonst nirgends gibt",
    "Ein Pfad, den nur Barfüßige finden",
    "Eine Landstraße, an der alle sieben Meilen ein Wirtshaus steht",
    "Ein Steg über einen Bach, unter dem etwas wohnt, das Zoll nimmt",
    "Ein Berg, den man dreimal umrunden muss, ehe sich der Eingang zeigt",
    "Eine Treppe im Fels, die mehr Stufen hat, als der Aufstieg braucht",
    "Ein Weg, auf dem man niemals umkehren darf",
    "Ein Tunnel unter dem Hügel, der kürzer ist, als er sein dürfte",
    "Ein Hafen, in dem ein Schiff auf einen einzigen Passagier wartet",
    "Eine Furt, die nur bei Neumond passierbar ist",
  // Werkstätten, Märkte & Geweihtes
    "Ein Jahrmarkt, der einmal im Jahr kommt und einen Stand zu viel hat",
    "Ein Kloster, dessen Bibliothek zwei Schlösser an einer Tür hat",
    "Eine Spinnstube, in der die Geschichten wahr werden, die man dort erzählt",
    "Ein Krämerladen, in dem alles zu haben ist, aber nicht für Geld",
    "Ein Kirchhof, auf dem ein Grab ohne Namen gepflegt wird",
    "Eine Mühle, deren Müller besser lebt, als das Korn erlaubt",
    "Ein Wallfahrtsort, an dem man einmal im Leben etwas erbitten darf",
    "Ein Marktplatz mit einem Pranger, den niemand mehr benutzt und niemand abbaut",
    "Eine Kapelle im Wald, in der eine Kerze immer frisch ist",
    "Ein Weberhaus, aus dem nachts der Webstuhl zu hören ist",
    "Ein Kaufmannshaus, dessen Reichtum auf einen einzigen Handel zurückgeht",
    "Ein Badehaus, in dem man nichts über sich erzählen darf",
    "Eine Schenke, in der Schulden nicht mit Geld beglichen werden",
    "Ein Waisenhaus, dessen Kinder alle gleich alt wirken",
    "Ein Kloster am Berg, das jedem Obdach gibt und niemanden gehen sieht",
    "Ein Wochenmarkt, auf dem ein Stand immer zuletzt abbaut",
];

export const MAERCHEN_PLACES: string[] = [
  ...MAERCHEN_AREAS,
  ...MAERCHEN_SPOTS,
];

/** Superhelden: Metropole, Konzerne, Verstecke, Behörden, Medien, Sperrzonen. */
export const SUPERHELDEN_AREAS: string[] = [
  // Die Stadt
    "Eine Metropole, deren Skyline in zehn Jahren dreimal umgebaut wurde",
    "Ein Finanzdistrikt, in dem die Fassaden neuer sind als die Verträge",
    "Ein Hafenviertel, das nach der letzten Evakuierung nie ganz zurückkam",
    "Ein Stadtteil, den die Versicherungen als Risikozone führen",
    "Eine Innenstadt mit mehr Kameras als Straßenlaternen",
    "Ein Viertel, das seine Feuerwehr selbst finanziert",
    "Ein Hochhaus, dessen oberste zwölf Stockwerke keinem gemeldeten Eigentümer gehören",
    "Eine Brücke, zweimal neu gebaut und beide Male aus demselben Grund",
    "Ein Bahnhof, unter dem eine stillgelegte Ebene bewohnt ist",
    "Ein Stadtviertel, in dem nachts niemand die Polizei ruft",
    "Eine Uferpromenade mit einem Denkmal für die Opfer, das die Ursache nicht nennt",
    "Ein Vergnügungsviertel, das bei jedem Wiederaufbau ein Stockwerk zugelegt hat",
    "Eine Werkssiedlung, deren Konzern die Straßen mitbesitzt",
    "Ein Stadtteil unter Dauerbaustelle, seit man dort etwas gefunden hat",
    "Ein Rathausbezirk, in dem drei Behörden für dieselbe Zone zuständig sind",
    "Ein Wohnblock, in dem eine Etage gemieden wird und niemand sagt, warum",
    "Eine Ausfallstraße mit einer Mautstelle, die es offiziell nicht gibt",
    "Ein Einwandererviertel, das seine eigene Nachtwache stellt",
    "Ein Stadtpark, der nachts geschlossen und trotzdem beleuchtet ist",
    "Eine Altstadt, deren Kanalsystem älter ist als jeder Stadtplan",
];

export const SUPERHELDEN_SPOTS: string[] = [
  // Labore & Konzerne
    "Ein Konzernturm mit einem Stockwerk, das im Fahrstuhl fehlt",
    "Ein Forschungslabor, dessen Geldgeber im Register eine Briefkastenfirma ist",
    "Ein Werksgelände, auf dem die Sirene monatlich getestet wird",
    "Ein Reaktor am Stadtrand, der als abgeschaltet gilt",
    "Ein Pharmakonzern mit einer eigenen Ambulanz für die eigene Belegschaft",
    "Ein Rechenzentrum, das die halbe Stadt mit Verkehrsdaten versorgt",
    "Ein Firmengelände, dessen Sicherheitsdienst besser ausgerüstet ist als das Revier",
    "Ein Labor unter einer Universität, das zu keinem Fachbereich gehört",
    "Ein Testgelände in der Wüste, drei Fahrstunden vom nächsten Ort",
    "Eine Chemiefabrik, deren Störfallakte nicht öffentlich ist",
    "Ein Gründerzentrum mit einem Gebäude ohne Fenster",
    "Ein Konzernarchiv, in dem Akten nach Jahrzehnten noch gesperrt sind",
    "Ein Klinikkomplex mit einer Station ohne Besuchszeiten",
    "Eine Werft, die Aufträge annimmt, deren Zweck nicht im Vertrag steht",
    "Ein Satellitenkontrollzentrum, das für einen einzigen Auftraggeber arbeitet",
    "Ein Forschungsschiff, das im Hafen liegt und nie ausläuft",
  // Hauptquartiere & Untergrund
    "Ein aufgegebener U-Bahn-Schacht, in den jemand Strom gelegt hat",
    "Ein Lagerhaus am Fluss, in das mehr geliefert wird, als je herauskommt",
    "Ein Penthouse mit einem Aufzug, der nur einen Knopf hat",
    "Ein Bunker aus dem letzten Krieg, kürzlich neu belüftet",
    "Eine ehemalige Feuerwache, die jemand privat gekauft hat",
    "Ein Kirchendachboden über einer Gemeinde, die nichts davon weiß",
    "Ein Parkhaus, dessen unterstes Deck seit Jahren gesperrt ist",
    "Eine Werkstatt hinter einer Werkstatt",
    "Ein Landhaus außerhalb, dessen Zufahrt auf keiner Karte steht",
    "Ein Serverraum in einer Wohnung, für die zu viel Strom bezahlt wird",
    "Ein stillgelegtes Wasserwerk mit einer sehr gut funktionierenden Tür",
    "Ein Clubkeller, in dem eine zweite Tür nie geöffnet wird",
    "Eine Bibliothek mit einem Magazin, zu dem drei Leute Schlüssel haben",
    "Ein Dachgarten, von dem aus man vier Bezirke einsieht",
    "Ein Boot im Yachthafen, das nie den Liegeplatz wechselt",
    "Ein Kino, dessen zweiter Saal seit Jahren renoviert wird",
  // Behörden, Haft & Gericht
    "Ein Hochsicherheitstrakt, gebaut für Insassen, die es damals noch nicht gab",
    "Ein Polizeirevier, in dem eine Sondereinheit ein eigenes Stockwerk hat",
    "Ein Gerichtsgebäude, in dem Verfahren regelmäßig unter Ausschluss laufen",
    "Eine Behörde, deren Zuständigkeit nirgends nachzulesen ist",
    "Ein Inselgefängnis, dessen Fähre einmal in der Woche fährt",
    "Ein Untersuchungsgefängnis mit einem Flügel ohne Kameras",
    "Ein Ausschuss, der öffentlich tagt und nichts entscheidet",
    "Ein Registrierungsbüro, vor dem täglich Leute stehen und manche zweimal",
    "Ein Militärstützpunkt am Stadtrand, der als Depot geführt wird",
    "Eine Kaserne, aus der nachts Fahrzeuge ohne Kennzeichen ausrücken",
    "Ein Stadtarchiv, in dem die Jahre eines Vorfalls fehlen",
    "Ein Krisenstab in einem Raum ohne Fenster",
    "Eine Grenzstation, an der Fähigkeiten angemeldet werden müssen",
    "Ein Amt für Wiederaufbau, das mehr Anträge hat als Mitarbeiter",
    "Ein Übungsgelände, auf dem geprobt wird, was offiziell nicht vorkommt",
    "Ein Sicherheitsrat, in dem zwei Städte sich eine Stimme teilen",
  // Medien & Öffentlichkeit
    "Eine Zeitungsredaktion, die seit dem Verkauf zwei Chefs hat",
    "Ein Fernsehsender mit einem eigenen Hubschrauber und einer eigenen Meinung",
    "Ein Stadion, das zweimal als Notunterkunft gedient hat",
    "Eine Universität, an der ein Institut Mittel bekommt, die niemand beantragt hat",
    "Ein Museum mit einer Ausstellung, die zu früh eröffnet wurde",
    "Ein Studio im Hinterhof, dem mehr Leute glauben als der Stadtverwaltung",
    "Ein Kongresszentrum, in dem jedes Jahr dieselbe Messe eskaliert",
    "Eine Schule, deren Turnhalle noch die Notbetten von damals lagert",
    "Ein Wohltätigkeitsball, auf dem jedes Jahr dieselben Namen spenden",
    "Ein Krankenhaus, dessen Notaufnahme eine eigene Statistik führt",
    "Ein Nachrichtenarchiv, in dem einzelne Bänder gesperrt sind",
    "Eine Kirche, die zur Anlaufstelle wurde, ohne es zu wollen",
    "Ein Gemeindezentrum, das die Angehörigen der Vermissten anschreibt",
    "Ein Rathaus mit einer Gedenktafel, die zweimal ergänzt wurde",
    "Ein Platz, an dessen Bauzaun Angehörige Fotos hängen",
    "Ein Verlagshaus, das eine Titelgeschichte seit Monaten zurückhält",
  // Schauplätze & Randgebiete
    "Ein Krater mitten im Stadtgebiet, um den herum gebaut wurde",
    "Eine Ruine, die als Mahnmal stehen bleiben soll und als Versteck dient",
    "Eine Sperrzone, in die Bauarbeiter nur in Begleitung dürfen",
    "Ein Industriehafen, in dem ein Container seit Jahren nicht abgeholt wird",
    "Ein Küstenabschnitt, an dem regelmäßig Dinge angespült werden",
    "Ein Vorort, der von der Metropole nichts wissen will",
    "Eine Kleinstadt zwei Stunden entfernt, in der plötzlich Reporter wohnen",
    "Ein Talkessel, in dem der Funkverkehr abbricht",
    "Eine Autobahnbrücke, halb gesperrt, seit sie repariert wurde",
    "Ein Vergnügungspark, seit einer Saison geschlossen und bewacht wie eine Anlage",
    "Eine Insel vor der Küste, deren Eigentümer nicht im Grundbuch steht",
    "Eine Bergstation, deren Seilbahn privat betrieben wird",
    "Ein Flughafen mit einem Terminal, das nie eröffnet wurde",
    "Ein Wüstenort, an dem eine Straße endet und eine Zufahrt beginnt",
    "Ein Stausee, dessen Pegel seit einem Zwischenfall überwacht wird",
    "Ein Grenzgebiet, in dem zwei Städte sich die Zuständigkeit teilen und keine übernimmt",
];

export const SUPERHELDEN_PLACES: string[] = [
  ...SUPERHELDEN_AREAS,
  ...SUPERHELDEN_SPOTS,
];

export const PLACES_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_PLACES,
  fantasy: FANTASY_PLACES,
  steampunk: STEAMPUNK_PLACES,
  cyberpunk: CYBERPUNK_PLACES,
  historisch: HISTORISCH_PLACES,
  western: WESTERN_PLACES,
  scifi: SCIFI_PLACES,
  maerchen: MAERCHEN_PLACES,
  superhelden: SUPERHELDEN_PLACES,
};

export const AREAS_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_AREAS,
  fantasy: FANTASY_AREAS,
  steampunk: STEAMPUNK_AREAS,
  cyberpunk: CYBERPUNK_AREAS,
  historisch: HISTORISCH_AREAS,
  western: WESTERN_AREAS,
  scifi: SCIFI_AREAS,
  maerchen: MAERCHEN_AREAS,
  superhelden: SUPERHELDEN_AREAS,
};

export const SPOTS_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_SPOTS,
  fantasy: FANTASY_SPOTS,
  steampunk: STEAMPUNK_SPOTS,
  cyberpunk: CYBERPUNK_SPOTS,
  historisch: HISTORISCH_SPOTS,
  western: WESTERN_SPOTS,
  scifi: SCIFI_SPOTS,
  maerchen: MAERCHEN_SPOTS,
  superhelden: SUPERHELDEN_SPOTS,
};

/**
 * Ein Ort, passend zum Genre. Ohne bekanntes Genre fällt die Wahl auf
 * „Gegenwart" – dieselbe Regel wie in `backgrounds.ts`, und aus demselben
 * Grund wird **nie** über die Listen gemischt.
 *
 * `ergaenzen` unterscheidet die beiden Lagen, in denen der Knopf gedrückt wird:
 *
 * - **Leeres Feld** (`false`): ein Rahmen und zwei Schauplätze darin,
 *   untereinander. Das ist die Form, die das Feld inzwischen erwartet.
 * - **Gefülltes Feld** (`true`): **nur ein Schauplatz**, den die aufrufende
 *   Seite anhängt. Die Annahme dahinter: Was Leute selbst eintippen, ist der
 *   Rahmen („Berlin", „Ein Fischerdorf"); was ihnen fehlt, ist das Konkrete
 *   darin. Ein zweiter Rahmen wäre in einem Feld, das schon einen hat, fast
 *   immer falsch.
 *
 * Was der Würfel **nicht** kann: prüfen, ob der gezogene Schauplatz zum
 * vorhandenen Rahmen passt. Er liest nicht, was dasteht – „Berlin" und ein
 * Dorfgasthof können nebeneinander landen. Dafür gibt es den KI-Knopf; dieser
 * hier ist der kostenlose, beliebig oft drückbare Anfang.
 */
export function randomPlace(genre?: string, ergaenzen = false): string {
  const key = genre ?? "";
  const spots = SPOTS_BY_GENRE[key] ?? GEGENWART_SPOTS;
  if (ergaenzen) return spots[Math.floor(Math.random() * spots.length)];

  const areas = AREAS_BY_GENRE[key] ?? GEGENWART_AREAS;
  const rahmen = areas[Math.floor(Math.random() * areas.length)];
  return [rahmen, ...pickSome(spots, 2, 2)].join("\n");
}
