/**
 * Orte für den Würfel am Szenario-Feld „Ort" – **je Genre eine eigene Liste zu
 * 100 Einträgen**.
 *
 * Aufgebaut wie `backgrounds.ts` und aus demselben Grund nach Genre getrennt
 * statt markiert: ein Ort trägt sein Genre in sich. „Ein Wohnblock, dessen
 * Aufzug seit Jahren steht" und „ein Turm, in dem die Treppe endet, bevor sie
 * oben ankommt" beschreiben dieselbe Enge – aber in Bildern, die sich nicht
 * austauschen lassen.
 *
 * Rein lokal, ohne API, wie alle Würfel im Projekt.
 *
 * **Ein Eintrag ist ein vollständiger Ort, kein Baustein.** Anders als beim
 * Aussehen oder Hintergrund wird hier **nicht** kombiniert: ein Szenario spielt
 * an einem Ort, nicht an zweieinhalb. Deshalb zieht `randomPlace` genau einen.
 *
 * Jeder Eintrag nennt den Ort **und ein Detail, das ihn kippen lässt** – etwas
 * Kaputtes, Verschwiegenes oder Unfertiges. Ein Ort ohne Riss ist eine Kulisse;
 * einer mit Riss ist ein Anfang.
 */

/** Gegenwart: Stadt, Provinz, Arbeitsplätze, Einrichtungen, Unterwegs. */
export const GEGENWART_PLACES: string[] = [
  // Stadt
  "Ein Altbauviertel, in dem die letzten alten Mieter zwischen sanierten Wohnungen ausharren",
  "Eine Hochhaussiedlung am Stadtrand, deren Einkaufszentrum zur Hälfte leer steht",
  "Ein Hafenviertel, in dem die Kräne stillstehen und die Mieten trotzdem steigen",
  "Eine Innenstadt, in der jeden Monat ein weiteres Ladenlokal zum Späti wird",
  "Ein Bahnhofsviertel, das nach zweiundzwanzig Uhr einer anderen Stadt gehört",
  "Eine Straße mit zwei Moscheen, einer Kirche und keinem Supermarkt",
  "Ein Studentenviertel, aus dem die Studenten längst weggezogen sind",
  "Ein Neubaugebiet, in dem noch kein Baum groß genug für Schatten ist",
  "Ein Gewerbegebiet mit einer einzigen Bushaltestelle und drei Schichten",
  "Ein Stadtteil, der seit dreißig Jahren auf die versprochene U-Bahn wartet",
  "Ein Häuserblock, in dem alle einander kennen und niemand miteinander spricht",
  "Eine Fußgängerzone, die abends von Sicherheitsdiensten geräumt wird",
  "Ein Kleingartenverein, eingekesselt zwischen Autobahn und Baugrube",
  "Ein Viertel, in dem gerade der erste Concept Store aufgemacht hat",
  "Eine Hinterhofwerkstatt zwischen zwei Galerien, noch nicht verdrängt",
  "Ein Wohnblock, dessen Aufzug seit zwei Jahren stillsteht",
  "Ein Platz, auf dem sich morgens die Tagelöhner und mittags die Touristen sammeln",
  "Eine Ausfallstraße, an der jedes zweite Haus einen Schallschutz-Antrag laufen hat",
  "Ein Stadtteil, in dem die Feuerwehr zu zweit ausrückt und die Polizei zu viert",
  "Ein Wohnhaus mit sieben Klingelschildern und elf Briefkästen",

  // Provinz & Land
  "Ein Dorf, dessen letzte Kneipe zum Wohnhaus umgebaut wurde",
  "Eine Kleinstadt, in der die Fabrik zumachte und die Straßennamen blieben",
  "Ein Ort mit einem Freibad, das nur noch an Wochenenden aufmacht",
  "Ein Weiler, in dem drei Höfe bewirtschaftet werden und neun leer stehen",
  "Eine Gemeinde, die um jeden Schüler kämpft, damit die Schule bleibt",
  "Ein Küstenort, der neun Monate im Jahr sich selbst gehört",
  "Ein Kurort, dessen Klinik verkauft wurde und dessen Gäste ausblieben",
  "Ein Bergdorf, das im Winter über eine einzige Straße erreichbar ist",
  "Ein Ort direkt an der Grenze, wo man zum Einkaufen ins Nachbarland fährt",
  "Eine Streusiedlung, in der der Bus zweimal am Tag fährt, außer in den Ferien",
  "Ein Dorf mit einem Windpark, über den seit acht Jahren gestritten wird",
  "Eine Kleinstadt, in der alle im selben Werk arbeiten oder gearbeitet haben",
  "Ein Ort, dessen Jugend am Freitag in die nächste Stadt fährt und sonntags zurück",
  "Eine Marschlandschaft, in der die Deiche jedes Jahr etwas höher werden",
  "Ein Tagebaurand, an dem drei Dörfer auf ihre Umsiedlung warten",
  "Ein Dorf, in dem seit dem Hochwasser jeder weiß, wer wem geholfen hat",
  "Eine Insel, auf der die Fähre den Takt des Tages vorgibt",
  "Ein Talort, durch den täglich vierhundert Lastwagen fahren",
  "Eine Gegend, in der die Handynetze an der Kreisgrenze enden",
  "Ein Ort mit einem neuen Logistikzentrum und keiner Wohnung mehr unter tausend Euro",

  // Arbeitsplätze
  "Eine Großküche, in der sieben Sprachen gesprochen und keine gelernt wird",
  "Ein Callcenter im dritten Stock über einem Möbelhaus",
  "Eine Lagerhalle, in der ein Scanner den Takt vorgibt",
  "Eine Werkstatt, die vom Sohn übernommen wurde, der sie nicht wollte",
  "Ein Krankenhaus, dessen Station seit Monaten in Unterbesetzung fährt",
  "Ein Labor in einem Institut, dessen Förderung im Sommer ausläuft",
  "Eine Redaktion, die von zwölf auf vier Leute geschrumpft ist",
  "Ein Hotel, das eine Kette gekauft hat und nun anders heißt",
  "Ein Familienbetrieb, in dem drei Generationen dieselbe Werkbank benutzen",
  "Eine Baustelle, auf der vier Subunternehmer nebeneinanderher arbeiten",
  "Ein Restaurant mit einem Stern und einer Küchenbrigade am Anschlag",
  "Ein Coworking-Space, in dem jeder von seinem eigenen Projekt lebt",
  "Eine Molkerei, die als Letzte in der Region noch annimmt",
  "Ein Recyclinghof, an dem man mehr über die Stadt erfährt als im Rathaus",
  "Eine Schreinerei, deren Auftragsbuch voll und deren Nachfolge offen ist",
  "Ein Taxiunternehmen mit sechs Wagen und zwei Fahrern, die alles machen",
  "Ein Fotostudio, das von Bewerbungsbildern und Beerdigungen lebt",
  "Eine Apotheke, die die halbe Nachbarschaft beim Vornamen kennt",
  "Ein Kino mit zwei Sälen und einem Betreiber, der nicht aufgeben will",
  "Ein Musikstudio im Keller, dessen Miete drei Leute zusammenlegen",

  // Einrichtungen
  "Eine Gesamtschule, an der jedes Jahr die Hälfte der Referendare geht",
  "Ein Pflegeheim, in dem der Frühdienst um halb sechs allein beginnt",
  "Eine Sozialstation, deren Warteliste länger ist als ihr Kalender",
  "Ein Jugendzentrum, dessen Förderung Jahr für Jahr neu beantragt wird",
  "Eine Bibliothek, die zur Wärmestube geworden ist, ohne dass es jemand ausspricht",
  "Ein Amt, in dem Termine sechs Wochen vorher vergeben werden",
  "Eine Kirchengemeinde mit einer vollen Tafel und einem leeren Gottesdienst",
  "Ein Sportverein, der über den einen Trainer zusammenhält",
  "Ein Gericht, dessen Verfahren sich seit Jahren stauen",
  "Eine Unterkunft, die als Provisorium gebaut wurde und im achten Jahr steht",
  "Ein Tierheim, das keine Katzen mehr aufnehmen kann",
  "Eine Musikschule im Gebäude der stillgelegten Grundschule",
  "Ein Hospiz mit Blick auf einen Parkplatz",
  "Eine Suchtberatung im Erdgeschoss, direkt neben einem Wettbüro",
  "Ein Frauenhaus, dessen Adresse alle im Ort kennen",
  "Eine Volkshochschule, deren beliebtester Kurs Deutsch ist",
  "Ein Wahllokal in einer Turnhalle, in der es nach Bohnerwachs riecht",
  "Ein Forschungsschiff im Winterhafen, mit halber Besatzung",
  "Eine Justizvollzugsanstalt am Ortsrand, um die ein Radweg führt",
  "Ein Rechenzentrum auf einem Acker, das keinen einzigen Arbeitsplatz brachte",

  // Unterwegs & Dazwischen
  "Ein Nachtzug, in dem sich dieselben Leute jede Woche begegnen",
  "Eine Autobahnraststätte, die nachts ihr eigenes Publikum hat",
  "Ein Fernbus auf der Strecke zwischen zwei Ländern",
  "Ein Flughafen-Transitbereich, in dem jemand seit vier Tagen wartet",
  "Eine Fähre, die zweimal täglich dieselben Gesichter transportiert",
  "Ein Wohnmobil auf einem Stellplatz, der als Dauerlösung gilt",
  "Eine Ferienwohnung, die zwischen zwei Buchungen leer steht",
  "Ein Pilgerweg, auf dem im Herbst nur noch die Ernsthaften gehen",
  "Ein Campingplatz, dessen Dauercamper eine eigene Ordnung haben",
  "Eine Umsteigestation, an der man nachts vierzig Minuten wartet",
  "Ein Frachtschiff, auf dem der Koch die einzige Konstante ist",
  "Ein Ferienhaus im Februar, ohne Nachbarn im Umkreis von zwei Kilometern",
  "Ein Zeltplatz nach dem Festival, an dem die Hälfte stehen gelassen wurde",
  "Ein Krankentransport, der täglich dieselbe Strecke fährt",
  "Eine Parkbucht mit Blick, auf der abends immer dieselben Autos stehen",
  "Ein Straßenzug, durch den seit dem Umbau kein Auto mehr fährt",
  "Ein Baumarktparkplatz, auf dem sich morgens um sieben etwas anderes abspielt",
  "Ein Waldstück am Stadtrand, in dem seit Wochen jemand wohnt",
  "Eine Brücke, unter der jemand seine Sachen ordentlich stapelt",
  "Ein Grenzübergang, an dem seit dem Sommer wieder kontrolliert wird",
];

/** Fantasy: Siedlungen, Wildnis, Bauwerke, Zwielicht, Heiliges. */
export const FANTASY_PLACES: string[] = [
  // Siedlungen
  "Ein Dorf am Waldrand, dessen Zaun jedes Jahr ein Stück näher an die Häuser rückt",
  "Eine Handelsstadt an einer Furt, die den Zoll selbst festlegt",
  "Ein Bergwerksort, dessen tiefster Stollen zugemauert wurde und über den niemand redet",
  "Eine Hafenstadt mit zwei Häfen: einem für Waren, einem für alles andere",
  "Ein Dorf, das sein Getreide dem Fluss verdankt und sein Schweigen dem Herrn",
  "Eine Stadt mit einer Mauer, die für die doppelte Einwohnerzahl gebaut wurde",
  "Ein Weiler auf einer Lichtung, den man ohne Führer nicht wiederfindet",
  "Eine Grenzstadt, in der zwei Sprachen und drei Gesetze gelten",
  "Ein Fischerdorf, dessen Boote nachts nicht auslaufen",
  "Eine Karawanserei am Wüstenrand, in der Waffen an der Tür bleiben",
  "Ein Dorf, das um einen Brunnen gebaut wurde, der seit dem Frühjahr trocken liegt",
  "Eine Stadt, in der die Gilden mehr entscheiden als der Rat",
  "Ein Bergdorf, das im Winter von der Welt abgeschnitten ist und das mag",
  "Eine Siedlung von Vertriebenen, die niemand offiziell zur Kenntnis nimmt",
  "Ein Marktflecken, an dem sich vier Straßen und vier Zuständigkeiten kreuzen",
  "Eine Pfahlbausiedlung im Sumpf, erreichbar über Stege, die man kennen muss",
  "Ein Dorf mit einer Schmiede, die nie kalt wird, und einer Kirche, die selten warm ist",
  "Eine Stadt, die auf den Ruinen einer älteren steht und deren Keller tiefer reichen als bekannt",
  "Ein Ort, in dem alle denselben Nachnamen tragen",
  "Eine Siedlung entlang einer alten Heerstraße, die niemand mehr instand hält",

  // Wildnis
  "Ein Wald, in dem die Wege sich nach der Jahreszeit ändern",
  "Ein Moor, das im Sommer Torf und im Winter Vermisste hergibt",
  "Ein Hochpass, der drei Monate im Jahr offen ist",
  "Eine Steppe, über die zweimal jährlich die Herden und einmal die Reiter ziehen",
  "Ein Küstenstreifen mit Klippen, an denen regelmäßig Wrackgut anlandet",
  "Ein Tal, in dem es früher dunkel wird als überall sonst",
  "Ein Urwald, dessen Bäume älter sind als jedes Königreich der Gegend",
  "Ein Gletscher, der jedes Jahr etwas freigibt, was besser eingefroren geblieben wäre",
  "Eine Insel, die auf keiner beiden Seekarten gleich eingezeichnet ist",
  "Ein Flusstal, das alle sieben Jahre über die Ufer tritt, immer im selben Monat",
  "Eine Wüste mit einer Straße aus Steinplatten, die von niemandem stammt",
  "Ein Sumpfgebiet, in dem Feuer nicht brennen will",
  "Eine Heide, auf der das Vieh gedeiht und die Menschen nicht bleiben",
  "Ein Höhlensystem, das weiter reicht als jede Karte behauptet",
  "Ein See, dessen Grund niemand ausgelotet hat",
  "Ein Wald, den die Dörfler nur zu dritt betreten",
  "Eine Schlucht mit einer einzigen Brücke und einem Wärter",
  "Eine Vulkaninsel, deren Boden alles wachsen lässt und alle nervös macht",
  "Ein Tal voller Steinsäulen, um die man einen Bogen macht",
  "Eine Küste, an der die Ebbe einen Weg freigibt und die Flut ihn nimmt",

  // Bauwerke
  "Eine Burg, die zwei Belagerungen überstand und den Frieden kaum",
  "Ein Turm, dessen obere Stockwerke seit Generationen verschlossen sind",
  "Eine Festung an einer Grenze, die es nicht mehr gibt",
  "Ein Palast, in dem mehr Diener leben als Herrschaft",
  "Eine Brücke aus alter Zeit, die niemand nachbauen könnte",
  "Ein Leuchtturm, dessen Feuer seit dem Herbst nicht mehr brennt",
  "Ein Aquädukt, das eine Stadt versorgt, die nicht mehr steht",
  "Eine Bibliothek, deren Katalog vollständiger ist als ihr Bestand",
  "Ein Wachturm auf einem Pass, besetzt von vier Leuten und einem Hund",
  "Eine Zitadelle mitten in der Stadt, die nach innen zeigt statt nach außen",
  "Ein Bergwerk, dessen Förderturm noch steht und dessen Schacht geflutet ist",
  "Eine Ruine, in der ein Dorf sein Vieh unterstellt",
  "Ein Kanalsystem unter der Stadt, älter als die Stadt",
  "Eine Grabanlage, die als Steinbruch benutzt wird",
  "Ein Herrenhaus, dessen Besitzer seit drei Jahren niemand gesehen hat",
  "Eine Mühle am Fluss, die dem Müller gehört und über die alle reden",
  "Ein Torhaus, an dem jeder zahlt außer denen, die es nicht müssen",
  "Eine Arena, die man zum Getreidespeicher umgebaut hat",
  "Ein Observatorium auf einem Berg, aus dem seit Jahren niemand herunterkam",
  "Ein Kloster mit einer Mauer, die eher nach innen als nach außen gerichtet scheint",

  // Zwielicht
  "Eine Diebesgilde, die sich als Fuhrunternehmen führt",
  "Ein Wirtshaus, in dem an einem Tisch nie jemand sitzt",
  "Ein Schwarzmarkt, der jede Woche den Ort wechselt",
  "Ein Hafenlager, dessen Inventar nicht mit den Zollbüchern übereinstimmt",
  "Eine Spielhölle, in der man auch mit anderem als Geld bezahlt",
  "Ein Badehaus, in dem mehr verhandelt als gebadet wird",
  "Ein Bordell mit den besten Informationen der Stadt",
  "Eine Kaschemme im Kellergewölbe, mit zwei Ausgängen und einer Regel",
  "Ein Pfandhaus, das die halbe Stadt in Büchern hat",
  "Eine Schmugglerbucht, die nur bei bestimmtem Wind anzulaufen ist",
  "Ein Söldnerlager vor den Toren, das man nicht wegschicken kann",
  "Ein Sklavenmarkt, der offiziell abgeschafft ist",
  "Eine Gasse, in der die Stadtwache zu zweit nicht mehr hineingeht",
  "Ein Gasthof an der Straße, aus dem regelmäßig Gäste nicht weiterreisen",
  "Ein Alchemistenviertel, dessen Rauch die Nachbarschaft vertrieben hat",
  "Ein Fälscherhaus, das Siegel für vier Königreiche führt",
  "Eine Arena für verbotene Kämpfe, unter einer legalen",
  "Ein Kartenhaus, in dem Karten gezeichnet werden, die es nicht geben darf",
  "Ein Kontor, das Waren versichert, die nie verschifft wurden",
  "Ein Tunnel unter der Stadtmauer, den alle kennen und niemand meldet",

  // Heiliges & Unheimliches
  "Ein Tempel, dessen Priesterschaft sich in zwei Auslegungen gespalten hat",
  "Ein heiliger Hain, in dem seit dem Frühling nicht mehr geopfert wird",
  "Eine Wallfahrtsstätte, deren Wunder ausgeblieben sind",
  "Ein Schrein an einer Wegkreuzung, an dem jeder etwas ablegt",
  "Ein Kloster, das Zuflucht gewährt und keine Fragen stellt",
  "Eine Kathedrale, die seit sechzig Jahren im Bau ist",
  "Ein Orden, dessen Regel strenger geworden ist als sein Glaube",
  "Ein Friedhof, auf dem die Gräber nach Westen zeigen, alle bis auf eins",
  "Eine Quelle, der man Heilkraft nachsagt und deren Wasser man abkocht",
  "Ein Steinkreis, um den herum gepflügt wird",
  "Ein Turm der Magier, der Lehrgeld verlangt und keine Fragen beantwortet",
  "Eine Akademie, an der zwei Schulen unterrichtet werden, die einander verachten",
  "Ein verlassenes Heiligtum, in dem noch Kerzen brennen",
  "Ein Ossarium unter einer Kirche, dessen Zugang nur der Küster kennt",
  "Eine Insel der Eremiten, die einmal im Jahr Besuch dulden",
  "Ein Ort, an dem Eide gelten und alle das ernst nehmen",
  "Eine Krypta, die man geöffnet hat, weil Platz gebraucht wurde",
  "Ein Berg, den zu besteigen als Frevel gilt und den doch jeder Hirte kennt",
  "Ein Waldheiligtum, das zwei Dörfer für sich beanspruchen",
  "Ein Baum am Dorfplatz, unter dem Recht gesprochen wird",
];

/** Steampunk: Industriestadt, Verkehr, Werkstätten, Gesellschaft, Untergrund. */
export const STEAMPUNK_PLACES: string[] = [
  // Industriestadt
  "Ein Fabrikviertel, über dem der Rauch tiefer hängt als die Dächer",
  "Eine Stadt mit einer Uhr, nach der sich alle Schichten richten",
  "Ein Werksgelände mit eigenem Bahnanschluss und eigener Gerichtsbarkeit",
  "Eine Arbeitersiedlung, die der Fabrik gehört, samt Läden und Schule",
  "Ein Kesselhaus, das die halbe Stadt mit Dampf versorgt",
  "Ein Hüttenwerk, dessen Feuer seit vierzig Jahren nicht aus war",
  "Ein Viertel, in dem die Wäsche grau von der Leine kommt",
  "Eine Gasanstalt am Fluss, deren Geruch bis in die Oberstadt zieht",
  "Ein Kanal, an dem Lastkähne im Minutentakt vorbeiziehen",
  "Eine Stadt auf zwei Ebenen: unten die Rohre, oben die Fassaden",
  "Ein Bahnbetriebswerk mit dreihundert Beschäftigten und einer Werksgewerkschaft",
  "Eine Spinnerei, in der der Lärm das Sprechen ersetzt hat",
  "Ein Kohlenhafen, dessen Staub sich in allem absetzt",
  "Ein Hochofenwerk, um das ein ganzer Ort gewachsen ist",
  "Eine Manufaktur, die auf Feinmechanik umgestellt hat und die Hälfte entließ",
  "Ein Elektrizitätswerk, das erst wenige Straßen versorgt und alle Interessen weckt",
  "Ein Viertel, in dem die Zisternen wichtiger sind als die Brunnen",
  "Eine Werft, die vom Segelbau auf Dampf umstellt und beide Zünfte gegen sich hat",
  "Eine Bergarbeiterstadt, deren Halden höher sind als ihre Kirche",
  "Ein Industrierevier, in dem drei Firmen alles besitzen außer den Menschen",

  // Verkehr & Luft
  "Ein Luftschiffhafen, dessen Türme über den Fabrikschloten stehen",
  "Ein Kopfbahnhof mit Glasdach und einer Halle, in der man sich verliert",
  "Ein Rangierbahnhof, auf dem nachts mehr los ist als tagsüber",
  "Eine Bergbahn, die vier Dörfer erschließt und drei ruiniert hat",
  "Eine Zeppelinwerft, an der zweitausend Menschen arbeiten und niemand versichert ist",
  "Ein Hafen, in dem Segler und Dampfer um jeden Liegeplatz streiten",
  "Eine Pneumatikpost, deren Röhren unter der ganzen Innenstadt liegen",
  "Ein Schleusenwerk, das den Warenfluss zweier Provinzen regelt",
  "Eine Untergrundbahn, deren erste Linie gerade eröffnet wurde",
  "Ein Postkutschenwechsel, den die Eisenbahn überflüssig gemacht hat",
  "Ein Tunnel durch den Berg, an dem seit neun Jahren gebaut wird",
  "Eine Schwebebahn über einem Fluss, die als Wunder gilt und als Zumutung",
  "Ein Kanalhafen mit Kränen, die noch von Hand bedient werden",
  "Eine Straßenbahnremise, deren Pferde gerade durch Motoren ersetzt werden",
  "Ein Frachtluftschiff auf Zwischenlandung, mit Ladung ohne Papiere",
  "Ein Leuchtfeuerturm mit Dampfsirene, die man drei Meilen weit hört",
  "Eine Eisenbahnbrücke, die man für doppelte Last freigegeben hat",
  "Ein Depot, in dem Lokomotiven abgestellt sind, für die es keine Strecke gibt",
  "Ein Umschlagplatz, an dem Schiene, Kanal und Straße aufeinandertreffen",
  "Eine Ballonstation auf einem Hügel, von der aus die Stadt vermessen wird",

  // Werkstätten & Labore
  "Eine Werkstatt für Feinmechanik, in der drei Uhrmacher und ein Erfinder sitzen",
  "Ein Laboratorium im Dachgeschoss, dessen Vermieter nichts weiß",
  "Ein Patentamt, dessen Archiv niemand mehr überblickt",
  "Eine Erfinderwerkstatt, die von einem einzigen Geldgeber abhängt",
  "Ein anatomisches Theater, in dem öffentlich vorgeführt wird",
  "Eine Prothesenwerkstatt gegenüber dem Werkstor",
  "Ein chemisches Institut, dessen Abwässer in den Stadtfluss gehen",
  "Ein Observatorium mit einem Instrument, das größer ist als sein Etat",
  "Eine Maschinenhalle, in der Prototypen stehen, die nie liefen",
  "Ein Konstruktionsbüro, in dem an einer Sache gearbeitet wird, die niemand benennt",
  "Eine Werkstatt für Automaten, deren Auftraggeber anonym bleiben",
  "Ein Kesselschmiede-Hof, auf dem die Prüfstelle nie erscheint",
  "Ein Institut für Elektrizität, das mit Spenden und Aufsehen finanziert wird",
  "Eine Druckerei mit einer Rotationsmaschine und zwei Konkurrenzblättern",
  "Eine Fotografenwerkstatt, in der Verfahren erprobt werden, die noch giftig sind",
  "Ein Uhrturm, dessen Werk ein Mann allein instand hält",
  "Eine Waffenmanufaktur mit einem Auftrag, der die Stadt ernährt",
  "Ein Ballonlabor, in dem Gasgemische ausprobiert werden",
  "Eine Werkstatt für Rechenmaschinen, deren Bestellungen aus einer Behörde kommen",
  "Ein Prüfstand außerhalb der Stadt, dessen Lärm nachts zu hören ist",

  // Gesellschaft
  "Ein Herrenclub, in dem über Konzessionen entschieden wird",
  "Eine Handelskammer, die mehr Macht hat als der Stadtrat",
  "Ein Opernhaus, das ein Fabrikant gestiftet und nach sich benannt hat",
  "Ein Kurbad, in das die Industriellen fahren, wenn der Rauch zu dick wird",
  "Eine Villenkolonie auf der windzugewandten Seite der Stadt",
  "Ein Vortragssaal, in dem Fortschritt und Empörung dasselbe Publikum haben",
  "Eine Weltausstellungshalle, drei Monate vor der Eröffnung",
  "Ein Bankhaus, das drei Werke finanziert und alle drei kontrolliert",
  "Ein Rathaus, dessen Bauamt seit Jahren dieselben Genehmigungen erteilt",
  "Eine Zeitungsredaktion, die von Anzeigen der Fabriken lebt",
  "Ein Gewerkschaftshaus, das man zweimal geräumt hat",
  "Ein Armenhaus, das die Stadt betreibt und die Kirche verwaltet",
  "Eine Bergwerksdirektion, die dreißig Kilometer von jedem Schacht entfernt liegt",
  "Ein Kaufhaus mit elektrischem Licht und Personal, das im Dachgeschoss schläft",
  "Ein Kolonialkontor, dessen Waren keiner nach ihrer Herkunft fragt",
  "Eine Akademie, an der Ingenieure und Militärs zusammen ausgebildet werden",
  "Ein Gerichtssaal, in dem gerade der erste Prozess um einen Arbeitsunfall läuft",
  "Ein Kaffeehaus, in dem Aktienkurse ausgerufen werden",
  "Ein Krankenhaus, das eine Stiftung trägt und ein Werksarzt leitet",
  "Ein Waisenhaus, dessen Zöglinge mit vierzehn in die Fabrik gehen",

  // Untergrund
  "Ein Kanalnetz, in dem Menschen leben, die dort nicht gemeldet sind",
  "Eine stillgelegte Strecke, die ein anderes Gewerbe übernommen hat",
  "Ein Schmugglerlager unter einem Kohlenhof",
  "Eine Kellerkneipe, in der die Streikkasse verwaltet wird",
  "Ein aufgelassener Schacht, durch den man unter die Stadtmauer kommt",
  "Eine Untergrundpresse in einer Kellerdruckerei",
  "Ein Lager für gestohlene Bauteile, sortiert wie ein Ersatzteillager",
  "Eine Boxarena unter einem Lagerhaus, mit Wetteinnahmen für drei Parteien",
  "Ein Netz von Kriechgängen zwischen den Kesselhäusern",
  "Ein Opiumhaus im Hafenviertel, mit einer Hintertür zur Zollstraße",
  "Ein Depot mit Sprengstoff, für das niemand zuständig sein will",
  "Ein Versammlungsraum ohne Fenster, dessen Adresse mündlich weitergegeben wird",
  "Eine Werkstatt, die Fabrikmarken fälscht",
  "Ein Tunnel, den die Arbeiter selbst gegraben haben, um den Werksschutz zu umgehen",
  "Ein Zwischenboden über einer Halle, in dem jemand wohnt",
  "Eine Kammer im Fundament, die auf keinem Bauplan steht",
  "Eine Zisterne, die als Versammlungsort dient, weil sie den Schall schluckt",
  "Ein Abwasserstollen, durch den man in drei Viertel gleichzeitig kommt",
  "Ein Kohlenkeller mit doppeltem Boden",
  "Ein Katakombenabschnitt, in dem eine Werkstatt ohne Konzession arbeitet",
];

/** Cyberpunk: Megacity, Konzern, Slums, Netz, Ödland. */
export const CYBERPUNK_PLACES: string[] = [
  // Megacity
  "Ein Stadtblock, dessen unterste zwölf Etagen kein Tageslicht sehen",
  "Ein Viertel, in dem die Werbeflächen heller sind als jede Straßenlaterne",
  "Ein Wohnturm mit dreitausend Einheiten und einem funktionierenden Aufzug",
  "Eine Sperrzone, die nach einem Chemieunfall nie freigegeben wurde",
  "Ein Distrikt, in dem drei Sicherheitsfirmen konkurrierende Zuständigkeiten haben",
  "Ein Kapselhotel-Komplex, in dem Leute seit Jahren wohnen",
  "Ein Marktviertel unter einer Hochstraße, mit eigener Stromversorgung",
  "Eine Zone, in der die Netzabdeckung absichtlich abgeschaltet wurde",
  "Ein Hochhaus, dessen obere Hälfte einer Firma und untere niemandem gehört",
  "Ein Stadtteil, der offiziell abgerissen ist und in dem vierzigtausend leben",
  "Eine Uferpromenade, die man drei Meter höher neu gebaut hat",
  "Ein Verkehrsknoten mit vier Ebenen, an dem sich alles trifft, was sich sonst meidet",
  "Ein Viertel, in dem Mieten in Rechenleistung bezahlt werden",
  "Eine Altstadt unter einer Kuppel, konserviert und eintrittspflichtig",
  "Ein Bezirk, dessen Wasserversorgung privatisiert wurde und stundenweise läuft",
  "Ein Wohnkomplex mit Gesichtserkennung an jedem Treppenhaus",
  "Ein Hafen, der vollautomatisch läuft und in dem trotzdem tausend Menschen arbeiten",
  "Eine Straße, die von zwei Banden auf halber Länge geteilt wird",
  "Ein Viertel, in dem die Klimaanlagen mehr Strom brauchen als die Wohnungen",
  "Ein Stadtgebiet, das nach dem Sturm nie wieder ans Netz ging",

  // Konzern
  "Ein Firmencampus mit eigener Werkssicherheit und eigenem Arbeitsrecht",
  "Ein Konzernturm, dessen oberste Etagen keinen Aufzugsknopf haben",
  "Ein Forschungslabor, dessen Existenz in keiner Bilanz auftaucht",
  "Eine Fertigungsanlage, in der zwölf Menschen und viertausend Maschinen arbeiten",
  "Ein Rechenzentrum, das mit Flusswasser gekühlt wird und den Fluss aufheizt",
  "Eine Konzernklinik, in der Behandlung an den Arbeitsvertrag gekoppelt ist",
  "Ein Ausbildungszentrum, dessen Absolventen sieben Jahre gebunden sind",
  "Ein Rohstofflager mit einer Sicherung, die teurer war als der Inhalt",
  "Ein Bürokomplex, in dem zwei Abteilungen einander bespitzeln",
  "Eine Teststrecke außerhalb der Stadt, hinter drei Zäunen",
  "Ein Serverraum, dessen Zugang nur vier Personen haben und einer davon ist tot",
  "Ein Vorstandsgebäude mit einem Hubschrauberdach und keinem Erdgeschoss",
  "Eine Konzernsiedlung, in der Wohnen, Einkaufen und Schule von einer Firma kommen",
  "Ein Werk, das nach einem Streik durch Roboter ersetzt wurde",
  "Eine Zulieferhalle, die drei Konzerne gleichzeitig beliefert und keinem gehört",
  "Ein Archivgebäude, dessen Bestände nie digitalisiert wurden, mit Absicht",
  "Eine Recyclinganlage, in der Prototypen vernichtet werden sollen",
  "Ein Hochsicherheitslabor unter einem gewöhnlichen Bürogebäude",
  "Eine Konzernbotschaft in einem Staat, der den Konzern nicht kontrolliert",
  "Ein Firmenhotel, in dem Verhandlungen stattfinden, die es offiziell nicht gibt",

  // Slums & Ränder
  "Eine Wellblechstadt auf dem Dach eines Parkhauses",
  "Ein Viertel ohne Postadressen, in dem Pakete trotzdem ankommen",
  "Eine Siedlung in einer stillgelegten U-Bahn-Station",
  "Ein Elendsquartier auf aufgeschüttetem Müll, dreißig Jahre alt",
  "Ein Block, in dem eine Klinik ohne Zulassung die einzige medizinische Versorgung ist",
  "Ein Markt, auf dem gebrauchte Implantate gehandelt werden",
  "Ein Viertel, dessen Strom von einer selbstgebauten Leitung kommt",
  "Eine Zeltstadt vor dem Werkstor, seit dem letzten Massenabbau",
  "Ein Containerdorf im Hafen, das als Übergangslösung errichtet wurde",
  "Ein Wohnschiff, das nicht auslaufen darf und nicht abgewrackt wird",
  "Eine Brachfläche, auf der eine Gemeinschaft Gemüse anbaut und es verteidigt",
  "Ein Häuserblock, den die Bewohner selbst instand halten, weil niemand kommt",
  "Ein Tunnelabschnitt, in dem eine Schule ohne Genehmigung betrieben wird",
  "Eine Kanalisation, in der eine Gruppe seit Jahren lebt und Regeln hat",
  "Ein Viertel, in dem Wasser teurer ist als Bandbreite",
  "Ein Areal, das nach einem Brand abgesperrt wurde und wieder bewohnt ist",
  "Ein Bordellkomplex mit angeschlossener Klinik, beide vom selben Betreiber",
  "Ein Fabrikgelände, das eine Familie besetzt hält und als Werkstatt betreibt",
  "Ein Hochhaus mit einem Wachdienst, den die Bewohner selbst bezahlen",
  "Eine Straße, in der jede Kamera zerschlagen wird, sobald sie hängt",

  // Netz & Untergrund
  "Ein Datenhafen in einem Land ohne Auslieferungsabkommen",
  "Ein Kellerlabor, in dem Implantate ohne Papiere eingesetzt werden",
  "Ein Netzknoten, den eine Gruppe kontrolliert und wie eine Mautstelle betreibt",
  "Ein Serverkeller unter einer Wäscherei",
  "Ein Schwarzmarkt für Identitäten, aufgebaut wie ein Reisebüro",
  "Eine Werkstatt, in der Fahrzeuge ihre Kennung verlieren",
  "Ein Piratensender, dessen Standort wöchentlich wechselt",
  "Ein Umschlagplatz für Daten, physisch, auf Trägern, per Kurier",
  "Ein Hackerkollektiv in einer ehemaligen Bibliothek",
  "Ein Simulationslokal, in dem man Erinnerungen kaufen kann",
  "Eine Klinik, die Implantate entfernt und keine Fragen stellt",
  "Eine Fälscherwerkstatt für Arbeitsnachweise",
  "Ein Bunker aus einem alten Krieg, jetzt mit eigener Stromversorgung",
  "Ein Depot für Hardware, die auf keiner Zollliste steht",
  "Ein Netzwerkraum, der nur analog erreichbar ist",
  "Eine Untergrundbörse, an der Sicherheitslücken gehandelt werden",
  "Ein Treffpunkt für Aussteiger aus Konzernverträgen",
  "Ein Lager mit Waffen aus einer aufgelösten Sicherheitsfirma",
  "Ein Datenfriedhof, auf dem Träger verschrottet werden sollen und nicht werden",
  "Ein Raum ohne jede Elektronik, in dem deshalb verhandelt wird",

  // Ödland & Draußen
  "Ein Autobahnkreuz, um das eine Siedlung gewachsen ist",
  "Eine Industriebrache, auf der nichts wächst und trotzdem jemand wohnt",
  "Ein Solarfeld in der Wüste, bewacht von zwei Leuten und einer Drohne",
  "Ein ausgetrocknetes Flussbett, auf dem Konvois fahren",
  "Eine Küstenstadt, deren untere Straßen bei Flut unter Wasser stehen",
  "Ein Farmkomplex, der einem Konzern gehört und keine Nachbarn duldet",
  "Ein Windpark, dessen Wartungsmannschaft seit Monaten nicht abgelöst wurde",
  "Eine Schnellstraße durch verlassenes Land, mit Tankstellen alle zweihundert Kilometer",
  "Eine Bergbaustadt, die abgebaut wurde und deren Loch geblieben ist",
  "Ein Grenzposten zwischen zwei Konzerngebieten",
  "Ein Frachtflughafen mitten im Nichts, nachts hell erleuchtet",
  "Eine Wasseraufbereitungsanlage, um die drei Siedlungen streiten",
  "Ein Truck-Stopp, der zugleich Markt, Klinik und Gericht ist",
  "Eine Geisterstadt mit funktionierendem Netzanschluss",
  "Ein Bahndamm, entlang dessen sich eine Siedlung zieht",
  "Ein aufgegebenes Kraftwerk, in dem eine Gemeinschaft Strom abzweigt",
  "Ein Küstenstreifen voller Schiffswracks, die zerlegt werden",
  "Ein Testgelände, das seit Jahren nicht mehr genutzt und nie freigegeben wurde",
  "Eine Sperrzone um einen Reaktor, in der Menschen leben, die dorthin gehören",
  "Ein Hochplateau mit einer Antennenanlage und zwölf Bewohnern",
];

/** Historisch: Stadt, Land, Hof & Kloster, Handel & Meer, Krieg & Grenze. */
export const HISTORISCH_PLACES: string[] = [
  // Stadt
  "Eine Reichsstadt, deren Rat aus zwölf Familien besteht",
  "Ein Handwerkerviertel, in dem die Zunft strenger ist als die Obrigkeit",
  "Eine Universitätsstadt mit zweitausend Studenten und ohne Polizei",
  "Ein Judenviertel, dessen Tore bei Einbruch der Dunkelheit geschlossen werden",
  "Eine Hafenstadt, in der die Pest ausgebrochen ist und niemand es zugibt",
  "Ein Marktplatz mit Pranger, Waage und Brunnen",
  "Eine Stadt, die zwei Herren Abgaben zahlt und beide für illegitim hält",
  "Ein Gerberviertel am Unterlauf des Flusses, wo sonst niemand wohnen will",
  "Eine Festungsstadt, in der mehr Soldaten als Bürger leben",
  "Ein Viertel der Tuchhändler, in dem die Häuser fünf Stockwerke haben",
  "Eine Stadt nach dem Brand, halb wieder aufgebaut, halb Asche",
  "Ein Rathaus, in dem die Ratsprotokolle seit zwei Jahren fehlen",
  "Eine Bischofsstadt, in der weltliche und geistliche Gerichte konkurrieren",
  "Ein Armenviertel vor der Mauer, das im Krieg zuerst abgerissen wird",
  "Eine Residenzstadt, die für den Hof gebaut wurde und ohne ihn leer wäre",
  "Ein Badhaus-Viertel mit einem schlechten Ruf und guten Geschäften",
  "Eine Stadt, deren Zunftordnung Frauen ausschließt und deren Werkstätten Frauen führen",
  "Ein Quartier der Fuhrleute vor dem Stadttor",
  "Eine Messestadt, die zweimal im Jahr ihre Einwohnerzahl verdoppelt",
  "Eine Stadt unter Belagerung, in der dritte Woche",

  // Land
  "Ein Dorf, das im Dreifelderbau wirtschaftet und dessen Allmende strittig ist",
  "Ein Gutshof mit vierzig Tagelöhnern und einem abwesenden Herrn",
  "Ein Weiler in den Bergen, dessen Bewohner im Winter wandern",
  "Ein Fischerdorf, dessen Fang dem Kloster gehört",
  "Ein Bauerndorf nach drei Missernten",
  "Eine Siedlung von Neusiedlern in gerodetem Wald",
  "Ein Dorf, das gerade seinen letzten Zehnten verweigert hat",
  "Ein Weinort an einem Südhang, im Jahr einer Rekordernte",
  "Ein Marschendorf hinter einem Deich, der im Herbst brach",
  "Ein Almgebiet, in dem den Sommer über niemand die Obrigkeit sieht",
  "Ein Dorf mit einer Mühle, an der alle mahlen müssen",
  "Eine Hufe am Waldrand, seit zwei Generationen in derselben Familie",
  "Ein Dorf, in dem Vieh gestorben ist und der Verdacht umgeht",
  "Ein Weiler an einer Pilgerstraße, der vom Durchgangsverkehr lebt",
  "Ein Bergbauort, in dem der Silberertrag nachlässt",
  "Ein Dorf, dessen Bewohner alle einem Kloster gehören",
  "Eine Köhlersiedlung im Wald, drei Tagesmärsche von der nächsten Straße",
  "Ein Gestüt, das dem Landesherrn gehört und den Hafer der Umgebung frisst",
  "Ein Dorf im Grenzgebiet, das jedes Jahrzehnt die Herrschaft wechselt",
  "Ein Ort mit einer Furt, an der Zoll erhoben wird, seit niemand weiß wann",

  // Hof & Kloster
  "Ein Fürstenhof, an dem drei Parteien um die Nachfolge ringen",
  "Eine Residenz, in der der Herrscher seit Monaten nicht öffentlich auftrat",
  "Ein Kloster mit einer Bibliothek und einem Abt, der nicht hineinlässt",
  "Ein Nonnenkloster, in dem Töchter des Adels versorgt werden",
  "Ein Bischofspalast, dessen Bauherr sich verschuldet hat",
  "Ein Hoflager, das alle drei Monate weiterzieht",
  "Eine Burg, auf der eine Witwe die Herrschaft führt und dafür angefeindet wird",
  "Ein Kanzleigebäude, in dem alle Urkunden des Landes lagern",
  "Ein Kloster, das Kranke aufnimmt und dabei selbst verarmt",
  "Eine Kommende eines Ritterordens, weit von jedem Kriegsschauplatz",
  "Ein Hofgericht, das seit Jahren dieselbe Erbsache verhandelt",
  "Ein Palast mit einem Garten, für den drei Dörfer weichen mussten",
  "Ein Skriptorium, in dem an einer Chronik geschrieben wird, die schmeichelt",
  "Eine Domschule, an der Söhne aus dem ganzen Land ausgebildet werden",
  "Ein Jagdschloss, das nur sechs Wochen im Jahr benutzt wird",
  "Ein Konvent, der sich von der Ordensleitung losgesagt hat",
  "Ein Hofstaat, in dem der Kanzler mehr regiert als der Fürst",
  "Eine Abtei mit eigenem Gericht, eigener Münze und eigenem Heer",
  "Ein Sommersitz, an dem der Hof den Seuchenmonaten ausweicht",
  "Ein Kloster, dessen Reliquie Pilger anzieht und dessen Echtheit angezweifelt wird",

  // Handel & Meer
  "Ein Kontor einer auswärtigen Handelsgesellschaft, mit eigenen Privilegien",
  "Ein Hafen, in dem die Schiffe auf günstigen Wind warten, seit drei Wochen",
  "Eine Werft, an der ein Schiff für eine Reise gebaut wird, von der man nicht spricht",
  "Ein Zollhaus an einer Flussenge, das ein Drittel jeder Ladung nimmt",
  "Ein Warenlager, in dem Gewürze und Waffen nebeneinanderliegen",
  "Eine Handelsstraße durch das Gebirge, im letzten Monat vor dem Schnee",
  "Ein Umschlagplatz, an dem drei Währungen im Umlauf sind",
  "Ein Kaufmannshaus, dessen Bücher zwei Fassungen haben",
  "Eine Karawanenstation, an der Wasser teurer ist als Seide",
  "Ein Fährhaus an einem Strom, das das Monopol hat",
  "Ein Fernhandelsschiff im Hafen, mit halber Mannschaft und voller Ladung",
  "Eine Bank, die einem Fürsten Geld geliehen hat und es nicht wiedersieht",
  "Ein Sklavenmarkt in einer Hafenstadt, in der es dafür Gesetze gibt",
  "Eine Insel als Zwischenstation, deren Gouverneur seit Jahren keine Post bekam",
  "Ein Salzhandelsort, an dem die Straßen nach den Fuhrleuten benannt sind",
  "Eine Faktorei an einer fremden Küste, dreihundert Menschen weit von zu Hause",
  "Ein Leuchtturmhafen, in den man nur bei Tag einlaufen kann",
  "Ein Hansekontor, dessen Privilegien gerade aufgekündigt wurden",
  "Ein Warenhof, in dem die Fremden wohnen müssen und nicht mit Einheimischen handeln dürfen",
  "Ein Hafen, aus dem eine Flotte ausgelaufen und nicht zurückgekehrt ist",

  // Krieg & Grenze
  "Ein Feldlager im Winterquartier, mit mehr Kranken als Kämpfern",
  "Eine Grenzfeste, deren Besatzung seit acht Monaten keinen Sold sah",
  "Ein Schlachtfeld, drei Tage danach",
  "Ein Landstrich, durch den zweimal ein Heer gezogen ist",
  "Eine belagerte Stadt, in der über Übergabe verhandelt wird",
  "Ein Söldnerlager, dessen Hauptmann auf Bezahlung wartet",
  "Ein Lazarett in einer beschlagnahmten Kirche",
  "Eine Marktstadt, die als Etappenort dient und ausgeplündert wird",
  "Ein Pass, den zweihundert Mann gegen zehntausend halten sollen",
  "Ein Gebiet unter Waffenstillstand, in dem beide Seiten Vorräte sammeln",
  "Ein Dorf zwischen den Linien, das beiden Seiten liefert",
  "Eine Wachburg an einer Grenze, an der seit Jahrzehnten nichts geschah",
  "Ein Feldherrnquartier in einem requirierten Gutshaus",
  "Eine Straße voller Flüchtender, in beide Richtungen",
  "Ein Waffenplatz, an dem ein Heer aufgestellt wird",
  "Eine Festung, die man für uneinnehmbar hält und deren Brunnen versiegt",
  "Ein Grenzfluss, über den man nachts übersetzt",
  "Ein besetzter Landstrich mit einer Verwaltung, die niemand anerkennt",
  "Ein Gefangenenlager, in dem Adlige auf Lösegeld warten",
  "Ein Ort, an dem ein Friedensvertrag ausgehandelt wird und alle bewaffnet sind",
];

/** Western: Town, Ranch & Weide, Trail, Grenze, Bergbau & Eisenbahn. */
export const WESTERN_PLACES: string[] = [
  // Town
  "Eine Stadt mit einer Hauptstraße, zwei Saloons und keinem Arzt",
  "Ein Ort, dessen Sheriff vor sechs Wochen weggeritten ist",
  "Eine Kleinstadt, in der ein Rancher den Laden, die Bank und den Richter bezahlt",
  "Eine Endstation der Bahnlinie, seit einem Jahr, bis sie weitergebaut wird",
  "Ein Ort, in dem an einem Tag mehr Waffen als Menschen ankommen",
  "Eine Stadt mit einer Kirche ohne Prediger und einem Saloon mit drei",
  "Ein Grenzort, in dem zwei Sprachen gesprochen und drei Rechtsauffassungen gelebt werden",
  "Eine Stadt am Fluss, deren Fähre der einzige Übergang auf hundert Meilen ist",
  "Ein Ort, in dem seit dem Streik die Hälfte der Läden zu ist",
  "Eine Stadt, die nach einem Brand komplett neu gebaut wurde, in vier Monaten",
  "Ein Nest mit einem Telegrafenamt, das die einzige Verbindung nach draußen ist",
  "Eine Stadt, die um eine Quelle herum entstand und deren Wasserrechte strittig sind",
  "Ein Ort mit einem Friedhof, der schneller wächst als die Einwohnerzahl",
  "Eine Stadt, in der zwei Familien seit zwölf Jahren nicht miteinander sprechen",
  "Ein Handelsposten, der zugleich Post, Gericht und Schenke ist",
  "Eine Stadt mit einem neuen Hotel und keiner Nachfrage danach",
  "Ein Ort, der eine Bürgerwehr aufgestellt hat und sie nicht mehr los wird",
  "Eine Stadt, deren Bank zum dritten Mal ausgeraubt wurde",
  "Ein Ort mit einer Schule, in die vier Kinder gehen und ein Lehrer fährt",
  "Eine Stadt, in der die Viehtriebsaison begonnen hat und alles ausgebucht ist",

  // Ranch & Weide
  "Eine Ranch, die dreimal so viel Land beansprucht wie sie besitzt",
  "Ein Weidegebiet, das seit dem Stacheldraht umkämpft ist",
  "Eine Rinderfarm, deren Besitzer starb und deren Erben streiten",
  "Ein Gehöft am Ende eines Tals, mit einer Familie und vier Hunden",
  "Eine Ranch, auf der die Hälfte der Männer im Frühjahr nicht wiederkam",
  "Ein Wasserloch, um das drei Rancher prozessieren",
  "Eine Schafweide neben einer Rinderweide, mit dem üblichen Ergebnis",
  "Ein Pferdegestüt, das die Armee beliefert und dafür geschnitten wird",
  "Eine Farm, die nach zwei Dürrejahren verkauft werden soll",
  "Eine Ranch mit einem Bunkhouse voller Männer, die niemand kennt",
  "Ein Homestead, dessen Anspruch angefochten wird",
  "Ein Gehöft, das nach dem Überfall halb abgebrannt und wieder bewohnt ist",
  "Eine Weide, auf der Vieh mit fremdem Brandzeichen steht",
  "Ein Ranchhaus, in dem eine Witwe dreißig Männer beschäftigt",
  "Ein Tal, in dem sich drei Familien das Wasser einer Quelle teilen sollen",
  "Ein Winterlager der Cowhands, weit oben, mit Vorräten für zwei Monate",
  "Eine Farm mit einem neuen Brunnen, den alle Nachbarn benutzen wollen",
  "Ein Corral, in dem gerade Wildpferde eingeritten werden",
  "Ein Gehöft an der Grenze zum Reservatsland",
  "Eine Ranch, deren Grenzzaun jede Woche an derselben Stelle durchtrennt wird",

  // Trail
  "Ein Viehtriebweg, auf dem zweitausend Rinder nach Norden ziehen",
  "Eine Flussfurt, an der sich die Herden stauen",
  "Ein Wagenzug, dessen Führer die Route zum ersten Mal fährt",
  "Ein Pass, den man vor dem ersten Schnee überqueren muss",
  "Eine Postkutschenstation mit frischen Pferden und altem Streit",
  "Ein Wasserstelle, die als Einzige auf zwei Tagesritte eingezeichnet ist",
  "Ein Lagerplatz am Trail, an dem regelmäßig Vieh verschwindet",
  "Eine Salzebene, die man nur nachts durchquert",
  "Ein Canyon, durch den der Weg führt und in dem er sich verengt",
  "Ein Handelsposten mitten auf der Strecke, ohne Nachbarn",
  "Ein ausgetrocknetes Flussbett, dem man vierzig Meilen folgt",
  "Eine Brücke, die eingestürzt ist, mit einem Umweg von drei Tagen",
  "Ein Trail, auf dem sich zwei Herden begegnen und keine ausweichen will",
  "Ein Rastplatz mit Gräbern, die alle dasselbe Jahr tragen",
  "Ein Bergpfad, auf dem ein Wagen nicht wenden kann",
  "Ein Fährbetrieb, dessen Besitzer den Preis nach Ungeduld staffelt",
  "Ein Lagerfeuer am Trail, an dem drei Gruppen zusammentreffen",
  "Eine Wegkreuzung mit einem Schild, das jemand gedreht hat",
  "Ein Sturmgebiet, in dem die Herde in der Nacht durchgegangen ist",
  "Eine Quelle, die vergiftet wurde, und niemand weiß von wem",

  // Grenze & Land
  "Ein Reservat, dessen Rationslieferung seit zwei Monaten ausbleibt",
  "Ein Grenzstreifen zu Mexiko, auf dem niemandes Gesetz durchsetzbar ist",
  "Ein Armeeposten mit vierzig Soldaten und einem Offizier ohne Erfahrung",
  "Ein Indianerdorf, dessen Land gerade neu vermessen wurde",
  "Ein Vertragsgebiet, das man in diesem Jahr zum dritten Mal verkleinert hat",
  "Ein Fort an einem Fluss, das Handel treibt und Krieg vorbereitet",
  "Ein Landstrich, für den zwei Regierungen Urkunden ausgestellt haben",
  "Ein Missionsposten zwischen zwei Welten und beiden verdächtig",
  "Ein Weidegebiet, das Siedler beanspruchen und Nomaden befahren",
  "Ein Grenzfluss, über den in beide Richtungen geschmuggelt wird",
  "Ein Agenturposten, dessen Verwalter die Lieferungen selbst verkauft",
  "Ein Jagdgebiet, in dem die Bisons ausgeblieben sind",
  "Ein Übergang, an dem Zoll erhoben wird, ohne rechtliche Grundlage",
  "Ein Landvermesserlager, das seit Wochen bewacht werden muss",
  "Ein Gebiet, dem gerade der Status als Territorium zugesprochen wurde",
  "Ein Fort, das aufgegeben wurde und in dem jemand wohnt",
  "Ein Handelsplatz, an dem Waffen gegen Pelze getauscht werden",
  "Ein Dorf, das zwischen zwei Kriegsparteien neutral bleiben will",
  "Ein Landstück, das eine Eisenbahngesellschaft geschenkt bekam",
  "Ein Grenzort, in dem Gesuchte aus zwei Ländern gleichzeitig sicher sind",

  // Bergbau & Eisenbahn
  "Eine Goldgräberstadt, ein Jahr nach dem Fund und sechs Monate nach dem Höhepunkt",
  "Ein Camp am Fluss, in dem dreihundert Männer und vier Frauen leben",
  "Eine Silbermine, deren Ader schmaler wird und deren Besitzer schweigt",
  "Eine Gesellschaftsmine, die den Claim eines Einzelnen aufgekauft hat",
  "Ein Bergwerksort, dessen Wasser vom Abraum grau ist",
  "Ein aufgegebenes Camp, in dem noch drei Leute waschen",
  "Eine Streckenbaustelle der Eisenbahn, mit tausend Arbeitern und zwei Ärzten",
  "Ein Eisenbahnlager, das alle zwei Wochen weiterzieht",
  "Ein Tunnelbau durch den Berg, im vierzehnten Monat",
  "Eine Bahnstation im Nichts, mit einem Wassertank und einem Wärter",
  "Eine Boomtown, in der Claims mehr wert sind als Gold",
  "Ein Mineneingang, der nach einem Einsturz nicht wieder geöffnet wurde",
  "Ein Camp, in dem die Versorgung ausgeblieben ist und der Winter kommt",
  "Eine Erzmühle, die den ganzen Tag lärmt und den ganzen Ort ernährt",
  "Ein Ort, an dem die Bahnlinie vorbeigeführt wurde, zwei Meilen entfernt",
  "Ein Bergbaudistrikt mit einer eigenen, selbstgegebenen Rechtsordnung",
  "Ein Camp chinesischer Arbeiter, das am Ortsrand liegen muss",
  "Ein Depot mit Sprengstoff für den Streckenbau, unbewacht",
  "Eine Mine, in der es seit dem Unglück im Frühjahr spukt, sagen die Leute",
  "Ein Ort, in dem eine Eisenbahngesellschaft das Land unter den Häusern gekauft hat",
];

export const PLACES_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_PLACES,
  fantasy: FANTASY_PLACES,
  steampunk: STEAMPUNK_PLACES,
  cyberpunk: CYBERPUNK_PLACES,
  historisch: HISTORISCH_PLACES,
  western: WESTERN_PLACES,
};

/**
 * Ein Ort, passend zum Genre. Ohne bekanntes Genre fällt die Wahl auf
 * „Gegenwart" – dieselbe Regel wie in `backgrounds.ts`, und aus demselben
 * Grund wird **nie** über die Listen gemischt.
 */
export function randomPlace(genre?: string): string {
  const pool = PLACES_BY_GENRE[genre ?? ""] ?? GEGENWART_PLACES;
  return pool[Math.floor(Math.random() * pool.length)];
}
