/**
 * Zeitangaben für den Würfel am Szenario-Feld „Zeit" – **je Genre eine eigene
 * Liste zu 100 Einträgen**.
 *
 * Wie bei den Orten: nach Genre getrennt statt markiert. „Der dritte Kriegs-
 * winter" und „die Woche vor dem Börsengang" sind beide angespannte Zeiten,
 * aber sie lassen sich nicht austauschen.
 *
 * **Ein Eintrag ist eine vollständige Zeitangabe**, kein Baustein – ein
 * Szenario spielt zu einer Zeit. `randomTime` zieht deshalb genau einen.
 *
 * Die Einträge nennen möglichst **nicht nur wann, sondern wann *im Verhältnis
 * wozu***: „im dritten Jahr der Dürre" verortet eine Geschichte, „im Sommer"
 * nicht. Jahreszahlen stehen bewusst selten und nur dort, wo das Genre sie
 * trägt – ein Datum legt mehr fest, als ein Würfel entscheiden sollte.
 */

/** Gegenwart: Jahreszeiten, Wirtschaftslagen, Umbrüche, Alltagstakt. */
export const GEGENWART_TIMES: string[] = [
  // Jahreszeit & Wetter
  "Ein Spätherbst, in dem es seit drei Wochen nicht aufgehört hat zu regnen",
  "Die erste warme Woche des Jahres, alle sind draußen",
  "Ein Hochsommer mit vierzig Grad und einem Hitzewarnungserlass",
  "Die Wochen zwischen den Jahren, wenn niemand erreichbar ist",
  "Ein Februar ohne Schnee, zum vierten Mal in Folge",
  "Die Nacht der Zeitumstellung im Oktober",
  "Der erste Frost, zwei Wochen früher als sonst",
  "Ein Sommer, in dem die Flüsse Niedrigwasser führen",
  "Die Woche vor den Sommerferien, wenn nichts mehr entschieden wird",
  "Ein verregneter August, mitten in der Hauptsaison",
  "Die Tage nach dem Sturm, während die Straßen freigeräumt werden",
  "Ein Januar, in dem es nie richtig hell wird",
  "Die Karwoche, wenn halb Deutschland unterwegs ist",
  "Ein April mit Spätfrost nach der Blüte",
  "Die letzten Septembertage, wenn abends die Terrassen leer bleiben",
  "Eine Woche im Hochwasser, während die Pegel noch steigen",
  "Der erste Schultag nach den Sommerferien",
  "Ein milder Dezember, in dem die Weihnachtsmärkte im Regen stehen",
  "Die Zeit der Rübenernte, wenn die Landstraßen verstopft sind",
  "Eine Woche im März, in der alles gleichzeitig blüht",

  // Wirtschaft & Arbeit
  "Sechs Wochen nach der Ankündigung des Stellenabbaus",
  "Die Woche vor der Betriebsversammlung",
  "Ein Jahr nach der Werksschließung",
  "Mitten in der Tarifrunde, kurz vor der Urabstimmung",
  "Die Tage vor dem Quartalsabschluss",
  "Ein Monat nach der Insolvenzanmeldung, während der Betrieb weiterläuft",
  "Die Zeit, in der die Aufträge zurückgehen und noch keiner es ausspricht",
  "Zwei Wochen vor der Bilanzpressekonferenz",
  "Der Sommer, in dem die Saisonkräfte ausbleiben",
  "Ein Jahr, in dem die Mieten schneller steigen als die Löhne",
  "Die Wochen nach der Übernahme durch den neuen Eigentümer",
  "Der Monat, in dem die Energiepreise sich verdoppelt haben",
  "Kurz vor dem Rentenbeginn, mit ungeklärter Nachfolge",
  "Die Zeit zwischen Kündigung und letztem Arbeitstag",
  "Ein Frühjahr, in dem alle Handwerker ausgebucht sind",
  "Die Woche, in der die erste Rate fällig wird",
  "Ein Herbst, in dem drei Betriebe im Ort gleichzeitig suchen",
  "Die Monate nach dem Umzug der Produktion ins Ausland",
  "Kurz vor Ablauf der befristeten Verträge",
  "Die Zeit, in der die Fördermittel auslaufen und der Antrag noch läuft",

  // Umbruch & Ereignis
  "Vier Wochen vor der Kommunalwahl",
  "Die Tage nach einem Unglück, über das alle reden",
  "Ein Jahr nach der Flut, während der Wiederaufbau stockt",
  "Die Woche, in der der Prozess beginnt",
  "Zwei Monate nach dem Zuzug von dreihundert Menschen",
  "Die Zeit, in der über die Schließung der Schule entschieden wird",
  "Kurz nach der Bekanntgabe des Bauprojekts",
  "Der Herbst, in dem die Bürgerinitiative Unterschriften sammelt",
  "Die Wochen nach dem Tod des Bürgermeisters",
  "Ein Sommer voller Demonstrationen, jeden Samstag",
  "Die Tage, bevor das Gutachten veröffentlicht wird",
  "Ein Jahr nach der Fusion zweier Gemeinden",
  "Die Woche, in der die Zeitung ihr Erscheinen einstellt",
  "Kurz vor dem hundertjährigen Jubiläum des Vereins",
  "Die Zeit, in der der Umbau begonnen und das Geld ausgegangen ist",
  "Zwei Wochen nach dem Einbruch, über den niemand sprechen will",
  "Der Winter, in dem der Ort zum ersten Mal in den Nachrichten war",
  "Die Monate nach der Rückkehr von jemandem, der lange weg war",
  "Kurz nachdem das Video die Runde gemacht hat",
  "Die Tage vor dem Abriss",

  // Lebensläufe & Übergänge
  "Der Sommer nach dem Abitur, bevor irgendetwas entschieden ist",
  "Die ersten Monate mit einem Neugeborenen",
  "Das Jahr nach der Trennung, in dem noch alles geteilt wird",
  "Die Wochen, in denen die Wohnung der Eltern aufgelöst wird",
  "Der Herbst nach dem Umzug in eine fremde Stadt",
  "Ein Jahr nach der Diagnose",
  "Die Zeit zwischen Studium und erster Stelle",
  "Die Wochen vor der Hochzeit, mit allen Angehörigen im Anmarsch",
  "Der erste Winter allein im Haus",
  "Die Monate, in denen ein Elternteil gepflegt wird",
  "Kurz vor dem achtzehnten Geburtstag",
  "Die Zeit nach der Entlassung aus der Klinik",
  "Ein Jahr, in dem drei runde Geburtstage zusammenfallen",
  "Die Wochen vor der Prüfung, die über alles entscheidet",
  "Der Sommer, in dem alle Freunde wegziehen",
  "Die Tage nach der Beerdigung, wenn die Verwandtschaft wieder abreist",
  "Ein Frühjahr, in dem das Kind auszieht",
  "Die Zeit, in der der Erbstreit entschieden werden muss",
  "Kurz nach der Rückkehr aus einem Jahr im Ausland",
  "Die Monate der Sanierung, in denen man zwischen Kisten lebt",

  // Alltagstakt
  "Ein gewöhnlicher Dienstag, an dem nichts passieren sollte",
  "Die Stunden zwischen Nachtschicht und Schlaf",
  "Ein Wochenende, an dem drei Termine kollidieren",
  "Die Zeit kurz vor Ladenschluss, an einem Samstag",
  "Ein langes Wochenende, an dem der Ort voll ist",
  "Die Nachtstunden in einem Betrieb, der durchläuft",
  "Ein Montagmorgen nach einem langen Wochenende",
  "Die Stunden, in denen die Schulen aus sind und die Büros nicht",
  "Ein Freitagnachmittag, an dem alle schon weg sind",
  "Die Tage nach einem langen Feiertagswochenende",
  "Ein Sonntag, an dem im Ort nichts geöffnet hat",
  "Die frühen Morgenstunden, wenn nur die Bäckerei Licht hat",
  "Eine Woche mit Vertretung, weil die Hälfte krank ist",
  "Die Zeit um Mitternacht in einer Notaufnahme",
  "Ein Ferienmonat, in dem die halbe Stadt weg ist",
  "Die Stunden nach dem letzten Zug",
  "Ein Nachmittag im November, wenn es um vier dunkel wird",
  "Die Tage, an denen die Müllabfuhr streikt",
  "Ein Wochenende mit Volksfest, wenn alle im Ort auf den Beinen sind",
  "Die Zeit der Inventur, wenn alles stillsteht",
];

/** Fantasy: Jahreszeiten, Herrschaft, Krieg, Zeichen, Feste. */
export const FANTASY_TIMES: string[] = [
  // Jahreszeit & Land
  "Der letzte Monat vor der Ernte, wenn die Vorräte knapp werden",
  "Ein Winter, der zwei Wochen zu früh gekommen ist",
  "Die Wochen der Schneeschmelze, wenn die Wege unpassierbar sind",
  "Ein dritter Dürresommer in Folge",
  "Die Zeit der Aussaat, wenn niemand abkömmlich ist",
  "Der erste Frühling nach einem harten Winter",
  "Die dunklen Wochen um die Wintersonnenwende",
  "Ein Herbst, in dem die Ernte gut ausfiel und die Abgaben stiegen",
  "Die Regenzeit, in der drei Monate kein Wagen fährt",
  "Die Tage, an denen die Herden ins Hochland ziehen",
  "Ein Sommer, in dem die Brunnen versiegen",
  "Die Zeit des Holzeinschlags, wenn die Dörfer leer sind",
  "Ein Jahr nach der Viehseuche",
  "Die Wochen vor dem ersten Schnee, wenn die Pässe schließen",
  "Ein Frühjahr mit Hochwasser, das die Furt genommen hat",
  "Die Zeit der Wanderung, wenn fremde Züge durchs Land kommen",
  "Ein Sommer, in dem die Fische ausbleiben",
  "Die Wochen der Jagd, wenn die Herrschaft im Land unterwegs ist",
  "Ein Jahr, in dem der Wald bis an die Felder gewachsen ist",
  "Die Tage nach einem Sturm, der die Dächer genommen hat",

  // Herrschaft
  "Das erste Jahr eines Herrschers, der zu jung ist",
  "Die Wochen zwischen dem Tod des Königs und der Krönung",
  "Ein Jahr, in dem zwei Thronanwärter dasselbe Recht beanspruchen",
  "Die Zeit einer Regentschaft, die niemand für rechtmäßig hält",
  "Kurz vor dem Landtag, auf dem die Steuern beschlossen werden",
  "Die Monate, in denen der Herr abwesend ist und der Vogt regiert",
  "Ein Jahrzehnt Frieden, das alle für selbstverständlich halten",
  "Die Wochen nach der Absetzung des Statthalters",
  "Ein Jahr, in dem die Gilden mehr Macht bekommen haben als der Rat",
  "Die Zeit einer Erbteilung, bei der drei Geschwister nicht einig werden",
  "Kurz nach einem Bündnis, das niemand wollte",
  "Die Monate vor einer Hochzeit, die zwei Häuser verbinden soll",
  "Ein Jahr, in dem die Münze verschlechtert wurde",
  "Die Zeit, in der ein neues Gesetz alte Rechte aufhebt",
  "Kurz nachdem eine Stadt sich freigekauft hat",
  "Die Wochen, in denen ein Aufstand niedergeschlagen wird",
  "Ein Jahr, in dem der Herrscher nicht mehr öffentlich erscheint",
  "Die Zeit zwischen zwei Steuereintreibungen",
  "Kurz vor dem Ablauf eines Waffenstillstands",
  "Ein Jahr, in dem der alte Bund erneuert werden muss",

  // Krieg
  "Der dritte Kriegswinter",
  "Die Wochen vor dem Feldzug, wenn die Truppen gesammelt werden",
  "Ein Frühjahr, in dem beide Heere auf besseres Wetter warten",
  "Die Tage nach einer Schlacht, die keine Seite gewonnen hat",
  "Die Zeit einer Belagerung, in der vierten Woche",
  "Ein Jahr nach dem Frieden, während die Söldner noch im Land sind",
  "Die Monate, in denen Grenzscharmützel zur Gewohnheit geworden sind",
  "Kurz vor dem Ablauf des Winterquartiers",
  "Die Wochen, in denen ein Heer durch die Provinz zieht",
  "Ein Sommer, in dem die Ernte für die Truppen beschlagnahmt wird",
  "Die Zeit nach einer Niederlage, während die Nachricht durchs Land geht",
  "Kurz nach dem Fall einer Festung, die als sicher galt",
  "Die Monate, in denen Flüchtende durch die Dörfer ziehen",
  "Ein Jahr, in dem zum ersten Mal seit Generationen wieder ausgehoben wird",
  "Die Wochen vor der Entscheidung, ob eine Stadt sich ergibt",
  "Die Zeit einer Fehde zwischen zwei Häusern, im zweiten Jahr",
  "Kurz nachdem Söldner den Sold verweigert bekommen haben",
  "Ein Herbst, in dem die Heere sich zurückziehen und die Plünderer bleiben",
  "Die Tage vor einer Verhandlung, bei der beide Seiten bluffen",
  "Ein Jahr, in dem eine Grenze zum ersten Mal seit langem verschoben wurde",

  // Zeichen & Schwellen
  "Ein Jahr, in dem ein Komet am Himmel steht",
  "Die Wochen einer Sonnenfinsternis, die niemand vorhergesagt hat",
  "Die Zeit einer Seuche, in ihrem zweiten Monat",
  "Ein Jahr, das eine alte Weissagung genannt hat",
  "Die Nächte, in denen die Sterne anders stehen als in den Büchern",
  "Kurz nachdem etwas aus einem Grab verschwunden ist",
  "Die Zeit, in der Tiere die Gegend verlassen",
  "Ein Sommer, in dem der Fluss zweimal rückwärts geflossen sein soll",
  "Die Wochen, in denen die Ernte schwarz wird",
  "Kurz vor einer Konjunktion, auf die Magier gewartet haben",
  "Die Zeit, in der die alten Bäume gleichzeitig blühen",
  "Ein Jahr, in dem kein Kind im Dorf geboren wurde",
  "Die Tage nach einem Erdbeben, das etwas freigelegt hat",
  "Die Wochen, in denen die Nebel nicht mehr weichen",
  "Ein Winter, in dem das Meer bis zur Insel gefroren ist",
  "Kurz nachdem eine Quelle wieder zu fließen begonnen hat",
  "Die Zeit, in der Träume sich in mehreren Dörfern gleichen",
  "Ein Jahr nach dem Verschwinden eines ganzen Dorfes",
  "Die Nächte des längsten Mondzyklus seit Menschengedenken",
  "Kurz bevor ein Siegel abläuft, von dem nur wenige wissen",

  // Feste & Kalender
  "Die Tage des Jahrmarkts, wenn die Stadt voller Fremder ist",
  "Die Woche der Sonnenwendfeier",
  "Kurz vor dem Erntedank, wenn abgerechnet wird",
  "Die Zeit der großen Wallfahrt, wenn die Straßen voll sind",
  "Ein Fest, zu dem alle Häuser des Landes geladen sind",
  "Die Tage der Zunftprüfungen",
  "Die Nächte des Totengedenkens, in denen niemand allein geht",
  "Kurz vor dem Gerichtstag, an dem alle Fälle des Jahres verhandelt werden",
  "Die Woche, in der der Zehnte eingesammelt wird",
  "Die Zeit der Musterung, wenn die jungen Männer antreten",
  "Ein Krönungsjahr, mit Feiern und Ausgaben",
  "Die Tage vor dem Frühjahrsmarkt, wenn die Karawanen eintreffen",
  "Die Woche der Ordensprüfung, zu der Anwärter aus dem ganzen Land kommen",
  "Kurz vor dem Turnier, das seit Monaten angekündigt ist",
  "Die Zeit der Rechnungslegung, wenn die Bücher offengelegt werden",
  "Ein Jubeljahr, in dem Schulden erlassen werden sollen",
  "Die Tage der Pilgerfahrt zum Grab des Stifters",
  "Die Woche, in der neue Ratsherren gewählt werden",
  "Kurz vor der Weihe, auf die eine Stadt seit Jahren wartet",
  "Die Zeit des Vertragsschlusses, der alle sieben Jahre erneuert wird",
];

/** Steampunk: Industriezyklen, Erfindung, Ausstellung, Soziales, Verkehr. */
export const STEAMPUNK_TIMES: string[] = [
  // Industriezyklus
  "Das dritte Jahr des Aufschwungs, in dem alle bauen",
  "Die Monate nach dem Börsenkrach, während die Werke schließen",
  "Ein Winter, in dem die Kohle knapp und teuer ist",
  "Die Wochen vor der Werksübernahme durch eine größere Gesellschaft",
  "Ein Jahr, in dem die Auftragsbücher voller sind als die Werkshallen",
  "Die Zeit nach dem Kesselunglück, während die Untersuchung läuft",
  "Kurz vor der Umstellung der Fertigung auf ein neues Verfahren",
  "Die Monate, in denen die Löhne zum zweiten Mal gesenkt wurden",
  "Ein Sommer, in dem drei Werke gleichzeitig einstellen",
  "Die Woche vor der Bilanzvorlage, die niemand sehen will",
  "Ein Jahr, in dem die Rohstoffpreise sich verdoppelt haben",
  "Die Zeit der Nachtschichten, weil ein Termin nicht zu halten ist",
  "Kurz nachdem eine Konzession an einen Auswärtigen vergeben wurde",
  "Die Monate, in denen die Fabrik auf Kriegsproduktion umstellt",
  "Ein Herbst, in dem der Kanal zufriert und nichts mehr geliefert wird",
  "Die Wochen nach dem Brand in der Spinnerei",
  "Ein Jahr, in dem eine neue Maschine dreihundert Stellen ersetzt",
  "Die Zeit, in der ein Werk auf Kurzarbeit fährt",
  "Kurz bevor das Patent ausläuft, von dem alles abhängt",
  "Die Monate nach der Fusion zweier Konkurrenten",

  // Erfindung & Fortschritt
  "Das Jahr, in dem die erste Linie elektrisch beleuchtet wird",
  "Die Wochen vor der ersten öffentlichen Vorführung",
  "Kurz nachdem ein Verfahren gestohlen und andernorts angemeldet wurde",
  "Die Zeit, in der zwei Erfinder dieselbe Idee zum Patentamt tragen",
  "Ein Jahr nach dem Unglück, das die Skeptiker bestätigte",
  "Die Monate der Erprobung, bevor entschieden wird",
  "Kurz vor dem Jungfernflug",
  "Die Wochen, in denen ein Prototyp dreimal versagt hat",
  "Ein Sommer, in dem die Akademie eine neue Theorie verwirft",
  "Die Zeit, in der der Geldgeber ungeduldig wird",
  "Kurz nachdem eine Erfindung militärisches Interesse geweckt hat",
  "Die Monate vor Ablauf der Forschungsförderung",
  "Ein Jahr, in dem drei konkurrierende Systeme um den Standard ringen",
  "Die Wochen nach der Veröffentlichung, die alles infrage stellt",
  "Kurz bevor die Sicherheitsvorschrift in Kraft tritt",
  "Die Zeit, in der ein Verfahren als sicher gilt und es nicht ist",
  "Ein Jahr, in dem die ersten Automaten öffentlich vorgeführt werden",
  "Die Monate nach dem Tod des Konstrukteurs, mit unfertigen Plänen",
  "Kurz vor der Prüfung durch die Gewerbeaufsicht",
  "Die Wochen, in denen ein Versuch dreimal wiederholt werden muss",

  // Ausstellung & Öffentlichkeit
  "Drei Monate vor der Weltausstellung",
  "Die Tage der Eröffnung, wenn die halbe Welt in der Stadt ist",
  "Die Wochen nach der Ausstellung, wenn die Hallen leer stehen",
  "Kurz vor der Einweihung der neuen Bahnstrecke",
  "Die Zeit einer Gewerbeschau, auf der Aufträge vergeben werden",
  "Ein Jubiläumsjahr der Gesellschaft, mit Festumzug",
  "Die Wochen, in denen die Zeitungen von nichts anderem schreiben",
  "Kurz nach einem Vortrag, der die Stadt gespalten hat",
  "Die Tage vor dem Besuch des Fürsten im Werk",
  "Ein Jahr, in dem eine Ausstellung abgesagt werden musste",
  "Die Zeit der Grundsteinlegung für ein Bauwerk, das alles überragen soll",
  "Kurz vor der Eröffnung des Kaufhauses mit elektrischem Licht",
  "Die Wochen einer Prozessberichterstattung, die die Stadt fesselt",
  "Ein Sommer, in dem eine Zeitung eine Serie über die Fabriken bringt",
  "Die Tage nach der Enthüllung eines Denkmals, das umstritten ist",
  "Kurz vor der Abstimmung über die Straßenbahnkonzession",
  "Die Zeit, in der ein Fotograf die Arbeitersiedlung dokumentiert",
  "Ein Jahr, in dem eine Kommission die Zustände untersucht",
  "Die Wochen vor der Wahl zur Handelskammer",
  "Kurz nachdem eine Schrift verboten und deshalb gelesen wurde",

  // Soziales
  "Die zweite Woche des Streiks, wenn die Kasse leer wird",
  "Kurz vor der Aussperrung",
  "Die Monate nach dem Verbot der Versammlungen",
  "Ein Winter, in dem die Armenspeisung nicht ausreicht",
  "Die Zeit, in der über das Kinderarbeitsgesetz beraten wird",
  "Kurz nachdem ein Werksschutz auf Demonstranten geschossen hat",
  "Die Wochen, in denen eine Gewerkschaft gegründet wird",
  "Ein Jahr, in dem die Cholera durch das Fabrikviertel geht",
  "Die Monate nach der Räumung des Arbeiterviertels",
  "Kurz vor dem Prozess um den Unfall im Kesselhaus",
  "Die Zeit, in der die ersten Frauen in die Fertigung geholt werden",
  "Ein Herbst, in dem die Mieten schneller steigen als die Stundenlöhne",
  "Die Wochen nach einem Aufruf, den niemand unterschreiben will",
  "Kurz nachdem eine Werkssiedlung Wasser bekommen hat",
  "Die Zeit, in der die Zuwanderung aus dem Osten das Viertel verändert",
  "Ein Jahr, in dem eine Krankenkasse gegründet wird",
  "Die Monate, in denen Streikbrecher untergebracht werden müssen",
  "Kurz vor Inkrafttreten der Arbeitszeitverordnung",
  "Die Wochen einer Untersuchung über die Luft in der Stadt",
  "Ein Jahr, in dem das erste Werk eine Werksschule eröffnet",

  // Verkehr & Verbindung
  "Der Monat, in dem die Bahnlinie den Ort erreicht",
  "Die Wochen vor der Eröffnung des Tunnels",
  "Kurz nach dem Zugunglück auf der Neubaustrecke",
  "Die Zeit, in der eine Strecke stillgelegt wird",
  "Ein Jahr, in dem die erste Untergrundbahn fährt",
  "Die Monate, in denen der Kanal ausgebaggert wird und stillliegt",
  "Kurz vor dem ersten Linienflug des Luftschiffs",
  "Die Wochen nach dem Verlust eines Frachtluftschiffs",
  "Ein Winter, in dem die Häfen zugefroren sind",
  "Die Zeit, in der die Postkutschen eingestellt werden",
  "Kurz nachdem ein Fahrplan zum ersten Mal überregional gilt",
  "Die Monate der Streckensperrung nach dem Erdrutsch",
  "Ein Jahr, in dem die Stadt ihre erste Telegrafenverbindung bekommt",
  "Die Wochen vor der Eröffnung der Schwebebahn",
  "Kurz nach der Einführung der Einheitszeit",
  "Die Zeit, in der zwei Gesellschaften um dieselbe Trasse streiten",
  "Ein Sommer, in dem der Fluss zu wenig Wasser für die Kähne führt",
  "Die Monate, in denen die Schleuse repariert wird",
  "Kurz vor der Abnahme der neuen Eisenbahnbrücke",
  "Die Wochen, in denen die Pferdebahn durch Motoren ersetzt wird",
];

/** Cyberpunk: Konzernzyklen, Netz, Stadt, Klima, Umbruch. */
export const CYBERPUNK_TIMES: string[] = [
  // Konzern
  "Die Woche vor dem Quartalsbericht, wenn alle Zahlen frisiert werden",
  "Drei Monate nach der feindlichen Übernahme",
  "Die Zeit, in der zwei Konzerne einen offenen Kleinkrieg führen",
  "Kurz nach dem Rückruf eines Produkts, das nicht zurückgeholt werden kann",
  "Die Monate, in denen eine Abteilung abgewickelt wird",
  "Ein Jahr, in dem die Aktie fällt und die Boni steigen",
  "Die Wochen vor dem Börsengang der Tochtergesellschaft",
  "Kurz nachdem ein Vorstand verschwunden ist",
  "Die Zeit einer internen Untersuchung, die niemand überleben soll",
  "Ein Quartal, in dem der Personalabbau automatisiert wurde",
  "Die Tage nach dem Leck, das die Bilanz kostete",
  "Kurz vor Ablauf eines Exklusivvertrags",
  "Die Monate, in denen ein Konzern eine Stadt kauft",
  "Ein Jahr nach der Fusion, während zwei Kulturen sich zerreiben",
  "Die Wochen, in denen eine Produktlinie eingestellt wird",
  "Kurz nachdem eine Klage zugelassen wurde",
  "Die Zeit, in der ein Konkurrent die bessere Technik hat",
  "Ein Quartal ohne Nachschub, weil ein Zulieferer ausgefallen ist",
  "Die Tage vor der Entscheidung über den Standort",
  "Kurz nach der Kündigung von zwölftausend Verträgen an einem Tag",

  // Netz
  "Die Woche nach dem größten Datenleck seit Jahren",
  "Die Tage, in denen ein Netzabschnitt abgeschaltet ist",
  "Kurz nach der Einführung der neuen Identitätspflicht",
  "Die Monate, in denen eine Sicherheitslücke offen und bekannt ist",
  "Ein Jahr, in dem die Überwachung lückenlos wurde",
  "Die Zeit nach einem Angriff, der die Verkehrssteuerung traf",
  "Kurz bevor ein Protokoll abgeschaltet wird, auf dem alles läuft",
  "Die Wochen, in denen gefälschte Identitäten massenhaft auffliegen",
  "Ein Sommer, in dem ein Kollektiv die Konzerndaten veröffentlicht",
  "Die Tage nach dem Ausfall der Kühlung im größten Rechenzentrum",
  "Kurz nachdem ein Netzknoten privatisiert wurde",
  "Die Zeit, in der Bandbreite rationiert wird",
  "Ein Jahr, in dem Implantate zum ersten Mal ferngesperrt werden konnten",
  "Die Monate nach dem Verbot anonymer Verbindungen",
  "Kurz vor dem Auslaufen eines Softwaresupports, von dem Kliniken abhängen",
  "Die Wochen, in denen jeder zweite Account gekapert wurde",
  "Die Zeit nach einem Ausfall, den niemand erklären konnte",
  "Ein Quartal, in dem die Erinnerungsaufzeichnungen legal wurden",
  "Kurz nachdem eine KI-Zulassung zurückgezogen wurde",
  "Die Tage, in denen das Netz erstmals seit Jahren wieder ausfiel",

  // Stadt & Sicherheit
  "Die dritte Woche der Ausgangssperre",
  "Kurz nach der Räumung eines besetzten Blocks",
  "Die Monate, in denen zwei Sicherheitsfirmen um denselben Distrikt kämpfen",
  "Ein Jahr, in dem die Polizei durch einen Dienstleister ersetzt wurde",
  "Die Zeit nach den Unruhen, während die Straßen noch gesperrt sind",
  "Kurz vor der Zwangsräumung eines ganzen Viertels",
  "Die Wochen, in denen die Wasserversorgung stundenweise läuft",
  "Ein Sommer, in dem die Klimaanlagen reihenweise ausfallen",
  "Die Tage nach einem Anschlag auf ein Umspannwerk",
  "Kurz nachdem eine Bande das Viertel übernommen hat",
  "Die Monate, in denen eine Sperrzone eingerichtet wird",
  "Ein Jahr, in dem die Mordrate zum ersten Mal offiziell gesenkt wurde",
  "Die Zeit, in der die Müllabfuhr eingestellt wird",
  "Kurz vor einer Wahl, bei der nur Vertragsbürger stimmen dürfen",
  "Die Wochen nach der Ankündigung des Abrisses",
  "Ein Quartal, in dem eine Seuche im Unterviertel umgeht",
  "Die Tage, an denen das Viertel vom Netz genommen wurde",
  "Kurz nachdem eine Klinik ohne Zulassung geschlossen wurde",
  "Die Zeit, in der Lebensmittelpreise täglich neu ausgezeichnet werden",
  "Ein Winter ohne Heizung in den unteren Etagen",

  // Klima & Umwelt
  "Der dritte Monat einer Hitzewelle ohne Regen",
  "Die Wochen nach dem Sturm, der die Küstenstadt getroffen hat",
  "Ein Jahr, in dem der Pegel die Schutzmauer erreicht hat",
  "Die Zeit der Rauchsaison, wenn die Luft draußen nicht atembar ist",
  "Kurz nach dem Chemieunfall, während die Zone abgeriegelt wird",
  "Die Monate, in denen das Trinkwasser rationiert wird",
  "Ein Sommer, in dem die Ernte großflächig ausgefallen ist",
  "Die Tage der jährlichen Überflutung, die keine Ausnahme mehr ist",
  "Kurz bevor eine Küstenlinie amtlich neu gezogen wird",
  "Die Wochen nach dem Ausfall der Meerwasserentsalzung",
  "Ein Jahr, in dem der Staub die Solarfelder unbrauchbar macht",
  "Die Zeit, in der die Luftfilter in den Wohntürmen versagen",
  "Kurz nach einem Erdbeben, das die Fundamente beschädigt hat",
  "Die Monate, in denen die Kühlung eines Reaktors improvisiert wird",
  "Ein Winter ohne Frost, in dem die Schädlinge überleben",
  "Die Tage nach dem Bruch einer Abraumhalde",
  "Kurz vor der Evakuierung eines Küstenbezirks",
  "Die Zeit, in der niemand mehr ohne Maske hinausgeht",
  "Ein Jahr, in dem die Regenzeit ausgeblieben ist",
  "Die Wochen, in denen die Vögel nicht zurückgekommen sind",

  // Umbruch
  "Die Tage nach der Aufdeckung, während die Verantwortlichen noch im Amt sind",
  "Kurz vor einem Prozess, in dem ein Konzern zum ersten Mal angeklagt ist",
  "Die Monate, in denen ein neues Gesetz Implantate reguliert",
  "Ein Jahr, in dem eine Gewerkschaft zum ersten Mal wieder etwas erreicht hat",
  "Die Zeit einer Amnestie, die nur zwei Wochen gilt",
  "Kurz nachdem ein Bezirk sich für unabhängig erklärt hat",
  "Die Wochen vor einem Referendum über die Konzernverträge",
  "Ein Quartal, in dem Verträge massenhaft gekündigt werden",
  "Die Tage, an denen ein Whistleblower untergetaucht ist",
  "Kurz nach dem Zusammenbruch einer Währung",
  "Die Zeit, in der ein Konzern die Verwaltung eines Bezirks übernimmt",
  "Ein Jahr nach der Legalisierung dessen, was alle längst tun",
  "Die Monate, in denen ein Bündnis mehrerer Viertel entsteht",
  "Kurz vor der Abschaltung eines Systems, von dem Millionen abhängen",
  "Die Wochen nach einem Streik, der zum ersten Mal Wirkung zeigte",
  "Ein Sommer, in dem drei Konzerne gleichzeitig verklagt werden",
  "Die Zeit nach dem Tod eines Gründers, ohne geregelte Nachfolge",
  "Kurz nachdem eine Sperrzone offiziell aufgehoben wurde",
  "Die Tage, an denen die Konzernsicherheit den Dienst verweigert",
  "Ein Jahr, in dem zum ersten Mal jemand seinen Vertrag auflösen konnte",
];

/** Historisch: Jahreszeit, Herrschaft, Krieg, Seuche, Kalender. */
export const HISTORISCH_TIMES: string[] = [
  // Jahreszeit & Ernte
  "Der Monat vor der Ernte, wenn die alten Vorräte aufgebraucht sind",
  "Ein Winter, in dem die Flüsse zugefroren und die Mühlen still sind",
  "Die Wochen der Heuernte, wenn kein Tagelöhner zu bekommen ist",
  "Ein zweites Missjahr in Folge",
  "Die Zeit der Weinlese, wenn das ganze Tal auf den Beinen ist",
  "Ein Frühjahr, in dem der Frost nach der Blüte kam",
  "Die dunklen Monate, in denen kaum gereist wird",
  "Ein Sommer voller Gewitter, die das Getreide niederschlagen",
  "Die Wochen des Viehauftriebs",
  "Ein Herbst nach reicher Ernte, mit vollen Speichern und steigenden Abgaben",
  "Die Zeit der Schafschur",
  "Ein Jahr ohne Sommer, in dem der Himmel trüb blieb",
  "Die Monate der Schneeschmelze, wenn die Wege grundlos sind",
  "Ein Frühjahr mit Hochwasser, das die Brücke genommen hat",
  "Die Tage des Schlachtens, kurz vor dem Winter",
  "Ein Sommer der Dürre, in dem die Brunnen versiegen",
  "Die Zeit der Aussaat, wenn jede Hand gebraucht wird",
  "Ein Winter, in dem das Vieh vor der Zeit geschlachtet werden muss",
  "Die Wochen des Torfstechens",
  "Ein Jahr, in dem Heuschrecken über die Felder gingen",

  // Herrschaft & Recht
  "Das erste Regierungsjahr eines unerfahrenen Fürsten",
  "Die Monate eines Interregnums, in dem niemand zuständig ist",
  "Ein Jahr, in dem neue Steuern erhoben werden",
  "Die Wochen vor einem Landtag, auf dem alles verhandelt wird",
  "Kurz nach der Verkündung eines Edikts, das alte Rechte aufhebt",
  "Die Zeit einer Erbfolgestreitigkeit zwischen zwei Linien",
  "Ein Jahr, in dem eine Stadt ihre Privilegien bestätigt bekommt",
  "Die Monate, in denen eine Reform die Verwaltung umbaut",
  "Kurz vor einem Gerichtstag, an dem alle Fälle des Jahres verhandelt werden",
  "Die Wochen nach der Absetzung eines Amtmanns",
  "Ein Jahr, in dem die Münze verschlechtert wurde und die Preise stiegen",
  "Die Zeit einer Visitation, wenn alles überprüft wird",
  "Kurz nachdem ein Bündnis geschlossen wurde, das die Lage ändert",
  "Die Monate vor einer Fürstenhochzeit",
  "Ein Jahr, in dem eine Zunftordnung neu gefasst wird",
  "Die Wochen, in denen ein Aufstand der Bauern gärt",
  "Kurz nach der Einführung einer neuen Gerichtsordnung",
  "Die Zeit, in der Land neu vermessen und verteilt wird",
  "Ein Jahr, in dem ein Herrscher abwesend im Feld ist",
  "Die Tage vor der Huldigung, die eine Stadt verweigern könnte",

  // Krieg
  "Der dritte Kriegswinter, mit Einquartierungen in jedem Haus",
  "Die Wochen vor Beginn des Feldzugs im Frühjahr",
  "Ein Jahr, in dem beide Heere durch dieselbe Provinz zogen",
  "Die Zeit einer Belagerung, in der sechsten Woche",
  "Kurz nach einer Schlacht, während die Verwundeten in die Stadt kommen",
  "Die Monate eines Waffenstillstands, den niemand für dauerhaft hält",
  "Ein Sommer, in dem die Ernte für die Truppen beschlagnahmt wird",
  "Die Wochen nach dem Fall einer Festung",
  "Kurz vor dem Beginn von Friedensverhandlungen",
  "Die Zeit, in der die Söldner den Sold nicht bekommen haben",
  "Ein Jahr, in dem die Werbetrommel durch die Dörfer geht",
  "Die Monate, in denen Flüchtende durch das Land ziehen",
  "Kurz nach der Plünderung einer Nachbarstadt",
  "Die Wochen des Winterquartiers, wenn die Vorräte des Ortes schwinden",
  "Ein Jahr, in dem ein Frieden geschlossen und nicht gehalten wurde",
  "Die Zeit einer Fehde, die seit zwei Generationen läuft",
  "Kurz bevor eine Stadt sich zur Übergabe entschließt",
  "Die Monate nach der Rückkehr des Heeres, mit allem, was es mitbringt",
  "Ein Sommer, in dem die Straßen für Zivilisten unsicher sind",
  "Die Tage vor einer Musterung, bei der jeder Zweite gezogen wird",

  // Seuche & Not
  "Der zweite Monat einer Seuche, während die Tore geschlossen sind",
  "Die Wochen nach dem ersten Toten, als es noch niemand wahrhaben wollte",
  "Ein Jahr nach der großen Sterblichkeit, mit halber Bevölkerung",
  "Die Zeit einer Hungersnot, im dritten Monat",
  "Kurz nach einem Stadtbrand, der ein Drittel vernichtet hat",
  "Die Monate der Quarantäne, in denen kein Schiff einläuft",
  "Ein Winter, in dem in den Dörfern gebettelt wird",
  "Die Wochen, in denen Wallfahrten gegen die Seuche ziehen",
  "Kurz nachdem die Brunnen unter Verdacht geraten sind",
  "Die Zeit, in der Fremde beschuldigt werden",
  "Ein Jahr, in dem die Pest ausgeblieben ist und alle warten",
  "Die Monate nach einem Erdbeben, während neu gebaut wird",
  "Kurz nach einer Sturmflut, die den Deich genommen hat",
  "Die Wochen, in denen das Vieh reihenweise verendet",
  "Ein Sommer, in dem die Kranken vor die Stadt gebracht werden",
  "Die Zeit, in der die Leichenkarren zur Gewohnheit geworden sind",
  "Kurz nach der Aufhebung einer Sperre, die Monate galt",
  "Die Monate, in denen die Getreidepreise sich verdreifacht haben",
  "Ein Jahr, in dem der Rat die Vorräte rationiert",
  "Die Wochen nach dem Ausbruch, wenn die Wohlhabenden aufs Land ziehen",

  // Kalender & Kirche
  "Die Fastenzeit, wenn Märkte und Feiern ruhen",
  "Die Tage der Fastnacht, wenn die Ordnung ausgesetzt ist",
  "Kurz vor dem Michaelistag, an dem Pachten fällig werden",
  "Die Wochen der Messe, wenn Fremde aus drei Ländern kommen",
  "Ein Jubeljahr, in dem Pilger in Scharen unterwegs sind",
  "Die Zeit zwischen Erntedank und Advent",
  "Kurz vor dem Martinstag, wenn Gesinde neu verdingt wird",
  "Die Tage der Prozession, an denen die ganze Stadt draußen ist",
  "Ein Konzilsjahr, in dem die Kirche über sich selbst streitet",
  "Die Wochen vor der Weihe einer neuen Kirche",
  "Kurz nach der Verkündung eines Ablasses",
  "Die Zeit, in der eine Reliquie durch das Land geführt wird",
  "Ein Jahr, in dem der Kalender geändert wurde und zehn Tage fehlen",
  "Die Monate, in denen ein Bischofssitz unbesetzt ist",
  "Kurz vor einem Kirchentag, auf dem über Lehre entschieden wird",
  "Die Wochen einer Wallfahrt, wenn die Herbergen überfüllt sind",
  "Ein Jahr, in dem ein Orden reformiert wird",
  "Die Zeit der Adventswochen, wenn Handel und Recht ruhen",
  "Kurz nach der Exkommunikation eines Mächtigen",
  "Die Tage vor Ostern, wenn alle Rechnungen beglichen werden",
];

/** Western: Saison, Boom & Bust, Recht, Bahn & Grenze, Trail. */
export const WESTERN_TIMES: string[] = [
  // Saison
  "Der Frühling, wenn der Viehtrieb nach Norden beginnt",
  "Ein Hochsommer, in dem die Wasserlöcher austrocknen",
  "Die Wochen des Round-up, wenn alle Hände gebraucht werden",
  "Ein Winter, in dem der Blizzard die halbe Herde gekostet hat",
  "Die Tage vor dem ersten Schnee, wenn die Pässe schließen",
  "Ein zweites Dürrejahr in Folge",
  "Die Zeit der Kalbung, wenn niemand schläft",
  "Ein Herbst, in dem die Preise am Verladebahnhof eingebrochen sind",
  "Die Wochen der Heuernte vor dem Winter",
  "Ein Frühjahr, in dem der Fluss die Furt unpassierbar macht",
  "Die Zeit des Brandings, mit Nachbarn und alten Streitigkeiten",
  "Ein Sommer voller Präriebrände",
  "Die Monate, in denen das Vieh im Hochland steht",
  "Ein Winter, in dem die Vorräte für zwei Monate reichen müssen",
  "Die Wochen nach einem Hagelschlag, der alles genommen hat",
  "Ein Frühjahr mit Überschwemmung im Flusstal",
  "Die Zeit des Pferdezureitens, wenn die Wildherden hereingebracht werden",
  "Ein Sommer, in dem die Heuschrecken kamen",
  "Die Tage der Ernte, wenn Erntehelfer durch die Gegend ziehen",
  "Ein Herbst, in dem der erste Frost drei Wochen zu früh kam",

  // Boom & Bust
  "Sechs Wochen nach dem Goldfund, wenn täglich hundert Neue ankommen",
  "Das zweite Jahr des Booms, wenn die leichten Claims erschöpft sind",
  "Die Monate nach dem Ende des Rausches, wenn die Hälfte weggezogen ist",
  "Ein Jahr, in dem eine Gesellschaft alle Claims aufkauft",
  "Die Wochen nach dem Einsturz in der Mine",
  "Kurz nachdem die Ader dünner geworden ist und keiner es zugibt",
  "Die Zeit, in der Grundstückspreise sich monatlich verdoppeln",
  "Ein Winter, in dem die Versorgung des Camps ausgeblieben ist",
  "Die Tage nach der Nachricht von einem Fund im Nachbartal",
  "Kurz vor der Versteigerung der stillgelegten Mine",
  "Die Monate, in denen die Erzmühle rund um die Uhr läuft",
  "Ein Jahr nach dem Bankrott der Minengesellschaft",
  "Die Wochen, in denen eine Boomtown ihre erste Kirche baut",
  "Kurz nachdem der Lohn in Firmenscheinen ausgezahlt wurde",
  "Die Zeit, in der ein Camp zur Stadt erklärt wird",
  "Ein Sommer, in dem das Wasser zum Waschen knapp wird",
  "Die Tage nach dem großen Feuer, das die halbe Stadt nahm",
  "Kurz vor dem Rückzug der Gesellschaft aus dem Distrikt",
  "Die Monate, in denen die letzten Prospektoren allein zurückbleiben",
  "Ein Jahr, in dem die Stadt zum zweiten Mal neu aufgebaut wird",

  // Recht & Unrecht
  "Die Wochen nach dem letzten Banküberfall, ohne Spur",
  "Kurz nachdem der Sheriff erschossen wurde",
  "Die Zeit, in der eine Bürgerwehr die Ordnung übernommen hat",
  "Ein Monat vor dem Prozess, zu dem der Richter anreisen muss",
  "Die Tage nach einer Lynchjustiz, über die niemand spricht",
  "Kurz nach der Ankunft eines neuen Marshals",
  "Die Wochen, in denen ein Kopfgeld ausgesetzt ist",
  "Ein Jahr, in dem der Bandenkrieg zwei Familien ausgelöscht hat",
  "Die Zeit einer Amnestie für alle, die die Waffen abgeben",
  "Kurz vor einem Duell, von dem die ganze Stadt weiß",
  "Die Monate nach dem Ausbruch aus dem Gefängnis",
  "Ein Sommer, in dem drei Postkutschen überfallen wurden",
  "Die Wochen, in denen Viehdiebstahl zur Regel geworden ist",
  "Kurz nachdem ein Gesetz gegen das Tragen von Waffen erlassen wurde",
  "Die Tage vor der Hinrichtung",
  "Ein Jahr, in dem die Range War offen ausbricht",
  "Die Zeit, in der ein Detektivbüro aus dem Osten ermittelt",
  "Kurz nach der Ankunft einer Kopfgeldjägerin",
  "Die Wochen, in denen die Stadt sich zwischen zwei Kandidaten entscheidet",
  "Ein Herbst, in dem die Gesetzlosen den Winter im Ort verbringen wollen",

  // Bahn & Grenze
  "Die Monate, bevor die Bahnlinie den Ort erreicht",
  "Kurz nachdem entschieden wurde, dass die Strecke woanders verläuft",
  "Die Wochen, in denen tausend Streckenarbeiter im Ort lagern",
  "Ein Jahr, in dem die Bahngesellschaft Land aufkauft",
  "Die Zeit nach der Fertigstellung, wenn die Arbeiter weiterziehen",
  "Kurz vor der Eröffnung des Verladebahnhofs",
  "Die Monate, in denen zwei Gesellschaften um dieselbe Trasse kämpfen",
  "Ein Winter, in dem die Strecke verschneit und niemand durchkommt",
  "Die Wochen nach dem Überfall auf den Zahltagszug",
  "Kurz nachdem der Telegraf den Ort erreicht hat",
  "Die Zeit, in der die Armee einen neuen Posten errichtet",
  "Ein Jahr, in dem das Reservat verkleinert wurde",
  "Die Monate nach einem gebrochenen Vertrag",
  "Kurz vor der Ankunft eines Kommissars aus Washington",
  "Die Wochen, in denen die Rationen nicht geliefert wurden",
  "Ein Sommer, in dem die Bisonherden ausgeblieben sind",
  "Die Zeit, in der Siedler auf Vertragsland ziehen",
  "Kurz nach einem Gefecht, das keine Seite gemeldet hat",
  "Die Monate, in denen ein Fort geräumt wird",
  "Ein Jahr, in dem das Territorium Staat werden soll",

  // Trail & Unterwegs
  "Die vierte Woche auf dem Trail, wenn die Vorräte knapp werden",
  "Kurz vor der Flussüberquerung bei Hochwasser",
  "Die Tage, nachdem die Herde in der Nacht durchgegangen ist",
  "Ein Abschnitt ohne Wasser, mit zwei Tagesritten vor sich",
  "Die Zeit, in der zwei Herden auf demselben Weg sind",
  "Kurz nachdem der Trailboss krank geworden ist",
  "Die Wochen, in denen ein Wagenzug zu spät im Jahr aufgebrochen ist",
  "Ein Sommer, in dem die Fährgebühren verdoppelt wurden",
  "Die Tage vor dem Pass, wenn das Wetter umschlägt",
  "Kurz nachdem der Führer sich verirrt hat und es nicht zugibt",
  "Die Zeit, in der die Pferde lahmen und der Ersatz fehlt",
  "Ein Herbst, in dem die letzten Züge vor dem Winter durchmüssen",
  "Die Wochen nach dem Verlust der Ochsen",
  "Kurz vor Erreichen der Verladestation, mit müder Mannschaft",
  "Die Tage, an denen Fremde dem Zug folgen",
  "Ein Frühjahr, in dem die Prärie nach dem Brand kahl ist",
  "Die Zeit, in der die Nächte kalt und die Tage zu heiß sind",
  "Kurz nachdem am Lagerplatz Vieh gefehlt hat",
  "Die Wochen, in denen jeder Tag zwanzig Meilen bringen muss",
  "Ein Sommer, in dem die Quellen entlang der Route versiegt sind",
];

/** Science Fiction: Bordzeit, Kolonie-Kalender, Verträge, Krisen, Technik, Bahnen. */
export const SCIFI_TIMES: string[] = [
  // Bordzeit & Reise
  "Der siebte Monat einer Überfahrt, die für fünf geplant war",
  "Die letzte Woche vor dem Sprung, wenn alles festgezurrt wird",
  "Die Tage nach dem Aufwachen aus dem Kälteschlaf, wenn niemand geradeaus geht",
  "Das dritte Jahr einer Reise ohne Zwischenhalt",
  "Die Stunden vor dem Bremsmanöver, wenn nichts mehr zu korrigieren ist",
  "Die Wache zwischen zwei und sechs, wenn nur zwei Leute wach sind",
  "Der Tag, an dem die Sichtweite zum ersten Mal bis ins Zielsystem reicht",
  "Die Wochen im Anflug, wenn die Antwortzeiten unter eine Stunde fallen",
  "Ein Umlauf nach dem Andocken, während die Zollformalitäten laufen",
  "Die Nacht vor dem Auslaufen, wenn die Verträge unterschrieben sind",
  "Der zweite Monat einer Quarantäne an Bord",
  "Die Zeit zwischen zwei Versorgungsflügen, sechzig Tage lang",
  "Der Umstieg auf Notrationen, drei Wochen vor dem geplanten Ziel",
  "Die Tage, in denen die Rotation abgeschaltet ist und alles schwebt",
  "Die Schicht, in der die Ablösung ausbleibt",
  "Der Rückflug, für den der Treibstoff nur noch einen Kurs zulässt",

  // Kolonie & Kalender
  "Das erste Jahr nach der Landung, wenn noch alles improvisiert ist",
  "Der zwanzigste Jahrestag der Gründung, den kaum jemand feiert",
  "Die lange Nacht eines Planeten, die vierzig Tage dauert",
  "Die Wochen vor dem Wechsel der Verwaltung",
  "Das Ende eines Zehnjahresvertrags, den die Hälfte nicht verlängern will",
  "Der Sommer, in dem die erste eigene Ernte reifte",
  "Die Jahreszeit, in der der Staub kommt und niemand nach draußen geht",
  "Das dritte Jahr ohne Nachschub",
  "Die Tage vor dem Zensus, wenn manche verschwinden",
  "Das Jahr, in dem mehr Kinder hier geboren als von außen angekommen sind",
  "Die Zeit kurz nach der Umstellung auf die Ortszeit, die niemand im Körper hat",
  "Der Winter, in dem die Kuppel zum ersten Mal geflickt werden musste",
  "Die Wochen vor der Abstimmung über die Unabhängigkeit",
  "Das Jahrzehnt, in dem die Gründergeneration wegstirbt",
  "Die Monate, in denen die Terraforming-Werte zum ersten Mal fallen",
  "Die Zeit nach dem Beben, als die Bohrstadt sich neu sortierte",

  // Politik & Verträge
  "Die Wochen vor Ablauf eines Waffenstillstands",
  "Das Jahr nach einem Krieg, den beide Seiten gewonnen haben wollen",
  "Die Zeit zwischen einem Vertragsschluss und seiner Ratifizierung",
  "Die Monate, in denen zwei Regierungen dasselbe System beanspruchen",
  "Der Tag, an dem die Zölle erhöht wurden, und die Wochen danach",
  "Die Zeit der Musterung, wenn jeder Jahrgang durchgezählt wird",
  "Die Wochen vor einer Inspektion, die alle drei Jahre kommt",
  "Das Jahr, in dem der Konzern die Verwaltung übernahm",
  "Die Übergangszeit, in der zwei Rechtsordnungen gleichzeitig gelten",
  "Die Monate nach dem Rückzug der Flotte",
  "Die Zeit, in der ein Prozess läuft, dessen Ausgang alles verschiebt",
  "Die Wochen nach der Aufhebung der Reisebeschränkungen",
  "Das letzte Jahr eines Handelsabkommens",
  "Die Tage, an denen der Notstand zum vierten Mal verlängert wird",
  "Die Zeit vor einer Wahl, die zum ersten Mal stattfindet",
  "Die Monate, in denen die Grenzziehung neu verhandelt wird",

  // Versorgung & Krisen
  "Die Wochen nach einem Leck, das niemand zugegeben hat",
  "Die Zeit der Rationierung, wenn die Reserven angebrochen werden",
  "Die Tage nach einem Reaktorstillstand, im Halbdunkel",
  "Die Monate, in denen die Filter erneuert werden müssten",
  "Der Winter, in dem die Wärmezuteilung halbiert wurde",
  "Die Wochen einer Seuche, die noch keinen Namen hat",
  "Die Zeit nach dem Ausfall der Fernverbindung",
  "Die Tage der Evakuierung, als die Schiffe nicht für alle reichten",
  "Die Monate nach dem Absturz, während die Untersuchung lief",
  "Die Wochen, in denen das Wasser rationiert wurde und niemand sagte, wie lange",
  "Die Zeit unmittelbar vor einem Sturm, den die Modelle unterschätzen",
  "Die Tage nach dem Streik in der Aufbereitung",
  "Die Monate, in denen die Luftqualität täglich veröffentlicht wird",
  "Die Zeit, in der ein Vorposten nicht mehr antwortet",
  "Die Wochen nach einer Explosion, deren Ursache offen ist",
  "Die Tage vor dem Einschlag eines Trümmerstücks, dessen Bahn bekannt ist",

  // Technik & Wandel
  "Das Jahr, in dem die erste Gerätegeneration vollständig ersetzt wurde",
  "Die Monate nach der Freigabe einer Technik, die vorher verboten war",
  "Die Zeit, in der die alten Systeme abgeschaltet und die neuen nicht fertig sind",
  "Die Wochen, in denen Automaten die Schichten übernahmen",
  "Das Jahrzehnt nach der Entdeckung des Sprungtors",
  "Die Tage nach einem Fehler in der Steuerung, der zwei Docks lahmlegte",
  "Die Zeit, bevor eine Bauart aus dem Verkehr gezogen wird",
  "Die Monate, in denen Prothesen billiger wurden als Behandlungen",
  "Das Jahr, in dem eine künstliche Intelligenz zum ersten Mal Rechtsstatus beantragte",
  "Die Wochen nach einem Signal, das nicht von Menschen stammt",
  "Die Zeit, in der zwei Kalender parallel geführt werden",
  "Die Monate nach der Umstellung auf ein neues Antriebsmuster",
  "Die Tage, in denen eine Aktualisierung ausgerollt wird, die niemand geprüft hat",
  "Die Zeit nach dem Verbot des Kälteschlafs für Zivilisten",
  "Das Jahr, in dem die letzte Werft im System schloss",
  "Die Wochen, in denen der Handel auf ein anderes Zahlungssystem umstellt",

  // Bahnen & Jahrestage
  "Die Konjunktion zweier Monde, die alle elf Jahre den Verkehr stilllegt",
  "Die Passage durch einen Strahlungsgürtel, drei Tage unter Deck",
  "Die Zeit des Ringschattens, wenn es tagsüber dunkel wird",
  "Die Wochen, in denen das Zielsystem hinter der Sonne steht und der Funk schweigt",
  "Der Sonnensturm, der alle sieben Jahre erwartet wird",
  "Die Tage vor einem Kometendurchgang, den drei Sekten verschieden deuten",
  "Die Zeit, in der der Planet seinem Stern am nächsten steht",
  "Die Nächte, in denen man die Station von unten sehen kann",
  "Die Monate, in denen die Umlaufbahn korrigiert werden muss",
  "Die zwei Wochen, in denen der Sprungpunkt offen steht",
  "Der Jahrestag eines Unglücks, an dem alle Sirenen getestet werden",
  "Die Woche der Vertragsbörse, wenn alle Arbeitsverhältnisse neu vergeben werden",
  "Die Tage nach der Ankunft eines Schiffs, das überfällig war",
  "Die Zeit des Generationswechsels an Bord, wenn die Ämter neu besetzt werden",
  "Die Monate, in denen ein Gerichtsverfahren die Kolonie spaltet",
  "Die Wochen vor der Ankunft der Inspektoren aus der Heimat",
  "Das erste Jahr, in dem niemand an Bord die Erde mehr gesehen hat",
  "Die Zeit nach der letzten Nachricht von zu Hause, elf Jahre alt",
  "Die Tage, an denen die Kuppel geöffnet werden darf",
  "Die Stunden vor einem Andockmanöver, für das es nur einen Versuch gibt",
];

/** Märchen: Jahreslauf, Fristen, Notzeiten, Herrschaft, Zauber, Menschenleben. */
export const MAERCHEN_TIMES: string[] = [
  // Jahreszeit & Land
  "Der letzte Abend vor der ersten Frostnacht",
  "Ein Winter, der so lang wurde, dass das Brennholz gezählt wird",
  "Die Woche der Ernte, in der jede Hand gebraucht wird",
  "Die zwölf Nächte zwischen den Jahren",
  "Ein Frühling, in dem der Schnee liegen blieb, als er gehen sollte",
  "Die Zeit der Heuernte, wenn nachts niemand im Haus ist",
  "Ein Sommer ohne einen einzigen Regentag",
  "Die Wochen vor der Aussaat, wenn das Korn knapp wird",
  "Der erste Schnee, drei Wochen zu früh",
  "Ein Herbst, in dem die Bäume zweimal trugen",
  "Die Tage, an denen das Vieh von der Alm kommt",
  "Ein Jahr, in dem der Fluss zweimal über die Ufer trat",
  "Die Nacht vor dem längsten Tag",
  "Die dunkelste Woche des Jahres",
  "Ein Frühjahr nach drei Missernten",
  "Die Wochen, in denen die Wege im Schlamm versinken",

  // Feste & Fristen
  "Der Abend vor der Hochzeit, an dem noch alles rückgängig zu machen wäre",
  "Die drei Tage eines Festes, das alle sieben Jahre gefeiert wird",
  "Die Nacht vor dem Gerichtstag",
  "Die Woche vor Ablauf einer Frist, die vor einem Jahr gesetzt wurde",
  "Der letzte Tag, an dem ein Versprechen noch eingelöst werden kann",
  "Die Zeit des Jahrmarkts, wenn Fremde im Dorf sind",
  "Der Tag der Musterung, an dem die Söhne gezählt werden",
  "Die Nacht der Sonnenwende, in der man nicht schlafen soll",
  "Die Woche, in der die Abgaben fällig werden",
  "Der Morgen nach einer Nacht, über die niemand spricht",
  "Die drei Tage Trauer, ehe das Erbe geteilt wird",
  "Die Zeit zwischen dem Antrag und der Antwort",
  "Der Vorabend einer Krönung, die niemand wollte",
  "Die Wochen, in denen die Braut gesucht wird",
  "Der siebte Tag einer Wette",
  "Die Nacht, in der ein Fluch ausläuft oder nicht",

  // Notzeiten
  "Das dritte Jahr einer Dürre",
  "Der Winter nach dem Krieg, als die Männer fehlten",
  "Die Wochen, in denen die Wölfe bis an die Höfe kommen",
  "Ein Jahr, in dem die Seuche die Nachbardörfer nahm und dieses ausließ",
  "Die Zeit, in der die Abgaben verdoppelt wurden",
  "Die Monate, in denen kein Händler mehr durchkam",
  "Der Sommer, in dem der Brunnen versiegte",
  "Die Tage nach einem Brand, der die halbe Gasse nahm",
  "Die Zeit, in der man das Saatgut aufaß",
  "Die Wochen einer Belagerung, die niemand ernst nimmt",
  "Das Jahr, in dem die Herde einging",
  "Die Zeit, in der die Kinder eines nach dem anderen krank wurden",
  "Die Tage nach dem Hochwasser, als die Grenzsteine fehlten",
  "Der Herbst, in dem eingezogen wurde, bevor geerntet war",
  "Die Wochen, in denen der Wald näher kam",
  "Der Winter, in dem drei Höfe leer standen",

  // Herrschaft & Zeitalter
  "Das erste Jahr eines Königs, der noch ein Kind ist",
  "Die Zeit, in der zwei Brüder um dieselbe Krone streiten",
  "Das letzte Jahr eines alten Herrn ohne Erben",
  "Die Wochen zwischen dem Tod des Königs und der Wahl des nächsten",
  "Ein Zeitalter, in dem die Wunder seltener werden",
  "Die Jahre, in denen die Riesen zuletzt gesehen wurden",
  "Die Zeit nach dem letzten Drachen",
  "Ein Jahrhundert, das seine Grenzen dreimal verschoben hat",
  "Die Regierungszeit einer Königin, die nie das Schloss verlässt",
  "Die Jahre, in denen das Reich befriedet gilt und niemand reist",
  "Die Zeit kurz nach einem Vertrag zwischen Menschen und dem Volk unter dem Hügel",
  "Ein Jahr des Aufruhrs, in dem die Ordnung gerade noch hält",
  "Die Zeit, in der ein neuer Glaube die alten Feste verbietet",
  "Die Wochen vor der Ankunft eines fremden Gesandten",
  "Ein Zeitalter, dessen Anfang niemand mehr benennen kann",
  "Die Jahre, in denen die Wege wieder sicher wurden",

  // Verzauberte Zeit
  "Die hundert Jahre eines Schlafs, im siebten Jahrzehnt",
  "Die Zeit, in der draußen ein Tag vergeht und drinnen ein Jahr",
  "Der Tag, der sich seit drei Wochen wiederholt",
  "Die Frist eines Zaubers, von der noch ein Winter bleibt",
  "Die Stunde vor Mitternacht, in der etwas endet",
  "Die Jahre, die jemand fort war und die man ihm nicht ansieht",
  "Die Zeit zwischen zwei Vollmonden, in der ein Wort nicht fallen darf",
  "Der siebte Tag nach einer Verwandlung",
  "Die drei Jahre, die eine Prüfung dauert",
  "Ein Sommer, der nicht enden will",
  "Die Nacht, die im ganzen Land zweimal gezählt wird",
  "Die Zeit, in der die Uhren im Schloss stillstehen",
  "Die Jahre, in denen niemand im Ort altert",
  "Der Winter, der jedes Jahr eine Woche früher beginnt",
  "Die Frist von einem Jahr und einem Tag, im elften Monat",
  "Die Zeit, seit der die Vögel nicht mehr singen",
  "Die Nächte, in denen der Hügel offen steht",
  "Der Morgen, an dem etwas zurückkommt, das lange fort war",

  // Menschenleben
  "Das Jahr, in dem das jüngste Kind das Haus verlässt",
  "Die Wochen nach der Geburt eines Erben, auf den man nicht mehr hoffte",
  "Die Zeit, in der ein Kind zum ersten Mal allein in den Wald darf",
  "Die Tage, ehe die Lehre beginnt",
  "Der Herbst, in dem die Alte im Dorf zu sterben anfing",
  "Die Zeit kurz nach dem Tod eines Vaters, bevor das Erbe geteilt ist",
  "Die Wochen vor einer Reise, von der man nicht wiederkommt",
  "Das Jahr, in dem die drei Töchter alle heiratsfähig wurden",
  "Die Zeit, in der ein Sohn zurückerwartet wird und ausbleibt",
  "Die Tage nach einer Rückkehr, die niemand erwartet hatte",
  "Die Wochen, in denen sich entscheidet, wer den Hof bekommt",
  "Der Winter, in dem der Vater zu alt für die Arbeit wurde",
  "Die Zeit, in der ein Findelkind ins Alter der Fragen kommt",
  "Die Tage vor einer Abreise, die als Strafe gilt",
  "Das Jahr, in dem der Älteste ging und der Jüngste blieb",
  "Die Wochen nach einer Hochzeit, die keiner wollte",
  "Die Zeit, in der ein Versprechen alt genug ist, eingefordert zu werden",
  "Die Nacht, in der jemand zum letzten Mal fortgeht",
];

/** Superhelden: nach dem Vorfall, Anfänge, Recht, Stimmung, Alltag, Zuspitzung. */
export const SUPERHELDEN_TIMES: string[] = [
  // Nach dem Vorfall
  "Die Wochen nach einem Ereignis, das die Stadt in zwei Zeiten teilt",
  "Der erste Jahrestag, an dem noch offen ist, ob gefeiert oder getrauert wird",
  "Die Tage, in denen die Trümmer noch nicht geräumt sind",
  "Der Monat, in dem die Versicherungen die Zahlungen einstellten",
  "Die Zeit, in der die Vermisstenlisten noch nicht endgültig sind",
  "Die Wochen einer Untersuchungskommission, deren Bericht nie erscheint",
  "Die Tage nach einer Rettung, die drei Häuserblocks gekostet hat",
  "Der Wiederaufbau im zweiten Jahr, wenn das Geld ausgeht",
  "Die Zeit, in der die Notunterkünfte geräumt werden sollen",
  "Die Wochen nach dem ersten Todesfall, den niemand jemandem zuordnen kann",
  "Der Sommer, in dem zum dritten Mal evakuiert wurde",
  "Die Tage, an denen die Innenstadt noch gesperrt ist",
  "Die Zeit kurz vor dem Prozess, der alles aufarbeiten soll",
  "Die Wochen, in denen die Stadt lernt, wieder U-Bahn zu fahren",
  "Der Monat, in dem die Spendenkampagne ins Stocken gerät",
  "Die Zeit nach einer Katastrophe, die andernorts größer war",
  "Die Tage, an denen die Kameras abziehen und die Arbeit bleibt",
  "Die Wochen, in denen die Schuldfrage öffentlich verhandelt wird",

  // Anfang & Auftauchen
  "Das Jahr, in dem zum ersten Mal jemand über die Dächer sprang",
  "Die Wochen nach dem ersten Video, das echt aussieht",
  "Die Zeit, in der noch alle glauben, es sei ein Werbetrick",
  "Die Monate, in denen jede Stadt ihren eigenen bekommt",
  "Der Sommer, in dem sich die Zahl derer, die etwas können, verdoppelte",
  "Die Tage nach einem Unfall, aus dem drei Leute anders herauskamen",
  "Die Zeit, in der die ersten Kinder mit Fähigkeiten eingeschult werden",
  "Die Wochen, in denen das Wort dafür noch gesucht wird",
  "Das Jahrzehnt, in dem alles anfing, aus heutiger Sicht",
  "Die Zeit unmittelbar vor der ersten öffentlichen Enttarnung",
  "Die Monate, in denen niemand weiß, ob es einer ist oder viele",
  "Die Tage nach dem ersten Auftritt bei Tageslicht",
  "Die Zeit, in der es noch keine Kostüme gab, nur Masken",
  "Die Wochen, in denen die erste Gruppe sich zusammentat",
  "Der Winter, in dem die Gerüchte zum ersten Mal Namen bekamen",
  "Die Zeit, in der die Universitäten anfingen, das ernst zu nehmen",

  // Recht & Politik
  "Die Wochen vor einer Abstimmung über die Registrierungspflicht",
  "Die Zeit, in der ein Gesetz gilt, aber niemand es durchsetzt",
  "Die Monate nach der Auflösung der Sondereinheit",
  "Die Tage vor einem Urteil, das Präzedenz schaffen wird",
  "Das Jahr, in dem die Stadt einen Vertrag mit Freiwilligen schloss",
  "Die Wochen, in denen der Notstand zum vierten Mal verlängert wird",
  "Die Zeit vor einer Wahl, in der beide Lager dasselbe versprechen",
  "Die Monate nach dem Rücktritt eines Bürgermeisters",
  "Die Tage, an denen zwei Behörden einander blockieren",
  "Die Zeit einer Anhörung, in der Namen fallen sollen",
  "Die Wochen, in denen eine Amnestie ausläuft",
  "Das Jahr, in dem ein Konzern die Stadtwerke übernahm",
  "Die Zeit, in der ein Haftbefehl gegen einen Retter läuft",
  "Die Monate, in denen Polizei und Freiwillige nicht mehr miteinander sprechen",
  "Die Tage nach der Aufhebung einer Ausgangssperre",
  "Die Wochen, in denen ein Denkmal auf- oder abgebaut werden soll",
  "Die Zeit, in der ein Ausschuss Akten anfordert, die es nicht gibt",
  "Die Monate vor der Räumung einer Sperrzone",

  // Öffentlichkeit & Stimmung
  "Die Wochen, in denen die Stimmung kippt und niemand weiß, wodurch",
  "Die Zeit, in der jeder eine Meinung hat und keiner eine Erinnerung",
  "Die Tage nach einer Titelgeschichte, die zu viel verriet",
  "Die Monate, in denen die Einschaltquoten von Katastrophen leben",
  "Ein Wahlkampf, in dem Sicherheit das einzige Thema ist",
  "Die Zeit, in der Kinder in Kostümen zur Schule gehen",
  "Die Wochen einer Kampagne, die zu Anzeigen aufruft",
  "Die Tage, an denen zum ersten Mal jemand ausgebuht wird",
  "Die Zeit, in der die Werbeverträge mehr wert sind als die Taten",
  "Die Monate, in denen ein Podcast die Ermittlungen überholt",
  "Die Wochen, in denen eine Gedenkfeier zur Demonstration wird",
  "Die Zeit nach einem Interview, das falsch verstanden wurde",
  "Die Tage, an denen die Stadt zwei Helden hat und sich entscheiden soll",
  "Die Wochen, in denen die Zahl der Nachahmer steigt",
  "Die Zeit, in der Umfragen zeigen, dass die Mehrheit Angst hat",
  "Die Monate, in denen alle darauf warten, dass etwas passiert",

  // Alltag & Jahreslauf
  "Eine Hitzewelle, in der das Stromnetz an der Grenze läuft",
  "Die Woche vor Weihnachten, wenn die Innenstadt voll ist",
  "Ein Herbst mit drei Streiks gleichzeitig",
  "Die Nacht der großen Parade",
  "Der Tag eines Endspiels, an dem die halbe Stadt im Stadion sitzt",
  "Ein verregneter Frühling, in dem die Kriminalität sinkt",
  "Die Wochen des Semesterbeginns, wenn die Stadt jünger wird",
  "Ein Silvester, an dem die Feuerwehr doppelt besetzt ist",
  "Die Tage vor einem angekündigten Sturm",
  "Die Ferienzeit, in der die Bürotürme leer stehen",
  "Die Nächte einer Hitzeperiode, in denen niemand schläft",
  "Die Wochen vor einem Gipfeltreffen in der Stadt",
  "Der Monatsanfang, wenn die Mieten fällig werden",
  "Die Zeit der Baumesse, wenn die Kräne kommen",
  "Ein Winter mit zu wenig Streusalz",
  "Die Nacht, in der der Strom für sechs Stunden ausfiel",

  // Zuspitzung
  "Die Stunden, in denen ein Ultimatum läuft",
  "Die Nacht vor einer angekündigten Enthüllung",
  "Die Tage, an denen jemand vermisst wird, den man nicht vermissen darf",
  "Die Wochen, in denen ein alter Fall neu aufgerollt wird",
  "Die Zeit, in der zwei Banden dieselbe Straße beanspruchen",
  "Die Tage vor einem Transport, dessen Route bekannt geworden ist",
  "Die Stunden nach einem Ausbruch aus dem Hochsicherheitstrakt",
  "Die Wochen, in denen jemand einen nach dem anderen findet",
  "Die Zeit, in der Erpresserbriefe eingehen und niemand reagiert",
  "Die Nacht einer Bombendrohung, die ernst genommen wird",
  "Die Tage, an denen die Funkfrequenzen der Polizei gestört sind",
  "Die Wochen vor dem Ablauf einer Frist, die jemand gesetzt hat",
  "Die Zeit, in der ein Verräter in den eigenen Reihen gesucht wird",
  "Die Stunden, in denen die Stadt evakuiert werden müsste und es nicht tut",
  "Die Tage nach einer Warnung, die niemand ernst nahm",
  "Die Nacht, in der zum ersten Mal jemand nicht zurückkommt",
];

export const TIMES_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_TIMES,
  fantasy: FANTASY_TIMES,
  steampunk: STEAMPUNK_TIMES,
  cyberpunk: CYBERPUNK_TIMES,
  historisch: HISTORISCH_TIMES,
  western: WESTERN_TIMES,
  scifi: SCIFI_TIMES,
  maerchen: MAERCHEN_TIMES,
  superhelden: SUPERHELDEN_TIMES,
};

/** Eine Zeitangabe, passend zum Genre. Ohne bekanntes Genre: „Gegenwart". */
export function randomTime(genre?: string): string {
  const pool = TIMES_BY_GENRE[genre ?? ""] ?? GEGENWART_TIMES;
  return pool[Math.floor(Math.random() * pool.length)];
}
