/**
 * Regeln für den Würfel am Szenario-Feld „Regeln" – **je Genre eine eigene
 * Liste zu 100 Einträgen**.
 *
 * Anders als bei Ort und Zeit wird hier **kombiniert**: ein Szenario hat nicht
 * eine Regel, sondern mehrere, und erst ihr Zusammentreffen ergibt eine Welt.
 * `randomRules` zieht deshalb **zwei bis drei** ohne Wiederholung.
 *
 * Jeder Eintrag ist ein **vollständiger Satz im Präsens**, der etwas behauptet,
 * das für alle im Szenario gilt. Kein Weltbaustein zum Weiterdenken, sondern
 * eine Festlegung, an der sich Figuren reiben können: „Wer hier ohne Bürgen
 * ankommt, bekommt keine Arbeit" ist eine Regel, „es gibt Bürgen" nicht.
 *
 * Die Sätze sind bewusst so geschrieben, dass sie **nebeneinander stehen
 * können**, ohne sich zu widersprechen: keine Zahlen, keine Eigennamen, keine
 * Aussagen über die Regierungsform, die eine zweite gezogene Regel aushebeln
 * könnte. Deshalb steht hier auch nichts über Ort oder Zeit – dafür gibt es
 * die anderen beiden Felder.
 */

import { pickSome } from "./inspiration";

/** Gegenwart: Geld, Arbeit, Nachbarschaft, Behörden, Ungeschriebenes. */
export const GEGENWART_RULES: string[] = [
  // Geld & Arbeit
  "Wer hier keinen unbefristeten Vertrag hat, bekommt keine Wohnung.",
  "Fast alle im Ort hängen an einem einzigen Arbeitgeber, auch die, die es bestreiten.",
  "Über Gehälter wird nicht gesprochen, nicht einmal unter Freunden.",
  "Wer kündigt, muss wegziehen – zweite Chancen gibt es hier nicht.",
  "Die guten Stellen werden vergeben, bevor sie ausgeschrieben sind.",
  "Nebenbei zu arbeiten ist normal und wird von allen verschwiegen.",
  "Wer Schulden hat, verliert seinen Stand, egal wie er sie bekam.",
  "Die Mieten steigen schneller, als jemand hier verdienen kann.",
  "Wer ein Haus erbt, bleibt; wer keines erbt, geht.",
  "Bar zu zahlen gilt als verdächtig, jedenfalls über bestimmte Beträge.",
  "Zwei Jobs zu haben ist hier keine Ausnahme, sondern die Voraussetzung.",
  "Wer von auswärts kommt, zahlt für alles mehr.",
  "Das Geld im Ort gehört drei Familien, und alle wissen welchen.",
  "Sich krankzumelden kostet mehr als die Krankheit.",
  "Wer den Betrieb kritisiert, findet danach keine Arbeit mehr in der Branche.",

  // Nachbarschaft & Gemeinschaft
  "Jeder weiß über jeden Bescheid, aber niemand spricht es aus.",
  "Wer nicht im Verein ist, gehört nicht dazu.",
  "Hilfe wird geleistet, aber nie erbeten – wer fragt, hat verloren.",
  "Streit wird ausgesessen, nicht ausgetragen.",
  "Wer weggezogen ist und zurückkommt, bleibt für immer der Weggezogene.",
  "Über Politik wird beim Essen nicht geredet, über Geld nie.",
  "Neuzugezogene brauchen zehn Jahre, bis sie mitreden dürfen.",
  "Was in der Familie passiert, bleibt in der Familie, auch das Schlimme.",
  "Wer die Polizei ruft, hat die Regeln gebrochen, nicht der andere.",
  "Man grüßt jeden, auch die, mit denen man nicht spricht.",
  "Nachbarschaftshilfe wird über Jahre aufgerechnet, ohne dass jemand Buch führt.",
  "Wer sich absondert, gilt als hochnäsig, nicht als schüchtern.",
  "Beerdigungen sind Pflicht, Hochzeiten sind Politik.",
  "Auf offener Straße wird nicht geweint.",
  "Die alten Streitigkeiten werden vererbt, ob man will oder nicht.",

  // Behörden & Verfahren
  "Alles geht seinen Weg, aber jeder Weg dauert Monate.",
  "Wer die richtigen Formulare kennt, bekommt, was anderen verweigert wird.",
  "Zuständigkeiten sind so verteilt, dass am Ende niemand zuständig ist.",
  "Widerspruch lohnt sich fast immer und wird fast nie eingelegt.",
  "Wer kein Deutsch spricht, braucht jemanden, der mitkommt.",
  "Fristen sind absolut, auch wenn der Bescheid zu spät zugestellt wurde.",
  "Was nicht digital erfasst ist, existiert für die Verwaltung nicht.",
  "Kontrollen finden statt, aber nur dort, wo sie einfach sind.",
  "Wer einen Anwalt bezahlen kann, bekommt ein anderes Verfahren.",
  "Anträge werden zuerst abgelehnt, das gehört zum Ablauf.",
  "Die Regeln sind für alle gleich und werden für manche ausgelegt.",
  "Ohne Meldeadresse gibt es nichts: kein Konto, keine Arbeit, keine Hilfe.",
  "Was einmal aktenkundig ist, verschwindet nicht mehr.",
  "Ehrenamtliche halten hier aufrecht, wofür eigentlich der Staat zuständig wäre.",
  "Datenschutz wird berufen, wenn es unbequem wird, und vergessen, wenn nicht.",

  // Öffentlichkeit & Netz
  "Was im Ort passiert, steht binnen Stunden in einer Gruppe im Netz.",
  "Ein Gerücht ist hier schneller wahr als eine Richtigstellung.",
  "Jeder wird gefilmt, jederzeit, und alle haben sich daran gewöhnt.",
  "Wer öffentlich Stellung nimmt, muss mit Post rechnen.",
  "Die Lokalzeitung berichtet nicht über ihre Anzeigenkunden.",
  "Anonymität gibt es nur, solange niemand ein Interesse hat.",
  "Wer einmal in den Nachrichten war, bleibt es im Netz für immer.",
  "Ein Foto genügt, um jemanden hier unmöglich zu machen.",
  "Über bestimmte Vorfälle wird nur im Privaten gesprochen.",
  "Was nicht dokumentiert ist, ist nicht passiert – vor Gericht wie im Ort.",
  "Jeder Streit wird binnen eines Tages öffentlich ausgetragen.",
  "Die Reichweite entscheidet, wem geglaubt wird.",
  "Wer sich entschuldigt, gibt zu, und wer zugibt, verliert.",
  "Bilder aus dem Ort verlassen den Ort nicht ungefragt.",
  "Auf Ansagen von oben reagiert hier niemand mehr.",

  // Ungeschriebenes
  "Herkunft entscheidet mehr als Leistung, auch wenn alle das Gegenteil behaupten.",
  "Wer laut wird, hat automatisch unrecht.",
  "Männer weinen hier nicht, Frauen entschuldigen sich für alles.",
  "Alter geht vor, immer und überall.",
  "Wer zuerst da war, hat Vorrang – bei Parkplätzen wie bei Ansprüchen.",
  "Versprechen unter vier Augen gelten mehr als Verträge.",
  "Über Krankheiten spricht man erst, wenn sie überstanden sind.",
  "Man geht nicht zum Arzt, solange man noch arbeiten kann.",
  "Kinder werden erwachsen, sobald der Erste in der Familie krank wird.",
  "Wer Bildung hat, wird misstrauisch beäugt, wenn er bleibt.",
  "Gäste bekommen das Beste, auch wenn danach nichts bleibt.",
  "Was man geerbt hat, verkauft man nicht.",
  "Wer aussteigt, wird nicht zurückgeholt.",
  "Für Fremde gelten die Regeln strenger als für Einheimische.",
  "Niemand fragt nach, warum jemand fortgegangen ist.",
  "Höflichkeit ersetzt hier Zuneigung und niemand merkt den Unterschied.",
  "Was gestern galt, gilt heute noch, bis jemand es ausdrücklich aufhebt.",
  "Wer keine Kinder hat, muss sich erklären.",
  "Nach dem dritten Bier ist alles gesagt und nichts davon gilt.",
  "Die Arbeit geht vor, auch vor dem Sterben.",
  "Wer im Ort investiert, darf mitbestimmen; wer nur wohnt, nicht.",
  "Man schuldet der Familie alles und sagt es nie.",
  "Über die Jahre vor der Wende wird nicht gesprochen.",
  "Ein gegebenes Wort bricht man nicht, auch wenn es teuer wird.",
  "Wer den Hof übernimmt, hat keine Wahl gehabt.",
  "Zugezogene mit Geld werden geduldet, Zugezogene ohne Geld nicht.",
  "Hier hilft man sich, aber man rechnet mit.",
  "Wer sich scheiden lässt, verliert die Hälfte des Bekanntenkreises.",
  "Man verlässt den Ort nicht ohne Grund und kehrt nicht ohne Grund zurück.",
  "Was die Kirche sagt, zählt nicht mehr, was sie besitzt, immer noch.",
  "Wer die Sprache nicht akzentfrei spricht, wird nie ganz dazugehören.",
  "Loyalität wiegt hier schwerer als Recht.",
  "Über Erbschaften wird geschwiegen, bis es zu spät ist.",
  "Jeder kennt die Wahrheit über den Unfall damals und keiner sagt sie.",
  "Kritik wird persönlich genommen, immer.",
  "Wer Erfolg hat, soll ihn nicht zeigen.",
  "Man bleibt bei der Familie, auch wenn sie einen zerstört.",
  "Ein Handschlag gilt hier mehr als eine Unterschrift.",
  "Wer aus der Reihe tanzt, wird nicht bestraft, sondern übersehen.",
  "Am Ende zählt, wer zur Beerdigung kommt.",
];

/** Fantasy: Magie, Herrschaft, Glaube, Gastrecht, Standesordnung. */
export const FANTASY_RULES: string[] = [
  // Magie
  "Magie wirkt, aber sie kostet den Anwender etwas, das nicht zurückkommt.",
  "Zauberei ist erlaubt, wird aber überwacht und muss angemeldet werden.",
  "Wer magisch begabt ist, gehört von Kindheit an dem Orden, nicht der Familie.",
  "Magie funktioniert hier nicht, und niemand weiß, warum.",
  "Jeder Zauber hinterlässt eine Spur, die kundige Augen lesen können.",
  "Die Toten bleiben tot, und wer das Gegenteil versucht, wird verbrannt.",
  "Heilkunst gilt als Magie und wird entsprechend misstraut.",
  "Zauberer dürfen kein Land besitzen und kein Amt bekleiden.",
  "Wer Magie einsetzt, muss sie öffentlich anzeigen oder gilt als Verräter.",
  "Magische Gegenstände sind Eigentum der Krone, wer sie findet, muss sie abliefern.",
  "Magie ist billig geworden und deshalb nichts mehr wert.",
  "Beschwörungen sind seit dem letzten Unglück bei Todesstrafe verboten.",
  "Jede magische Handlung braucht Zeugen, sonst zählt sie als Angriff.",
  "Nur wer lesen kann, kann zaubern – und lesen lernen wenige.",
  "Magie wirkt nur nach Einbruch der Dunkelheit.",

  // Herrschaft & Recht
  "Recht spricht, wer das Land besitzt, nicht wer es kennt.",
  "Ein Eid bindet hier auch dann, wenn er erzwungen wurde.",
  "Wer einen Herrn hat, kann nicht vor Gericht gegen ihn aussagen.",
  "Waffen dürfen in Städten nicht getragen werden, außer von Adligen.",
  "Fehden zwischen Häusern sind erlaubt, solange keine Bauern zu Schaden kommen.",
  "Die Todesstrafe wird öffentlich vollstreckt und gilt als Fest.",
  "Wer ein Jahr und einen Tag in der Stadt lebt, ist frei.",
  "Schulden gehen auf die Kinder über.",
  "Adel wird nur über die Mutter vererbt.",
  "Zölle darf jeder erheben, der eine Brücke hält.",
  "Zweikampf ist ein zulässiges Beweismittel vor Gericht.",
  "Wer verbannt wird, verliert Namen und Anspruch, nicht nur den Ort.",
  "Ämter werden gekauft, nicht vergeben.",
  "Das Wort eines Priesters wiegt vor Gericht doppelt.",
  "Wer sein Land drei Jahre nicht bestellt, verliert es.",

  // Glaube
  "Die Götter antworten, aber selten und nie eindeutig.",
  "Es gibt nur einen Glauben, und Abweichung ist ein Verbrechen.",
  "Wer im Tempel Zuflucht sucht, darf nicht herausgeholt werden.",
  "Opfer werden erwartet, und wer nicht opfert, wird gemieden.",
  "Die Priesterschaft stellt die einzigen Schreibkundigen im Land.",
  "Sterbende müssen vor Sonnenuntergang bestattet werden.",
  "Verstorbene ohne Ritus kehren zurück, sagen alle, und alle glauben es.",
  "Wahrsagen ist verboten und wird überall praktiziert.",
  "Bestimmte Tage sind heilig, an ihnen ruht jede Arbeit und jedes Recht.",
  "Wer einen Eid bei den Göttern bricht, verliert seinen Stand.",
  "Die alten Bräuche werden neben dem neuen Glauben weitergeführt.",
  "Zwei Auslegungen desselben Glaubens stehen einander feindlich gegenüber.",
  "Namen haben Macht, deshalb nennt niemand seinen vollen.",
  "Fremde Götter dürfen verehrt werden, aber nicht in der Öffentlichkeit.",
  "Die Kirche besitzt mehr Land als der Fürst.",

  // Gastrecht & Verkehr
  "Wer an einen Tisch geladen wird, ist bis zum Morgen unantastbar.",
  "Reisende haben Anspruch auf ein Nachtlager, jeder Hof muss es gewähren.",
  "Wer bei Nacht anklopft, wird nicht abgewiesen, aber gemustert.",
  "Fremde müssen sich beim Ältesten melden, bevor sie sich setzen.",
  "Wer Waffen mit an den Tisch bringt, erklärt Feindschaft.",
  "Boten sind unverletzlich, auch die des Feindes.",
  "Der Weg gehört allen, das Land daneben niemandem Fremden.",
  "Wer Salz und Brot geteilt hat, kann nicht mehr gegeneinander klagen.",
  "Karawanen zahlen Wegegeld und bekommen dafür Geleit.",
  "Ein Gast, der drei Tage bleibt, wird Teil des Hauses und seiner Pflichten.",
  "Handel mit Fremden ist nur an Markttagen erlaubt.",
  "Wer die Grenze überschreitet, gibt seine Waffen ab.",
  "Nachts wird das Tor geschlossen, und niemand kommt hinein.",
  "Wer einen Schiffbrüchigen aufnimmt, haftet für ihn.",
  "Auf der Straße gilt Frieden, wer ihn bricht, ist vogelfrei.",

  // Stand & Ordnung
  "Jeder wird geboren, wo er bleibt – Aufstieg gibt es nicht.",
  "Handwerk darf nur ausüben, wer der Zunft angehört.",
  "Frauen erben kein Land, aber sie verwalten es.",
  "Wer nicht lesen kann, gilt nicht als vollwertiger Zeuge.",
  "Leibeigene dürfen den Bezirk nicht ohne Erlaubnis verlassen.",
  "Der älteste Sohn erbt alles, die anderen gehen zum Heer oder ins Kloster.",
  "Ehen werden geschlossen, nicht gewählt.",
  "Wer heiratet, muss dem Herrn eine Abgabe zahlen.",
  "Ein Bastard hat keinen Anspruch, aber jeder weiß, wer wessen ist.",
  "Kleidung ist nach Stand vorgeschrieben, Verstöße werden bestraft.",
  "Wer sich freikauft, bleibt für alle trotzdem, was er war.",
  "Das Alter entscheidet in jeder Versammlung.",
  "Nur Grundbesitzer haben Stimme im Rat.",
  "Wer eine Waffe führt, muss auch für die Verteidigung antreten.",
  "Fremde können nie Bürger werden, ihre Enkel schon.",
  "Der Herr darf über Leben und Tod entscheiden, tut es aber selten selbst.",
  "Wer sein Handwerk aufgibt, verliert das Recht, es je wieder auszuüben.",
  "Ohne Bürgen bekommt hier niemand Arbeit.",
  "Bettelei ist erlaubt, aber nur den Anerkannten.",
  "Wer den Zehnten nicht zahlt, verliert die Ernte, nicht das Land.",
  "Waffenrecht und Stimmrecht sind dasselbe Recht.",
  "Verträge gelten nur, wenn sie ein Zeuge beider Stände bezeugt.",
  "Kinder gehören dem Haus, nicht den Eltern.",
  "Wer sich verschuldet, arbeitet ab, was er schuldet, bis es getilgt ist.",
  "Ein gegebenes Wort kann nicht zurückgenommen werden, nur eingelöst.",
  "Wer die Sprache der Herrschaft nicht spricht, wird vor Gericht nicht gehört.",
  "Ein Findelkind gehört dem Ort, der es aufnimmt, und schuldet ihm alles.",
  "Die Jagd im Wald des Herrn kostet die Hand.",
  "Wer eine Mühle oder Schmiede betreibt, braucht die Erlaubnis des Herrn.",
  "Verwandtschaft verpflichtet bis ins dritte Glied.",
  "Wer sich in einer Stadt niederlässt, muss einen Bürgen und ein Handwerk vorweisen.",
  "Man reist nicht bei Nacht, und wer es tut, hat etwas zu verbergen.",
  "Ein Schwur auf Eisen bindet stärker als einer auf Papier.",
  "Wer Land rodet, darf es drei Jahre steuerfrei bestellen.",
  "Fahrendes Volk darf bleiben, solange der Markt dauert, keinen Tag länger.",
  "Die Ältesten des Dorfes entscheiden, wer heiraten darf.",
  "Wer einen Wolf erlegt, hat Anspruch auf Lohn aus der Gemeindekasse.",
  "Waisen werden vom Ort versorgt und arbeiten dafür, sobald sie können.",
  "Ein Handel gilt erst, wenn beide Seiten getrunken haben.",
  "Wer die Ernte des Nachbarn schädigt, ersetzt sie doppelt.",
];

/** Steampunk: Fortschritt, Fabrik, Stand, Verkehr, Wissenschaft. */
export const STEAMPUNK_RULES: string[] = [
  // Fortschritt & Ordnung
  "Fortschritt gilt als moralische Pflicht, Zweifel daran als Rückständigkeit.",
  "Was patentiert ist, gehört dem, der es angemeldet hat, nicht dem, der es erdacht hat.",
  "Erfindungen müssen der Behörde vorgeführt werden, bevor sie verkauft werden dürfen.",
  "Wer eine Maschine baut, haftet für alles, was sie anrichtet.",
  "Die Dampfkonzession vergibt die Stadt, und sie vergibt sie nur einmal.",
  "Neue Verfahren werden erprobt, indem man sie einsetzt.",
  "Sicherheitsvorschriften gibt es, aber keine Kontrolle.",
  "Wer eine Maschine bedienen kann, verdient das Doppelte.",
  "Handarbeit gilt als überholt und wird trotzdem überall gebraucht.",
  "Jede Neuerung wird zuerst im Militär erprobt.",
  "Wer gegen eine Maschine verliert, bekommt keine Entschädigung.",
  "Das Patentamt ist käuflich, und alle wissen es.",
  "Erfinder ohne Geldgeber bleiben Erfinder ohne Erfindung.",
  "Bauteile sind genormt, aber jede Firma hat ihre eigene Norm.",
  "Was funktioniert, wird eingesetzt, bevor jemand versteht, warum.",

  // Fabrik & Arbeit
  "Die Werkssirene bestimmt den Tag, nicht die Sonne.",
  "Wer zu spät kommt, wird für die ganze Schicht nicht eingelassen.",
  "Kinder arbeiten mit, sobald sie an die Maschine reichen.",
  "Unfälle im Werk sind Sache des Verunglückten.",
  "Der Lohn wird in Werksscheinen ausgezahlt, gültig nur im Werksladen.",
  "Wer sich gewerkschaftlich betätigt, wird noch am selben Tag entlassen.",
  "Die Wohnung gehört zur Stelle: wer die Stelle verliert, verliert beides.",
  "Vorarbeiter dürfen körperlich strafen.",
  "Es wird sechs Tage gearbeitet, der siebte gehört der Kirche.",
  "Frauen erhalten für dieselbe Arbeit ein Drittel.",
  "Wer krank wird, wird ersetzt, nicht behandelt.",
  "Das Werk stellt Schule, Laden und Arzt – und rechnet alles an.",
  "Streik ist gesetzlich verboten und kommt trotzdem vor.",
  "Die Schicht endet, wenn das Tagessoll erfüllt ist, nicht nach Stunden.",
  "Wer nach dem Unfall nicht mehr arbeiten kann, geht ins Armenhaus.",

  // Stand & Gesellschaft
  "Geld schlägt Herkunft, aber Herkunft öffnet Türen, die Geld nicht öffnet.",
  "Wer im Rauch wohnt, kommt nicht in die Oberstadt.",
  "Bildung ist käuflich und deshalb ein Standesmerkmal.",
  "Ein Ingenieurtitel gilt mehr als ein Adelstitel, aber nur in der Stadt.",
  "Frauen dürfen studieren, aber nicht praktizieren.",
  "Wer im Club aufgenommen wird, entscheidet über Aufträge.",
  "Die Handelskammer bestimmt mehr als der Stadtrat.",
  "Schulden gelten als moralisches Versagen, nicht als wirtschaftliches Pech.",
  "Wohltätigkeit ist Pflicht der Reichen und Bedingung für die Armen.",
  "Ein Skandal beendet eine Karriere, ein Verbrechen nicht unbedingt.",
  "Die Fabrikanten heiraten untereinander.",
  "Wer aufsteigt, muss seine Herkunft ablegen, sichtbar und hörbar.",
  "Über Geld spricht man nicht, über Titel ständig.",
  "Diener hören alles und gelten als taub.",
  "Fortschrittsfeindlichkeit ist gesellschaftlich unmöglich.",

  // Verkehr & Verbindung
  "Der Fahrplan ist verbindlich, auch wenn er nicht einzuhalten ist.",
  "Wer die Trasse besitzt, bestimmt, wer sie befahren darf.",
  "Luftfahrt ist unversichert, jeder fliegt auf eigenes Risiko.",
  "Post wird geöffnet, wenn ein Verdacht besteht, und ein Verdacht besteht oft.",
  "Der Telegraf ist staatlich und wird mitgelesen.",
  "Reisen ohne Papiere ist möglich, aber teuer.",
  "Fracht geht vor Personen, immer.",
  "Wer eine Konzession für eine Strecke hat, hat sie für hundert Jahre.",
  "Die Uhrzeit richtet sich nach der Bahn, nicht nach der Sonne.",
  "Kanäle sind privat, Straßen sind öffentlich, und beide sind mautpflichtig.",
  "Wer zu Fuß reist, gilt als mittellos.",
  "Ein Unglück wird untersucht, wenn eine Gesellschaft daran verdient.",
  "Der Zoll kontrolliert alles außer dem, was den Großen gehört.",
  "Luftschiffe dürfen über der Oberstadt nicht ankern.",
  "Wer Kohle transportiert, hat Vorfahrt vor allem anderen.",

  // Wissenschaft & Wahrheit
  "Was in der Akademie nicht anerkannt ist, gilt als Scharlatanerie.",
  "Versuche am Menschen sind erlaubt, solange er einwilligt.",
  "Die Zeitungen berichten, was ihre Anzeigenkunden erlauben.",
  "Ein Gutachten kostet, und der Zahlende bekommt sein Ergebnis.",
  "Fotografien gelten vor Gericht als Beweis.",
  "Wer eine Theorie widerlegt, macht sich Feinde fürs Leben.",
  "Chemikalien sind frei verkäuflich.",
  "Öffentliche Vorführungen ersetzen die Prüfung.",
  "Frauen dürfen nicht als Erstautorin veröffentlichen.",
  "Was der Militärverwaltung nützt, wird nicht veröffentlicht.",
  "Ärzte sind zugleich Werksärzte und niemals unabhängig.",
  "Die Statistik gilt als Beweis, auch wenn sie erfunden ist.",
  "Wer eine Entdeckung meldet, muss sie binnen dreier Monate vorführen.",
  "Geheimhaltung ist Vertragsbestandteil jeder Anstellung.",
  "Über den Preis des Fortschritts wird nicht öffentlich geredet.",
  "Elektrizität gilt als gefährlich und wird deshalb nur oben installiert.",
  "Ein Verfahren gilt als sicher, bis dreimal jemand gestorben ist.",
  "Erfinder haften mit ihrem Vermögen, Gesellschaften nicht.",
  "Wer Beweise vorlegt, muss auch die Mittel haben, sie zu verteidigen.",
  "Die Akademie entscheidet, was als Wissen gilt.",
  "Rauch gilt als Zeichen von Wohlstand.",
  "Wer eine Maschine versteht, wird nicht gefragt, ob man sie bauen soll.",
  "Militäraufträge sind ehrenhaft, zivile sind es weniger.",
  "Konstruktionspläne sind Eigentum des Werks, nicht des Konstrukteurs.",
  "Öffentliche Sicherheit endet an der Werksgrenze.",
  "Wer eine Konzession besitzt, muss sie nutzen, sonst fällt sie zurück.",
  "Ruß in der Luft gilt als Preis, den alle zahlen und niemand berechnet.",
  "Lehrjungen sind sieben Jahre an ihren Meister gebunden.",
  "Wer nachts im Werk gebraucht wird, hat kein Recht abzulehnen.",
  "Die Feuerwehr rückt zuerst zu den Fabriken aus, dann zu den Wohnhäusern.",
  "Ein Ingenieur haftet persönlich für jede Konstruktion, die er unterschreibt.",
  "Frauen dürfen in der Fertigung arbeiten, aber nicht an den Maschinen.",
  "Wer im Werk stirbt, wird auf Kosten des Werks bestattet und damit ist es erledigt.",
  "Über Betriebsgeheimnisse zu reden ist strafbar, auch nach der Kündigung.",
  "Der Werksarzt entscheidet, wer arbeitsfähig ist, nicht der Kranke.",
  "Erfindungen von Angestellten gehören dem Werk.",
  "Wer eine Maschine beschädigt, arbeitet sie ab.",
  "Die Stadt haftet für nichts, was hinter einem Werkstor geschieht.",
  "Jede Neuerung muss zuerst der Direktion vorgeführt werden.",
  "Wer den Kessel bedient, darf die Schicht nicht verlassen.",
];

/** Cyberpunk: Konzernrecht, Daten, Körper, Überleben, Loyalität. */
export const CYBERPUNK_RULES: string[] = [
  // Konzernrecht
  "Konzerne haben eigenes Hausrecht, das staatliches Recht ersticht.",
  "Wer einen Vertrag unterschreibt, verkauft mehr, als darin steht.",
  "Kündigen kann man nicht – man wird abgeschrieben.",
  "Wer keinen Arbeitgeber hat, gilt rechtlich als nicht vorhanden.",
  "Die Werkssicherheit darf schießen, die Polizei muss fragen.",
  "Verträge werden nicht gebrochen, sondern neu ausgelegt.",
  "Wer einen Konzern verklagt, verliert, egal wie recht er hat.",
  "Wohnung, Versicherung und Ausbildung hängen am Arbeitsvertrag.",
  "Konkurrenzklauseln gelten lebenslang.",
  "Was du im Dienst erfindest, gehört dem Konzern, auch was du dabei denkst.",
  "Schulden werden vererbt und mit Zinsen weitergereicht.",
  "Die Gerichtsbarkeit richtet sich danach, wem der Boden gehört.",
  "Wer zwischen zwei Konzerne gerät, hat kein Recht mehr auf irgendetwas.",
  "Streiken ist Vertragsbruch, und Vertragsbruch ist eine Straftat.",
  "Nur wer versichert ist, wird behandelt.",

  // Daten & Identität
  "Wer keine verifizierte Identität hat, existiert nicht.",
  "Alles wird aufgezeichnet, und alles wird irgendwann verkauft.",
  "Eine Identität lässt sich kaufen, aber nur eine gebrauchte.",
  "Anonymität ist illegal und deshalb teuer.",
  "Wer ein Leck verursacht, wird nicht verklagt, sondern gelöscht.",
  "Erinnerungen sind aufzeichenbar und deshalb handelbar.",
  "Was du unverschlüsselt sagst, ist öffentlich.",
  "Deine Kreditwürdigkeit entscheidet, welche Straßen du betreten darfst.",
  "Es gibt keine Löschung, nur Verlagerung.",
  "Ein Datensatz gilt als Beweis, eine Aussage nicht.",
  "Wer offline geht, macht sich verdächtig.",
  "Der Zugang zum Netz ist ein Vertrag, kein Recht.",
  "Jedes Implantat sendet, ob du willst oder nicht.",
  "Wer die Daten hat, hat recht.",
  "Deine Bewegungsdaten gehören dem Betreiber der Straße.",

  // Körper & Technik
  "Implantate brauchen Wartung, und Wartung ist ein Abonnement.",
  "Wer sich nicht erweitern lässt, ist auf dem Arbeitsmarkt chancenlos.",
  "Ein Implantat kann ferngesperrt werden, wenn die Rate ausbleibt.",
  "Ersatzteile für den Körper sind billiger als Behandlung.",
  "Wer zu viel ersetzt hat, verliert Rechte als natürliche Person.",
  "Illegale Klinikarbeit ist Standard, legale ist unbezahlbar.",
  "Der Hersteller haftet nicht für das, was in deinem Körper steckt.",
  "Medikamente werden abonniert, nicht verschrieben.",
  "Wer Schmerzen ausschaltet, merkt nicht, wenn er kaputtgeht.",
  "Gebrauchte Implantate werden ausgebaut, auch bei Lebenden.",
  "Jede Erweiterung ist rückverfolgbar bis zum Einbau.",
  "Alterung gilt als vermeidbar und wird deshalb als Versäumnis behandelt.",
  "Ein Körper ohne Papiere lässt sich verwerten.",
  "Wer sein Implantat entfernen lässt, verliert die Garantie auf alles.",
  "Blut, Gewebe und Daten werden am selben Schalter gehandelt.",

  // Überleben
  "Wasser ist teurer als Bandbreite.",
  "Wer nachts allein unterwegs ist, hat entweder Schutz oder nichts zu verlieren.",
  "Strom kommt stundenweise, und die Stunden werden bekannt gegeben.",
  "Wer im Erdgeschoss wohnt, wohnt im Wasser.",
  "Gesundheitsversorgung existiert, aber nicht für alle Etagen.",
  "Waffen sind verboten und überall.",
  "Wer eine Adresse hat, hat es geschafft.",
  "Frische Lebensmittel sind ein Statussymbol.",
  "Die Luft draußen ist an schlechten Tagen tödlich, und es gibt viele schlechte Tage.",
  "Wer nicht arbeiten kann, wird verlegt, nicht versorgt.",
  "Miete wird wöchentlich fällig, in bar oder in Leistung.",
  "Kein Rettungsdienst fährt in bestimmte Blocks.",
  "Wer keinen Schutzpatron hat, zahlt an alle.",
  "Feuer breitet sich hier aus, weil niemand zuständig ist.",
  "Kinder arbeiten, sobald sie nicht mehr getragen werden müssen.",

  // Loyalität & Straße
  "Wer redet, wird nicht bestraft, sondern ersetzt.",
  "Ein Wort auf der Straße gilt mehr als ein Vertrag im Turm.",
  "Schulden bei einer Bande werden nicht erlassen, nur verlängert.",
  "Wer Schutz annimmt, gehört dazu, ob er will oder nicht.",
  "Verrat wird nicht vergessen, aber manchmal gekauft.",
  "Jeder arbeitet für jemanden, auch wer das Gegenteil sagt.",
  "Familie ist, wer für dich einsteht, nicht wer mit dir verwandt ist.",
  "Neutralität gibt es nicht, nur unentdeckte Zugehörigkeit.",
  "Wer eine Grenze überquert, zahlt an beide Seiten.",
  "Ein Job wird zu Ende gebracht, auch wenn der Auftraggeber tot ist.",
  "Wer bezahlt wird, fragt nicht.",
  "Informationen sind die einzige Währung, die nicht abgewertet wird.",
  "Man hilft, aber man rechnet auf.",
  "Wer einmal für einen Konzern gearbeitet hat, wird auf der Straße nie voll akzeptiert.",
  "Rache ist hier keine Emotion, sondern Preispolitik.",
  "Wer sich nicht wehrt, wird abgeräumt.",
  "Alte Leute gibt es kaum, und die es gibt, haben Gründe.",
  "Man stirbt hier an Kleinigkeiten, nicht an großen Dingen.",
  "Loyalität hält genau so lange wie die Zahlungen.",
  "Wer aussteigen will, muss die Stadt verlassen, und die Stadt ist überall.",
  "Ein Versprechen ohne Anzahlung ist kein Versprechen.",
  "Wer einen Auftrag ablehnt, bekommt keinen zweiten.",
  "Namen werden nicht genannt, nur Kennungen.",
  "Wer für zwei Seiten arbeitet, wird von beiden bezahlt und von beiden gejagt.",
  "Ein Treffen findet nie zweimal am selben Ort statt.",
  "Wer bewaffnet zu einer Verhandlung kommt, hat schon geantwortet.",
  "Schweigen kostet extra und hält länger.",
  "Man fragt nicht, wofür die Daten gebraucht werden.",
  "Wer einen Mittelsmann umgeht, verliert den Zugang für immer.",
  "Jede Bande duldet Durchreisende, aber keine Geschäfte.",
  "Wer ein Versteck verrät, verliert alle.",
  "Ein Ausweis ist so gut wie die Firma, die ihn nicht widerruft.",
  "Wer im Netz auffällt, wird auf der Straße gesucht.",
  "Erste Regel: niemand kommt zurück, um dich zu holen.",
  "Ein Job ohne Rückweg wird doppelt bezahlt und einfach überlebt.",
  "Wer sich versichern lässt, gibt zu, dass er etwas zu verlieren hat.",
  "Man zahlt nie im Voraus und nie den vollen Preis.",
  "Wer einen Konzernmitarbeiter tötet, hat die Firma am Hals, nicht die Polizei.",
  "Vertrauen wird geliehen, nicht geschenkt.",
  "Wer zu lange in einem Viertel bleibt, gehört ihm.",
];

/** Historisch: Stand, Kirche, Recht, Wirtschaft, Ehre. */
export const HISTORISCH_RULES: string[] = [
  // Stand & Geburt
  "Der Stand bei der Geburt bestimmt das ganze Leben.",
  "Wer Land besitzt, hat Recht; wer keines besitzt, hat Pflichten.",
  "Adel darf nicht arbeiten, Bürger nicht regieren, Bauern nicht fortziehen.",
  "Ein Titel wird vererbt, ein Amt gekauft, ein Handwerk gelernt.",
  "Wer eine Standesgrenze überschreitet, gilt als anmaßend.",
  "Kleiderordnungen legen fest, wer was tragen darf.",
  "Nur der erstgeborene Sohn erbt, alle anderen müssen versorgt werden.",
  "Frauen stehen zeitlebens unter der Vormundschaft eines Mannes.",
  "Ein Leibeigener kann nicht klagen, nur sein Herr für ihn.",
  "Wer freigelassen wird, bleibt an den Ort gebunden.",
  "Bürgerrecht muss erworben werden und kostet mehr, als die meisten haben.",
  "Der Familienname sagt alles, was man über einen Menschen wissen muss.",
  "Bildung ist Vorrecht der Kirche und des Adels.",
  "Wer einheiratet, bringt Vermögen mit oder wird nicht genommen.",
  "Uneheliche Kinder erben nichts und tragen es im Namen.",

  // Kirche & Glaube
  "Der Glaube ist vorgeschrieben, Abweichung ist Ketzerei.",
  "Die Kirche führt die einzigen Register über Geburt, Ehe und Tod.",
  "Wer in der Kirche Zuflucht sucht, darf nicht ergriffen werden.",
  "Der Zehnte ist zu entrichten, auch in Hungerjahren.",
  "Zinsnahme ist verboten und wird über Umwege betrieben.",
  "An Feiertagen ruht jede Arbeit, und es gibt viele Feiertage.",
  "Wer exkommuniziert wird, verliert jeden Rechtsanspruch.",
  "Eheschließungen sind unauflöslich.",
  "Der Bischof ist zugleich weltlicher Herr.",
  "Aberglaube wird verfolgt und von allen praktiziert.",
  "Selbstmörder werden außerhalb der Mauern verscharrt.",
  "Klöster bieten Versorgung, verlangen aber Eintritt und Mitgift.",
  "Predigten sind das wichtigste Nachrichtenmedium.",
  "Wer die Beichte verweigert, macht sich verdächtig.",
  "Fasten- und Speisegebote gelten für alle Stände.",

  // Recht & Gewalt
  "Recht spricht der Herr, und er spricht es öffentlich.",
  "Folter ist zulässiges Mittel der Wahrheitsfindung.",
  "Strafen werden am Körper vollzogen, nicht in Jahren bemessen.",
  "Wer geächtet wird, darf von jedem erschlagen werden.",
  "Ein Eid ersetzt den Beweis, wenn genug Männer ihn leisten.",
  "Blutrache ist verboten und findet statt.",
  "Wer bewaffnet reist, ist verdächtig, wer unbewaffnet reist, ist Beute.",
  "Waffenrecht hängt am Stand, nicht am Bedarf.",
  "Für einen Toten wird gezahlt, und der Preis richtet sich nach dem Stand.",
  "Gerichtsverfahren dauern Jahre und werden vererbt.",
  "Fremde unterliegen einem eigenen Recht.",
  "Zeugen müssen ehrbar sein, sonst zählt ihre Aussage nicht.",
  "Der Herr darf jeden auf seinem Land richten.",
  "Wer nicht zahlen kann, sitzt es ab oder arbeitet es ab.",
  "Ein Vertrag ohne Siegel ist kein Vertrag.",

  // Wirtschaft & Not
  "Zünfte bestimmen, wer ein Handwerk ausüben darf und wie viele.",
  "Preise für Brot und Bier setzt die Obrigkeit fest.",
  "Wer über den festgesetzten Preis verkauft, wird an den Pranger gestellt.",
  "Handel mit Fremden ist nur an Markttagen erlaubt.",
  "Jeder Fluss und jede Brücke hat einen Zoll.",
  "Wucher wird bestraft und ist unentbehrlich.",
  "Missernten treffen die Herrschaft nicht, nur die Bauern.",
  "Vorräte anzulegen gilt als Spekulation.",
  "Wer die Mühle des Herrn nicht benutzt, wird bestraft.",
  "Fuhrleute haften für die Ware, die sie verlieren.",
  "Münzen werden gewogen, nicht gezählt.",
  "Kredit gibt es nur gegen Grundbesitz oder Bürgen.",
  "Die Allmende gehört allen und wird von den Mächtigen eingezäunt.",
  "Bettelei ist erlaubt, aber nur mit Erlaubnisschein.",
  "Wer sein Handwerk nicht ernährt, wandert oder verhungert.",

  // Ehre & Umgang
  "Ehre ist ein Besitz und lässt sich zerstören.",
  "Eine Beleidigung muss beantwortet werden, sonst gilt sie als wahr.",
  "Ein gegebenes Wort bricht man nicht, auch nicht gegenüber Feinden.",
  "Gastrecht ist heilig, drei Tage lang.",
  "Wer sich nicht satisfaktionsfähig zeigt, verliert seinen Stand.",
  "Über Familienangelegenheiten spricht man nicht mit Fremden.",
  "Der Ruf einer Frau ist der Besitz ihrer Familie.",
  "Wer sich öffentlich betrinkt, verliert an Ansehen, nicht an Freunden.",
  "Schulden bei Standesgenossen werden nicht eingeklagt, sondern erinnert.",
  "Ein Bruch des Lehnseids ist das schwerste Verbrechen überhaupt.",
  "Man widerspricht keinem Höhergestellten in der Öffentlichkeit.",
  "Wer sein Wort mehrfach bricht, findet keinen Bürgen mehr.",
  "Höflichkeitsformen sind verbindlich und ihr Verstoß ist eine Kampfansage.",
  "Wer einen Gefangenen macht, hat Anspruch auf sein Lösegeld.",
  "Alter und Herkunft entscheiden, wer zuerst spricht.",
  "Wer einen Gast beherbergt, haftet für seine Taten.",
  "Ein Fremder muss sich beim Rat melden, bevor er übernachtet.",
  "Waffen bleiben vor der Kirche und vor dem Rathaus.",
  "Wer schreiben kann, wird gebraucht und deshalb überwacht.",
  "Briefe werden gesiegelt und trotzdem gelesen.",
  "Ein Handwerksgeselle muss wandern, bevor er Meister werden kann.",
  "Wer eine Frau ohne Zustimmung ihrer Familie nimmt, ist ein Räuber.",
  "Das Stadttor schließt bei Sonnenuntergang, für alle.",
  "Wer nach dem Feuerläuten noch Licht brennt, zahlt Strafe.",
  "Jeder Bürger muss Waffen und Rüstung stellen können.",
  "Getreide darf nicht ausgeführt werden, solange der eigene Markt leer ist.",
  "Wer Feuer verursacht, haftet für die ganze Gasse.",
  "Der Nachtwächter hat Befehlsgewalt über jeden, den er antrifft.",
  "Duelle unter Bürgern sind verboten, unter Adligen geduldet.",
  "Wer die Stadt verlässt, ohne seine Schulden zu tilgen, wird geächtet.",
  "Ein Meister darf nur so viele Gesellen halten, wie die Zunft erlaubt.",
  "Über Krankheiten im Haus muss dem Rat Meldung gemacht werden.",
  "Wer einen Toten findet, muss ihn melden und darf ihn nicht bewegen.",
  "Fremde Kaufleute dürfen nicht untereinander handeln, nur mit Einheimischen.",
  "Wer die Wache beleidigt, verbringt die Nacht im Turm.",
  "Das Recht des Ortes gilt nur innerhalb der Mauern.",
  "Wer sich verdingt, ist ein Jahr gebunden, von Martini bis Martini.",
  "Kinder haften nicht, aber ihre Väter.",
  "Wer Almosen verweigert, gilt als hartherzig und wird gemieden.",
  "Ein Urteil des Rats ist endgültig, es sei denn, der Herr hebt es auf.",
];

/** Western: Waffen, Land, Recht, Gemeinschaft, Grenze. */
export const WESTERN_RULES: string[] = [
  // Waffen & Gewalt
  "Jeder trägt eine Waffe, und jeder weiß, wer sie benutzen kann.",
  "Wer zuerst zieht, hat unrecht, aber meistens überlebt.",
  "In der Stadt müssen Waffen beim Sheriff abgegeben werden.",
  "Ein Streit wird draußen ausgetragen, nicht im Saloon.",
  "Wer einen Unbewaffneten erschießt, wird gehängt.",
  "Notwehr gilt großzügig, solange Zeugen es bestätigen.",
  "Auf Pferdediebe wird ohne Warnung geschossen.",
  "Wer aus dem Hinterhalt schießt, verliert jeden Anspruch auf Ehre.",
  "Duelle sind verboten und werden nicht verhindert.",
  "Wer eine Waffe zieht, muss sie auch benutzen.",
  "Frauen und Kinder werden nicht in Schusswechsel hineingezogen, das gilt absolut.",
  "Wer einen Mann tötet, muss dessen Familie ins Gesicht sehen.",
  "Schießereien in der Stadt kosten den Schützen den Schaden.",
  "Ein Gewehr ist Werkzeug, ein Revolver ist eine Absicht.",
  "Wer davonläuft, kommt hier nie wieder unter Menschen.",

  // Land & Vieh
  "Wer Wasser hat, hat Macht.",
  "Land gehört dem, der es hält, nicht dem, der Papiere darauf hat.",
  "Offenes Weideland ist frei, bis jemand einen Zaun zieht.",
  "Ein Brandzeichen ist Eigentumsnachweis und wird nicht angezweifelt.",
  "Wer fremdes Vieh treibt, ist ein Dieb, egal welche Gründe er hat.",
  "Schafe und Rinder teilen sich kein Land.",
  "Ein Homestead muss bewirtschaftet werden, sonst verfällt der Anspruch.",
  "Zäune zu durchtrennen ist eine Kriegserklärung.",
  "Wasserrechte werden vor Gericht entschieden und auf der Weide durchgesetzt.",
  "Wer durchtreibt, darf tränken, aber nicht lagern.",
  "Verirrtes Vieh gehört dem, auf dessen Land es steht, bis der Besitzer kommt.",
  "Nachbarn helfen beim Round-up, ohne dass jemand fragt.",
  "Wer sein Land verkauft, verkauft auch die Fehden, die daran hängen.",
  "Vieh geht vor Menschen, wenn das Wasser knapp wird.",
  "Wer den Trail sperrt, legt sich mit allen Ranchern der Gegend an.",

  // Recht & Ordnung
  "Der Sheriff ist gewählt und damit käuflich.",
  "Der Richter kommt zweimal im Jahr, alles andere regelt die Stadt selbst.",
  "Eine Bürgerwehr ersetzt das Gesetz, sobald es zu langsam ist.",
  "Ein Kopfgeld gilt tot oder lebendig, und lebendig ist mehr Arbeit.",
  "Wer im Gefängnis sitzt und nicht abgeholt wird, kommt frei.",
  "Was jenseits der Stadtgrenze passiert, interessiert hier niemanden.",
  "Der Marshal hat Vollmacht, aber selten Rückendeckung.",
  "Ein Geständnis reicht als Beweis, auch ein erzwungenes.",
  "Wer die Kaution stellt, bestimmt über den Beschuldigten.",
  "Zeugen aus dem eigenen Ort zählen doppelt.",
  "Fremde werden zuerst verdächtigt.",
  "Ein Prozess dauert einen Tag, das Urteil eine Stunde.",
  "Wer geht, bevor der Richter kommt, gilt als schuldig.",
  "Der Bankier hat mehr Einfluss auf das Urteil als der Anwalt.",
  "Wer aussagt, muss danach mit den Leuten weiterleben.",

  // Gemeinschaft
  "Man hilft jedem Fremden, der um Wasser bittet.",
  "Ein geteiltes Lagerfeuer verpflichtet für die Nacht.",
  "Wer allein reist, wird nicht nach seinem Namen gefragt.",
  "Über die Vergangenheit eines Mannes fragt man nicht.",
  "Ein Handschlag gilt, ein Vertrag ist eine Beleidigung.",
  "Wer beim Wort genommen wird, hat sein Wort gegeben.",
  "Nachbarn kommen beim Hausbau und beim Sterben.",
  "Wer sein Pferd schlecht behandelt, wird geschnitten.",
  "In Not wird geteilt, danach wird abgerechnet.",
  "Ein Prediger und ein Arzt sind willkommen, alles andere wird geprüft.",
  "Wer trinkt, zahlt für alle oder für keinen.",
  "Falschspiel wird schwerer bestraft als Diebstahl.",
  "Man betritt kein fremdes Haus, ohne gerufen zu werden.",
  "Wer eine Beerdigung verpasst, hat einen Grund zu nennen.",
  "Über Frauen wird in ihrer Abwesenheit nicht gesprochen.",

  // Grenze & Fremde
  "Zwei Meilen hinter der Stadt gilt kein Gesetz mehr.",
  "Verträge mit den Stämmen werden geschlossen, um gebrochen zu werden.",
  "Wer über den Fluss geht, ist außer Reichweite jedes Haftbefehls.",
  "Die Armee schützt die Siedler, nicht das Land.",
  "Reservatsgrenzen werden verschoben, wenn dort etwas gefunden wird.",
  "Wer mit den Stämmen handelt, gilt in der Stadt als unzuverlässig.",
  "Die Eisenbahngesellschaft bekommt jedes Land, das sie beantragt.",
  "Ein Gebiet gehört dem, der zuerst eine Behörde einrichtet.",
  "Fremde Sprachen werden geduldet, aber nicht vor Gericht.",
  "Wer aus Mexiko kommt, braucht doppelt so lange, um dazuzugehören.",
  "Chinesische Arbeiter dürfen nicht aussagen und nicht besitzen.",
  "Wer sich hier neu erfindet, wird beim Wort genommen, bis jemand ihn erkennt.",
  "Kopfgeldjäger haben in der Stadt keine Befugnisse und werden geduldet.",
  "Wer freiwillig ins Territorium zieht, verzichtet auf jeden Schutz.",
  "Was östlich des Mississippi gilt, gilt hier nicht.",
  "Wer einen Claim absteckt, muss ihn bearbeiten, sonst ist er frei.",
  "Gold wird gewogen, nicht gezählt, und die Waage gehört dem Händler.",
  "Wer die Post überfällt, hat es mit der Regierung zu tun, nicht mit der Stadt.",
  "Ein Pferd zu leihen ist selbstverständlich, es nicht zurückzubringen ist tödlich.",
  "Wer im Winter jemanden abweist, hat ihn umgebracht.",
  "Die Bahn fährt zur angeschlagenen Zeit, alles andere wartet.",
  "Wer Alkohol an die Stämme verkauft, macht sich strafbar und tut es trotzdem.",
  "Ein Vertrag mit einer Gesellschaft ist einseitig und wird trotzdem unterschrieben.",
  "Wer Schulden im Laden hat, verkauft seine Ernte an den Ladenbesitzer.",
  "Fremde Reiter werden von der Veranda aus beobachtet, bis sie vorbei sind.",
  "Wer nachts an eine Ranch reitet, ruft von weitem.",
  "Der Saloon ist neutraler Boden, bis jemand ihn verlässt.",
  "Wer eine Rechnung offen hat, verlässt die Stadt nicht.",
  "Ein Mann wird an seiner Arbeit gemessen, nicht an seinem Besitz.",
  "Wer sein Wort gegenüber einer Frau bricht, findet keine Arbeit mehr.",
  "Karten, Whiskey und Pferde werden nicht auf Kredit gehandelt.",
  "Wer eine Herde verliert, verliert seine Anstellung, egal warum.",
  "Die Kirche steht allen offen, auch denen, die nicht hineingehen.",
  "Wer eine Waffe im Saloon abfeuert, zahlt für jeden Spiegel.",
  "Ein Trailboss entscheidet allein, und seine Entscheidung wird nicht besprochen.",
  "Wer den Lohn vorschießt, bindet den Mann für die Saison.",
  "Über eine Frau, die allein reist, wird nichts gefragt und viel gedacht.",
  "Wer einen Verletzten zurücklässt, findet keinen Partner mehr.",
  "Das Feuer im Camp wird nie unbeaufsichtigt gelassen.",
  "Wer die Wasserstelle vergiftet, wird von allen gejagt, ohne Ausnahme.",
];

/** Science Fiction: Versorgung, Zugehörigkeit, Verträge, Maschinen, Körper, Ferne. */
export const SCIFI_RULES: string[] = [
  // Versorgung & Leben
  "Luft und Wasser werden zugeteilt, und die Zuteilung ist öffentlich einsehbar.",
  "Wer Ressourcen verschwendet, verliert Anspruch, nicht Geld.",
  "Jeder Haushalt führt eine Verbrauchsbilanz, und die wird geprüft.",
  "Reparieren gilt mehr als Besitzen.",
  "Nichts wird weggeworfen, alles wird zurückgeführt.",
  "Wohnraum bemisst sich nach Aufgabe, nicht nach Vermögen.",
  "Wer nicht arbeitet, bekommt Grundversorgung, aber keine Bewegungsfreiheit.",
  "Schwerkraft ist ein Privileg, für das bezahlt wird.",
  "Frisches Essen ist ein Geschenk, kein Handelsgut.",
  "Kinder gelten als gemeinsame Angelegenheit, nicht als Sache der Eltern allein.",
  "Wer eine Störung bemerkt und nicht meldet, haftet mit.",
  "Jeder Erwachsene beherrscht die Notfallgriffe, und das wird geprüft.",
  "Die Wartung hat Vorrang vor jeder anderen Arbeit.",
  "Überzählige Fracht wird abgeworfen, ohne Rücksprache.",
  "Alle tragen dieselbe Kleidung, Unterschiede werden anders gezeigt.",
  "Über den Preis von Wasser wird geredet, über den von Luft nicht.",

  // Recht & Zugehörigkeit
  "Wer hier geboren ist, hat andere Rechte als wer angekommen ist.",
  "Der Aufenthalt hängt an einem Vertrag, nicht an einer Herkunft.",
  "Wer seinen Vertrag bricht, verliert den Anspruch auf Rückreise.",
  "Ausweisung ist die höchste Strafe und wird selten verhängt.",
  "Es gibt kein Gefängnis, nur den Ausschluss von der Versorgung.",
  "Recht spricht, wer die Schicht leitet.",
  "Verträge gelten über den Tod hinaus und gehen auf die Kinder über.",
  "Wer eine Fähigkeit hat, die gebraucht wird, darf nicht kündigen.",
  "Doppelte Zugehörigkeit gilt als Sicherheitsrisiko.",
  "Schulden lassen sich mit Dienstzeit begleichen, und das ist der übliche Weg.",
  "Wer sich nicht registrieren lässt, kommt in keiner Akte vor.",
  "Jeder trägt eine Kennung, und sie zu verbergen ist strafbar.",
  "Fremde dürfen bleiben, solange jemand für sie bürgt.",
  "Zugehörigkeit richtet sich nach dem Schiff, nicht nach dem Geburtsort.",
  "Wer zurückkehrt, fängt von vorn an.",
  "Stehen die Beweise gleich, entscheidet ein Los.",

  // Arbeit & Vertrag
  "Arbeitsverträge laufen über Jahre und lassen sich nicht vorzeitig lösen.",
  "Wer eine Stelle antritt, verzichtet für ihre Dauer auf das Klagerecht.",
  "Der Arbeitgeber stellt die Wohnung, und mit der Stelle geht sie verloren.",
  "Beförderungen werden ausgelost, nicht vergeben.",
  "Jede Ausbildung wird vorfinanziert und muss abgearbeitet werden.",
  "Wer die Ausbildung abbricht, schuldet sie in voller Höhe.",
  "Eine Schicht dauert so lange, wie die Aufgabe braucht.",
  "Arbeitsniederlegung gilt als Gefährdung und wird entsprechend behandelt.",
  "Ämter werden nicht vererbt, Verpflichtungen schon.",
  "Wer eine Anlage von innen kennt, darf sie nicht verlassen.",
  "Fachleute werden zugeteilt, nicht eingestellt.",
  "Freiwillige Mehrarbeit wird verzeichnet und zählt bei Zuteilungen.",
  "Niemand arbeitet allein, das ist Vorschrift.",
  "Wer einen Auftrag annimmt, nennt den Auftraggeber nicht.",

  // Technik & Maschinen
  "Denkende Maschinen sind zugelassen, dürfen aber nicht entscheiden.",
  "Jedes System führt ein Protokoll, das sich nicht löschen lässt.",
  "Wer Technik verändert, haftet für alles, was danach geschieht.",
  "Selbstlernende Programme müssen angemeldet und begrenzt werden.",
  "Für jedes lebenswichtige System gibt es eine Handkurbel.",
  "Wer eine Sperre umgeht, verliert den Zugang dauerhaft.",
  "Nichts Wichtiges hängt an einer einzigen Leitung.",
  "Alte Technik gilt als die sicherere und wird bevorzugt.",
  "Wer etwas baut, muss zeigen, wie man es abschaltet.",
  "Werkzeug gehört der Station, nicht dem, der es benutzt.",
  "Automaten übernehmen keine Aufgaben, bei denen jemand sterben kann.",
  "Reparaturen werden vor Ort erklärt, nicht nur ausgeführt.",
  "Was von außen kommt, wird nicht eingespielt.",
  "Wer die Wartung abzeichnet, zeichnet mit seinem Namen.",

  // Körper & Medizin
  "Eingriffe am eigenen Körper sind frei, aber meldepflichtig.",
  "Prothesen gehören dem, der sie bezahlt hat.",
  "Wer nicht diensttauglich ist, verliert seinen Platz an Bord.",
  "Auskunft über die eigene Herkunft darf nicht verlangt werden.",
  "Kälteschlaf gilt als Reise, nicht als Behandlung.",
  "Behandlung wird nach Nutzen zugeteilt, nicht nach Dringlichkeit.",
  "Nachwuchs ist genehmigungspflichtig.",
  "Wer krank ist, meldet sich, oder ein anderer meldet ihn.",
  "Alter wird in Wachjahren gezählt, nicht in verstrichenen.",
  "Der Tod an Bord wird protokolliert, nicht betrauert.",
  "Körperliche Veränderungen dürfen keine Bedingung einer Anstellung sein.",
  "Wer Schmerzmittel nimmt, bedient keine Systeme.",
  "Anpassungen sind Voraussetzung für jede Landung.",
  "Der Körper eines Verstorbenen geht in die Aufbereitung.",

  // Ferne & Nachricht
  "Nachrichten von außen sind Tage alt, und alle wissen das.",
  "Was hier entschieden wird, lässt sich von außen nicht mehr aufhalten.",
  "Wer eine Nachricht sendet, sendet sie an alle.",
  "Über eine Schiffslänge hinaus gibt es keine Geheimnisse.",
  "Karten sind Handelsware und werden nicht verschenkt.",
  "Wer einen Weg kennt, gibt ihn nicht weiter.",
  "Funkstille gilt als Zustimmung.",
  "Jede Ankunft wird angekündigt, sonst gilt sie als Angriff.",
  "Fremde Signale werden gemeldet, nicht beantwortet.",
  "Die Aufzeichnungen der Gründung sind für alle einsehbar.",
  "Wer lügt, wird nicht bestraft, sondern nicht mehr gefragt.",
  "Gerüchte reisen schneller als Schiffe, und danach richtet man sich.",

  // Draußen & Grenzen
  "Kontakt mit Fremdem wird gemeldet, bevor er stattfindet.",
  "Was von draußen kommt, geht zuerst in Quarantäne.",
  "Waffen bleiben beim Andocken an Bord.",
  "Wer die Kuppel verlässt, geht zu zweit oder gar nicht.",
  "Außenarbeit wird doppelt vergütet und ist trotzdem unbeliebt.",
  "Niemand betritt einen fremden Ort ohne Einladung.",
  "Ein Wrack gehört dem, der es meldet, nicht dem, der es findet.",
  "Was auf einem Planeten wächst, bleibt dort.",
  "Grenzen verlaufen entlang von Bahnen, nicht entlang von Linien.",
  "Wer ein Gebiet beansprucht, muss es besetzen können.",
  "Rettung wird jedem geleistet, auch dem Gegner.",
  "Der erste Fund gehört der Gemeinschaft, jeder weitere dem Finder.",
  "Eine fremde Sprache zu lernen gilt als Pflicht, nicht als Begabung.",
  "Wer draußen jemanden zurücklässt, kommt nicht wieder herein.",
];

/** Märchen: Wort, Gastrecht, Zahlen, Schwellen, Zauberpreis, Stand, Vergeltung. */
export const MAERCHEN_RULES: string[] = [
  // Wort & Versprechen
  "Ein gegebenes Wort bindet, gleich unter welchen Umständen es fiel.",
  "Wer einen Namen kennt, hat Macht über den, der ihn trägt.",
  "Ausgesprochene Wünsche gehen in Erfüllung, aber nicht so, wie sie gemeint waren.",
  "Was dreimal gesagt wird, wird wahr.",
  "Ein Fluch lässt sich nicht aufheben, nur erfüllen.",
  "Wer ein Geheimnis verrät, verliert, was es ihm eingebracht hat.",
  "Schweigen kann ein Preis sein und wird als solcher verlangt.",
  "Ein Handel gilt, auch wenn man den Preis nicht verstanden hat.",
  "Wer sich verspricht, hat versprochen.",
  "Lügen werden sichtbar, spät, aber immer.",
  "Den eigenen Namen nennt man Fremden nicht.",
  "Wer sich bedankt, ist entlassen, und wer entlassen ist, geht.",
  "Ein Rat, um den nicht gebeten wurde, verpflichtet zu nichts.",
  "Ein Segen wirkt nur, solange der Beschenkte ihn nicht erwähnt.",
  "Wer flucht, trifft am Ende sich selbst.",
  "Verträge werden mündlich geschlossen und sind darum unlösbar.",

  // Gastrecht & Mildtätigkeit
  "Wer einen Fremden abweist, wird es bereuen.",
  "Brot und Salz verpflichten Gast und Gastgeber gleichermaßen.",
  "Unter einem fremden Dach darf niemandem geschadet werden.",
  "Wer teilt, obwohl er nichts hat, bekommt zurück.",
  "Bettler sind selten das, wonach sie aussehen.",
  "Freundlichkeit gegenüber Tieren zahlt sich später aus.",
  "Wer dem Ersten nicht hilft, dem hilft der Dritte nicht.",
  "Hochmut wird bestraft, und nicht von Menschen.",
  "Undankbarkeit ist die schwerste Verfehlung, die man begehen kann.",
  "Der Jüngste erreicht, woran die Älteren gescheitert sind.",
  "Wer nichts fordert, bekommt am meisten.",
  "Almosen dürfen nicht gezählt werden.",
  "Wer lacht, wo er helfen sollte, verliert die Stimme.",
  "Hilfe wird nie zweimal angeboten.",

  // Zahlen & Ordnung
  "Alles Wichtige geschieht dreimal.",
  "Die siebte Sache ist immer die entscheidende.",
  "Für jeden gibt es genau eine Prüfung, die zählt.",
  "Aufgaben kommen zu dritt, und die letzte ist unmöglich.",
  "Wer zweimal versagt, hat einen Versuch übrig.",
  "Der dritte Weg ist der richtige und der schwerste.",
  "Was zwölf Stunden dauert, endet mit dem Schlag.",
  "Ein Jahr und ein Tag ist die übliche Frist.",
  "Was sich siebenmal wiederholt, wird zur Regel dieser Welt.",
  "Der erste Versuch gehört immer dem Falschen.",
  "Man darf nur einmal fragen.",
  "Wer zurückblickt, verliert, was er getragen hat.",
  "Was bei Tag gilt, gilt bei Nacht nicht.",
  "Es zählt nur, was vor Zeugen geschieht.",

  // Wald & Schwellen
  "Der Wald gehört sich selbst, und wer eintritt, ist geduldet.",
  "Schwellen werden nicht ungefragt überschritten.",
  "Wer vom Weg abkommt, findet nicht zurück, sondern woandershin.",
  "Nach Einbruch der Dunkelheit gehört das Land anderen.",
  "Was im Wald gesagt wird, hört der Wald.",
  "Fließendes Wasser wird von manchem nicht überquert.",
  "Kreuzwege sind Orte der Entscheidung, nicht der Rast.",
  "Wer an einem Hügel schläft, wacht anderswo auf.",
  "Man nimmt nichts mit, wonach man nicht gefragt hat.",
  "Wer barfuß geht, sieht Wege, die es sonst nicht gibt.",
  "Türen, die von selbst offen stehen, sind Einladungen mit Preis.",
  "Eisen hält fern, was nicht hereinsoll.",
  "Der Wald gibt zurück, was ihm gehört, aber nicht unverändert.",
  "Wer im Wald isst, bleibt.",

  // Zauber & Preis
  "Jeder Zauber verlangt etwas, das nicht wiederkommt.",
  "Verwandlungen halten nicht ewig, aber länger als ein Menschenleben.",
  "Wunder geschehen selten und nie zweimal am selben Ort.",
  "Wer eine Gabe geerbt hat, kann sie nicht ablegen.",
  "Gaben werden bei der Geburt vergeben, nicht später erworben.",
  "Das Wirken einer weisen Frau gilt mehr als das eines Herrn.",
  "Was verzaubert ist, erkennt man am fehlenden Schatten.",
  "Gold aus Zauberei wird bei Sonnenaufgang zu Laub.",
  "Wer heilt, nimmt die Krankheit auf sich.",
  "Erlöst wird nur, wer erlöst werden will.",
  "Ein Zauber bricht, wenn man seinen Grund kennt.",
  "Wer bezaubert ist, weiß es nicht.",
  "Die Toten kehren nicht zurück, aber sie melden sich.",
  "Das Übernatürliche mischt sich nur ein, wenn es gerufen wurde.",

  // Stand & Herkunft
  "Wer arm geboren ist, kann aufsteigen, aber nur durch eine Tat.",
  "Adel verpflichtet und schützt nicht.",
  "Der Jüngste erbt nichts und geht darum fort.",
  "Töchter werden verheiratet, Söhne fortgeschickt.",
  "Herkunft zeigt sich, ob man will oder nicht.",
  "Ein König ist an sein Wort gebunden wie der Geringste.",
  "Wer sein Handwerk beherrscht, wird überall aufgenommen.",
  "Findelkinder haben eine Herkunft, und sie kommt ans Licht.",
  "Angeheiratete haben es schwer, Vertrauen zu erwerben.",
  "Geschwister sind Verbündete oder Gegner, nie gleichgültig.",
  "Wer wegzieht, kommt verändert wieder oder gar nicht.",
  "Die Alten wissen mehr, als sie sagen, und sagen es, wenn man fragt.",
  "Wer sich verkleidet, wird nicht erkannt, so einfach ist es.",
  "Schönheit gilt als Zeichen, nicht als Zufall.",

  // Vergeltung
  "Böses wird bestraft, aber nicht immer von denen, die es traf.",
  "Wer eine Falle stellt, gerät hinein.",
  "Fleiß wird belohnt, Faulheit sichtbar gemacht.",
  "Neid verrät sich durch die Tat, nicht durch das Wort.",
  "Was gestohlen ist, bringt keinen Nutzen.",
  "Grausamkeit gegen Wehrlose wird nicht vergessen.",
  "Reue kommt zu spät und zählt trotzdem.",
  "Die Wahrheit kommt heraus, meist auf einem Fest.",
  "Wer Unrecht duldet, hat es mitbegangen.",
  "Strafen sind hart und werden öffentlich vollzogen.",
  "Gnade kann jederzeit gewährt werden und beendet alles.",
  "Es gibt keine zweite Chance, aber viele erste.",
  "Wer einmal gerettet hat, darf einmal etwas verlangen.",
  "Am Ende bekommt jeder, was ihm zusteht, nicht was er wollte.",
];

/** Superhelden: Kräfte, Maske, Recht, Öffentlichkeit, Schaden, Konzerne, Kodex. */
export const SUPERHELDEN_RULES: string[] = [
  // Fähigkeiten
  "Fähigkeiten sind selten, aber kein Geheimnis.",
  "Zwei gleiche Kräfte gibt es nicht, jeder ist damit allein.",
  "Jede Fähigkeit hat einen Preis, den nur ihr Träger kennt.",
  "Kräfte zeigen sich in der Jugend oder gar nicht.",
  "Fähigkeiten lassen sich nicht abgeben und nicht ablegen.",
  "Wer seine Kraft einsetzt, verbraucht sich dabei.",
  "Kräfte sind vererbbar, überspringen aber öfter, als sie weitergehen.",
  "Es gibt keine Unverwundbaren, nur schlecht Getroffene.",
  "Eine Fähigkeit zu haben heißt nicht, sie zu beherrschen.",
  "Fähigkeiten sind messbar und werden eingestuft.",
  "Wer über die eigene Grenze geht, kommt nicht unbeschadet zurück.",
  "Kräfte versagen unter Druck, und niemand weiß vorher, wann.",
  "Es gibt kein Training, nur Gewöhnung.",
  "Wer eine Kraft verliert, bekommt sie nicht wieder.",

  // Identität & Maske
  "Wer eine Maske trägt, wird nicht nach dem Gesicht darunter gefragt.",
  "Eine Enttarnung ist der schwerste Bruch des Ungeschriebenen.",
  "Niemand arbeitet unter dem eigenen Namen.",
  "Wer sich zu erkennen gibt, kann nicht zurück.",
  "Angehörige werden nicht angetastet, und das gilt für beide Seiten.",
  "Zwei Leben zu führen ist erlaubt, aber nicht gegenüber Behörden.",
  "Eine maskierte Aussage zählt vor Gericht nicht.",
  "Ein Deckname wird kein zweites Mal vergeben.",
  "Masken erkennen einander und sprechen sich nicht an.",
  "Wer die Identität eines anderen kennt, schweigt oder gilt als Feind.",
  "Kostüme sind Handwerk, keine Verkleidung.",
  "Wer ohne Maske eingreift, gilt als Zivilist und wird so behandelt.",
  "Es gibt keinen Ruhestand, nur Verschwinden.",
  "Wer aufhört, wird nicht gesucht.",

  // Recht & Registrierung
  "Wer Fähigkeiten hat, muss sie melden.",
  "Selbstjustiz ist verboten und wird geduldet.",
  "Festnahmen durch Freiwillige sind rechtlich wertlos.",
  "Maskiert beschaffte Beweise sind vor Gericht nicht verwertbar.",
  "Es gibt eine eigene Haftanstalt und ein eigenes Verfahren dafür.",
  "Wer Kräfte im Streit einsetzt, wird nach schwererem Recht beurteilt.",
  "Die Stadt haftet für Schäden, die Freiwillige verursachen.",
  "Eine Behörde führt Buch, und die Liste ist nicht öffentlich.",
  "Wer sich nicht registriert, verliert den Anspruch auf Schutz.",
  "Kinder mit Fähigkeiten werden gesondert beschult.",
  "Verträge mit Freiwilligen sind befristet und jederzeit kündbar.",
  "Der Ausnahmezustand kann für einzelne Bezirke verhängt werden.",
  "Waffen sind verboten, Fähigkeiten nicht.",
  "Wer zweimal auffällt, wird verpflichtet.",
  "Amtshilfe wird geleistet, aber nicht dokumentiert.",
  "Wer im Einsatz tötet, wird nie verurteilt und nie wieder eingesetzt.",

  // Öffentlichkeit
  "Alles wird gefilmt, immer, aus mehreren Richtungen.",
  "Die Presse entscheidet, wer als Held gilt.",
  "Wer gerettet wurde, wird befragt, bevor er versorgt wird.",
  "Beliebtheit ist eine Ressource und wird verwaltet.",
  "Ein Fehler wiegt schwerer als zehn Erfolge.",
  "Jeder hat eine Meinung, und sie ändert sich wöchentlich.",
  "Namen vergibt die Öffentlichkeit, nicht der Träger.",
  "Wer sich rechtfertigt, hat schon verloren.",
  "Es gibt Anhängerschaften, und sie sind gefährlich.",
  "Werbeverträge sind üblich und werden nicht versteckt.",
  "Denkmäler werden zu Lebzeiten errichtet und wieder abgerissen.",
  "Wer schweigt, gilt als schuldig.",
  "Aufnahmen von Einsätzen sind Handelsware.",
  "Die Stadt liebt ihre Retter und fürchtet sie gleichzeitig.",

  // Schaden & Verantwortung
  "Jeder Einsatz kostet mehr, als er rettet, und es wird aufgerechnet.",
  "Wer Schaden anrichtet, zahlt ihn nicht.",
  "Versicherungen schließen Ereignisse dieser Art ausdrücklich aus.",
  "Evakuierung geht vor Verfolgung.",
  "Der Wiederaufbau dauert länger als die Erinnerung.",
  "Zivile Opfer werden gezählt und veröffentlicht.",
  "Wer nicht eingreift, macht sich nicht strafbar.",
  "Ein Gebäude ist zu ersetzen, ein Zeuge nicht.",
  "Die Feuerwehr rückt erst aus, wenn der Kampf vorbei ist.",
  "Rettung ist Pflicht, Verfolgung ist Wahl.",
  "Wer sich einmischt, übernimmt die Verantwortung für alles Weitere.",
  "Schadensbegrenzung zählt mehr als ein Sieg.",
  "In Wohngebieten wird nicht gekämpft, darauf haben sich alle geeinigt.",
  "Wer flieht, wird nicht durch die Stadt verfolgt.",

  // Konzerne & Wissenschaft
  "Die Ursache liegt fast immer bei einem Unternehmen.",
  "Forschung an Fähigkeiten ist genehmigungspflichtig und findet trotzdem statt.",
  "Wer die Technik hat, braucht keine Kräfte.",
  "Konzerne unterhalten eigene Einsatzkräfte, und das ist erlaubt.",
  "Wissen über Ursprünge wird gekauft, nicht veröffentlicht.",
  "Jede Erklärung, die angeboten wird, ist zu einfach.",
  "Fähigkeiten zu behandeln ist teuer und selten erfolgreich.",
  "Wer geheilt werden will, unterschreibt, was ihm danach erlaubt ist.",
  "Aus den Laboren verschwinden regelmäßig Prototypen.",
  "Verträge über Fähigkeiten laufen über Jahrzehnte.",
  "Universitäten forschen mit, aber nur mit fremdem Geld.",
  "Die gefährlichsten Gegner werden bezahlt.",
  "Was wirklich funktioniert, wird nicht veröffentlicht.",
  "Wer die Akten hat, bestimmt die Geschichte.",

  // Kodex
  "Es wird nicht getötet, und wer tötet, gehört nicht mehr dazu.",
  "Wer um Hilfe bittet, bekommt sie, ohne Frage nach dem Grund.",
  "Persönliches wird aus dem Einsatz herausgehalten.",
  "Ein Gegner, der aufgibt, wird nicht weiter angegriffen.",
  "Reviere werden geachtet, auch unausgesprochene.",
  "Zwei greifen nicht gleichzeitig ein, ohne sich abzusprechen.",
  "Wer Hilfe annimmt, schuldet sie zurück.",
  "Niemand wird an die Behörden verraten, auch kein Gegner.",
  "Wer Zivilisten benutzt, verliert jeden Schutz des Ungeschriebenen.",
  "Alte Absprachen gelten, bis sie ausdrücklich aufgekündigt werden.",
  "Über die Fähigkeiten anderer wird nicht gesprochen.",
  "Wer einmal auf der falschen Seite stand, kann zurückkommen.",
  "An einem Jahrestag wird nicht gekämpft.",
  "Es wird geholfen, auch wenn niemand zusieht.",
];

export const RULES_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_RULES,
  fantasy: FANTASY_RULES,
  steampunk: STEAMPUNK_RULES,
  cyberpunk: CYBERPUNK_RULES,
  historisch: HISTORISCH_RULES,
  western: WESTERN_RULES,
  scifi: SCIFI_RULES,
  maerchen: MAERCHEN_RULES,
  superhelden: SUPERHELDEN_RULES,
};

/**
 * Zwei bis drei Regeln, passend zum Genre, ohne Wiederholung.
 *
 * Verbunden mit **Leerzeichen**, nicht mit Semikolon: die Einträge sind
 * vollständige Sätze mit Punkt, und ein Semikolon dazwischen ergäbe Unsinn.
 * (Bei Aussehen und Hintergrund ist es umgekehrt – das sind Satzteile.)
 */
export function randomRules(genre?: string): string {
  const pool = RULES_BY_GENRE[genre ?? ""] ?? GEGENWART_RULES;
  return pickSome(pool, 2, 3).join(" ");
}
