/**
 * Bausteine für den Würfel am Szenario-Feld „Figuren" – **je Genre eine eigene
 * Liste von Rollen und eine von Rissen**, kombinatorisch zu einer Figur
 * zusammengesetzt (Name + Rolle + Riss). Anders als bei Ort und Zeit werden hier
 * also **Bausteine** gemischt, wie bei den Regeln – nur über zwei Ebenen: was
 * eine Figur in dieser Welt **tut** (Rolle) und woran sie **kippt** (Riss).
 *
 * Aus rund 100 Rollen und 100 Rissen je Genre entstehen tausende Figuren; der
 * Name kommt aus `names.ts` (genre-passender Kulturkreis). Eine Figur ist damit
 * ein **Notizzettel**, kein Steckbrief: „Name: was sie tut; woran sie kippt."
 *
 * **Rollen und Risse sind subjektlose Verbalphrasen im Präsens** (wie die
 * Hintergründe in `backgrounds.ts`) – **ohne Pronomen auf die Figur** („er/sie/
 * ihr"). So legen sie **kein Geschlecht** fest und passen zu jedem gezogenen
 * Namen. Ein Riss ist immer ein Riss: etwas Verschwiegenes, Ersehntes,
 * Ungelöstes, an dem sich eine Geschichte entzünden kann – nie bloß ein Beruf.
 *
 * Nach Genre **getrennt und nie gemischt** (dieselbe Regel wie in
 * `backgrounds.ts`): Ein Netrunner gehört nicht ins Märchen. Ohne bekanntes
 * Genre fällt die Wahl auf „Gegenwart".
 */

import { pickSome } from "./inspiration";
import { randomName } from "./names";

// ---------------------------------------------------------------------------
// Rollen – was eine Figur in dieser Welt tut / ist (subjektlose Verbalphrasen)
// ---------------------------------------------------------------------------

const GEGENWART_ROLLEN: string[] = [
  "führt den letzten Kiosk an der Ecke",
  "sitzt für die Gemeinde im Bauausschuss",
  "fährt nachts Kranken- und Notdienste",
  "pflegt die alte Mutter im dritten Stock",
  "hält die Buchhaltung einer kleinen Spedition",
  "unterrichtet an der Gesamtschule am Rand",
  "betreibt eine Werkstatt für alte Autos",
  "arbeitet an der Kasse im einzigen Supermarkt",
  "leitet das Vereinsheim des Sportclubs",
  "verwaltet die Wohnungen einer Erbengemeinschaft",
  "kellnert in der Kneipe am Marktplatz",
  "sitzt im Wartezimmer als Sprechstundenhilfe",
  "fährt für einen Lieferdienst durch die Stadt",
  "hütet den Schrebergarten seit dreißig Jahren",
  "schreibt für das Lokalblatt die Vermischtes-Seite",
  "räumt frühmorgens die Straßen des Viertels",
  "hält die Feuerwehr als Wehrführer zusammen",
  "verkauft Versicherungen von Tür zu Tür",
  "steht sonntags hinter der Theke der Bäckerei",
  "programmiert allein in einer stillen Wohnung",
  "leitet die Tafel und teilt die Spenden ein",
  "fährt Bus auf der einzigen Linie ins Umland",
  "sortiert im Amt die Anträge der anderen",
  "trainiert die Jugendmannschaft am Wochenende",
  "hält den Familienbetrieb gegen die Ketten",
  "putzt in Büros, wenn niemand mehr da ist",
  "vermittelt Ferienwohnungen an Fremde",
  "steht als Werkschutz am Tor des Betriebs",
  "betreut Geflüchtete in einer Beratungsstelle",
  "erbt einen Hof, den keiner mehr bewirtschaften will",
];

const FANTASY_ROLLEN: string[] = [
  "schmiedet Klingen in der Werkstatt am Wall",
  "führt die einzige Schenke am Handelsweg",
  "hütet die Tore der Stadt bei Nacht",
  "sammelt Kräuter in den Wäldern vor den Mauern",
  "steht der Gilde der Händler vor",
  "dient im Turm als Schreiber des Fürsten",
  "treibt Vieh über die Pässe ins Tal",
  "singt in den Höfen von alten Schlachten",
  "webt Bannzeichen in Tuch und Teppich",
  "verwaltet die Kornspeicher der Burg",
  "reist als Bote zwischen den Lehen",
  "heilt mit Kräutern, was der Priester aufgibt",
  "wacht als Söldner über einen Handelszug",
  "fährt die Fähre über den reißenden Fluss",
  "hält als Müller die Mühle am Bach",
  "sammelt Zölle an der Brücke ein",
  "lehrt Kinder heimlich die alten Zeichen",
  "gräbt in Ruinen nach vergessenen Dingen",
  "dient bei Hofe als Mundschenk",
  "führt eine Bande Wegelagerer in den Hügeln",
  "pflegt die Pferde im Marstall des Barons",
  "predigt in der kleinen Kapelle am Weg",
  "schnitzt Götzen für die Bauern der Gegend",
  "hält als Vogt Gericht über das Dorf",
  "sticht in See mit einem kleinen Handelsschiff",
  "sammelt Schulden für einen Geldverleiher ein",
  "bewacht die Bibliothek des alten Ordens",
  "zieht mit dem Wanderzirkus von Markt zu Markt",
  "arbeitet als Gerber am stinkenden Rand der Stadt",
  "dient der Herrin als Zofe und Ohr",
];

const STEAMPUNK_ROLLEN: string[] = [
  "hält die Kessel im Maschinenhaus in Gang",
  "konstruiert Rechenwerke aus Messing und Zahnrad",
  "steuert ein Luftschiff über die Rauchstadt",
  "leitet eine Fabrik am schwarzen Fluss",
  "repariert Automaten in einer Hinterhofwerkstatt",
  "verlegt Rohre und Leitungen unter der Stadt",
  "führt Buch über die Waren im Zollhaus",
  "erforscht Dampfdruck an der Akademie",
  "heizt die Öfen im Bauch eines Ozeandampfers",
  "verkauft Prothesen aus Messing und Leder",
  "spioniert für ein Konsortium der Industrie",
  "hält als Schaffner die pneumatische Bahn im Takt",
  "sammelt Schrott und Altmetall in den Gassen",
  "betreibt einen Salon für gehobene Gesellschaft",
  "wartet die Uhren am Turm über dem Rathaus",
  "schmuggelt Ersatzteile durch die Kanäle",
  "leitet ein Waisenhaus neben der Gießerei",
  "erfindet Apparate, die niemand bestellt hat",
  "fotografiert mit schwerem Gerät für die Presse",
  "verwaltet die Patente eines großen Hauses",
  "steht als Werkmeister über hundert Arbeitern",
  "zieht als Quacksalber mit Toniken über Land",
  "gräbt Kohle in den Flözen unter den Hügeln",
  "hält Vorträge über den Fortschritt in Vereinen",
  "näht Ballonhüllen in einer zugigen Halle",
  "beliefert die Reichen mit seltenen Mechaniken",
  "führt die Feuerwache mit dampfgetriebenem Gerät",
  "sammelt für ein Museum kuriose Apparaturen",
  "betreibt eine Telegrafenstation am Hafen",
  "arbeitet als Taucher an den Fundamenten der Brücken",
];

const CYBERPUNK_ROLLEN: string[] = [
  "durchsucht als Netzläufer fremde Systeme",
  "vermittelt als Fixer Aufträge im Untergrund",
  "arbeitet in der mittleren Etage eines Konzerns",
  "betreibt eine Bar unter der Hochstraße",
  "flickt Implantate in einer Kellerklinik",
  "fährt Kuriere durch die verstopften Schluchten",
  "handelt mit Daten auf dem grauen Markt",
  "sichert als Söldner Konzernkonvois",
  "programmiert Werbung, die niemand abschalten kann",
  "lebt vom Verkauf gebrauchter Erinnerungen",
  "leitet eine Bande in den unteren Ebenen",
  "hält als Streifenpolizist ein verlorenes Revier",
  "schürft Rechenzeit in einem heißen Serverloch",
  "singt in den Clubs hinter verspiegeltem Glas",
  "verwaltet Wohnkapseln für einen Vermieter",
  "spioniert Angestellte für die Chefetage aus",
  "verkauft Straßendrogen mit Konzernsiegel",
  "repariert Drohnen auf einem Schrottdach",
  "arbeitet als Leiharbeiter ohne Vertrag",
  "moderiert einen Piratensender aus dem Bunker",
  "wäscht Geld über eine Kette von Läden",
  "hütet ein Rechenzentrum tief unter der Stadt",
  "schmuggelt Menschen über die Konzerngrenze",
  "testet neue Implantate am eigenen Körper",
  "sammelt Pfand und Schrott in den Randzonen",
  "hält als Ripperdoc die Ärmsten am Leben",
  "verkauft falsche Papiere aus einem Wohnwagen",
  "steuert Kampfdrohnen aus einem fensterlosen Raum",
  "betreibt einen Nudelstand an der Kreuzung",
  "arbeitet als Datenkurier mit gesperrtem Konto",
];

const HISTORISCH_ROLLEN: string[] = [
  "führt einen Krämerladen an der Hauptstraße",
  "dient als Magd auf einem großen Hof",
  "predigt in der Pfarrei des Kirchspiels",
  "treibt Handel mit Tuch über die Grenze",
  "arbeitet als Schmied an der Poststraße",
  "verwaltet das Gut für einen abwesenden Herrn",
  "näht als Schneiderin für die besseren Häuser",
  "hält als Wirt die Herberge am Markt",
  "unterrichtet die Kinder in der Dorfschule",
  "dient als Soldat in der Garnison der Stadt",
  "sammelt Steuern für den Landesherrn ein",
  "fährt Fuhren mit Salz und Korn über Land",
  "heilt als Bader und schröpft die Kranken",
  "steht als Amtmann zwischen Bauern und Herrschaft",
  "webt Leinen in der Stube am langen Winter",
  "handelt mit Vieh auf den großen Märkten",
  "dient bei Hofe als Kammerzofe",
  "gräbt Torf in den Mooren vor dem Dorf",
  "führt die Zunft der Bäcker als Meister",
  "reist als Hausierer mit einem Kasten Waren",
  "schreibt Briefe für alle, die es nicht können",
  "verwaltet das Waisenhaus der Gemeinde",
  "fischt auf dem Fluss mit einem alten Kahn",
  "dient als Kutscher einem reichen Kaufmann",
  "hütet die Grenze als Zöllner am Schlagbaum",
  "arbeitet in der Küche eines Klosters",
  "handelt heimlich mit verbotenen Büchern",
  "pflegt die Kranken im Siechenhaus vor den Toren",
  "führt als Hebamme das Dorf durch seine Geburten",
  "dient dem Rat der Stadt als Schreiber",
];

const WESTERN_ROLLEN: string[] = [
  "treibt Rinder über die staubigen Ebenen",
  "hält als Sheriff Ordnung in einem Nest",
  "schenkt im Saloon an der Hauptstraße aus",
  "gräbt in den Bergen nach einer Ader Gold",
  "führt den einzigen Krämerladen der Stadt",
  "reitet für die Postlinie durch das Territorium",
  "besitzt die Ranch am Ende des Tals",
  "spielt Karten in den Hinterzimmern der Städte",
  "schmiedet Hufeisen und Achsen am Rand des Orts",
  "predigt in einer Kirche aus rohem Holz",
  "führt die Bank mit dem einzigen Safe weit und breit",
  "jagt Kopfgelder über die Grenze hinweg",
  "arbeitet als Cowboy auf einem fremden Land",
  "betreibt die Poststation an der Wüstenstraße",
  "verlegt Gleise für die kommende Eisenbahn",
  "verkauft Land, das ihm nicht gehört",
  "hält als Doktor die einzige Praxis der Gegend",
  "singt und tanzt in der Show des Saloons",
  "treibt eine Bande über die Hügel und Schluchten",
  "verwaltet den Wasserlauf, von dem alle leben",
  "handelt mit den Stämmen an der Grenze",
  "führt die Kutsche durch unsicheres Land",
  "brennt Whiskey in einer versteckten Hütte",
  "hütet die Herde als schweigsamer Alter",
  "arbeitet als Fallensteller in den Wäldern",
  "steht als Marshal über mehreren Städten",
  "betreibt das Hotel mit den einzigen Betten",
  "gräbt Brunnen für die Siedler der Ebene",
  "verkauft Gewehre aus einem Planwagen",
  "führt Buch über die Schulden des halben Orts",
];

const SCIFI_ROLLEN: string[] = [
  "fliegt einen Frachter zwischen den Kolonien",
  "wartet die Lebenserhaltung einer Station",
  "forscht im Labor eines Terraform-Projekts",
  "handelt mit Wasser an der Grenze des Systems",
  "kommandiert ein Bergbauschiff im Gürtel",
  "programmiert die Bordsysteme alter Kähne",
  "verwaltet eine Kolonie am Rand des Bekannten",
  "schürft Erz auf einem toten Mond",
  "dient als Sanitäter auf einem Militärschiff",
  "schmuggelt Fracht durch die Kontrollzonen",
  "leitet den Hafen einer Umlaufstation",
  "pflegt die Hydrokulturen unter der Kuppel",
  "repariert Roboter in einer Werft",
  "hält als Marshal Ordnung auf einer Außenwelt",
  "übersetzt zwischen Kolonisten und Konzern",
  "steuert Bergbaudrohnen aus einem Kontrollraum",
  "predigt einer Sekte auf dem langen Flug",
  "sammelt Wracks im Schatten eines Riesen",
  "verwaltet die Rationen einer Langstreckenreise",
  "forscht an einem Signal, das niemand erklärt",
  "dient als Ingenieur im Maschinenraum",
  "verkauft gefälschte Reisepapiere für Schiffe",
  "betreibt eine Bar an einem Umschlagplatz",
  "führt als Captain eine bunt zusammengewürfelte Crew",
  "wacht über ein Archiv verlorener Erde-Daten",
  "arbeitet als Kopfgeldjäger zwischen den Welten",
  "hütet einen Leuchtturm an einem Sprungpunkt",
  "leitet die Quarantäne einer verseuchten Kuppel",
  "baut Habitate für die nächste Welle Siedler",
  "fährt einen Rover durch die Staubwüste eines Planeten",
];

const MAERCHEN_ROLLEN: string[] = [
  "mahlt das Korn in der Mühle am Waldrand",
  "hütet die Gänse auf der Wiese vor dem Dorf",
  "schlägt Holz in den tiefen, dunklen Wäldern",
  "spinnt Flachs bis tief in die Nacht",
  "hält als Wirtin die Schenke an der Kreuzung",
  "sammelt Beeren und Pilze für die Tafel des Königs",
  "webt Körbe aus Weiden am Bach",
  "dient im Schloss als jüngste Küchenmagd",
  "zieht als Spielmann von Dorf zu Dorf",
  "hütet die Schafe am Fuß des verbotenen Bergs",
  "backt das Brot für das ganze Dorf",
  "wohnt allein als weise Frau am Moor",
  "schmiedet in einer Esse tief im Wald",
  "fischt im See, in dem etwas wohnen soll",
  "dient dem König als treuer Jäger",
  "handelt mit Bändern und Nadeln von Markt zu Markt",
  "hält die Fähre über den nebligen Fluss",
  "sammelt für den Apotheker seltene Wurzeln",
  "bewacht das Tor zum verwunschenen Garten",
  "näht Kleider für die Töchter des Grafen",
  "erzählt den Kindern am Feuer die alten Geschichten",
  "hütet einen Schatz, von dem niemand wissen darf",
  "dient als Stallbursche auf dem Gut",
  "sammelt Wegzoll an der alten Steinbrücke",
  "pflegt den Garten hinter der hohen Mauer",
  "zieht mit dem Bären über die Jahrmärkte",
  "wohnt als Einsiedler in einer Höhle am Hang",
  "kehrt die Asche im großen Kamin des Schlosses",
  "flickt Töpfe und Kessel als wandernder Kesselflicker",
  "hütet die Bienen des Klosters am Berg",
];

const SUPERHELDEN_ROLLEN: string[] = [
  "recherchiert für eine große Stadtzeitung",
  "forscht im Labor eines Technologiekonzerns",
  "leitet die Spurensicherung der Polizei",
  "arbeitet als Sanitäter im Nachtdienst",
  "betreibt einen Späti im gebeutelten Viertel",
  "verteidigt Mittellose als Pflichtanwältin",
  "hält als Kommissar eine Mordkommission zusammen",
  "unterrichtet Physik an einer Highschool",
  "moderiert eine reichweitenstarke Nachrichtensendung",
  "programmiert Sicherheitssysteme für Banken",
  "führt eine Bar, in der Halbwelt und Presse sitzen",
  "leitet die Notaufnahme des größten Krankenhauses",
  "arbeitet als Bürgermeisterin einer geteilten Stadt",
  "sammelt als Streuner Gerüchte von der Straße",
  "verwaltet das Vermögen einer alten Familie",
  "trainiert Jugendliche in einer Boxhalle",
  "fliegt einen Rettungshubschrauber über die Stadt",
  "hält als Wachmann ein leerstehendes Hochhaus",
  "leitet eine Hilfsorganisation im Krisenviertel",
  "fotografiert für die Klatschpresse die Reichen",
  "forscht heimlich an verbotenen Technologien",
  "steht einem Rüstungskonzern als Direktor vor",
  "arbeitet als Feuerwehrfrau in der Innenstadt",
  "betreibt einen Pfandleihladen mit offenen Ohren",
  "leitet als Direktor ein überfülltes Waisenhaus",
  "verkauft Informationen an beide Seiten",
  "hält als U-Bahn-Fahrer die Stadt in Bewegung",
  "organisiert Proteste gegen den großen Konzern",
  "pflegt in einer Klinik die Opfer der Kämpfe",
  "sitzt als Staatsanwältin gegen das Verbrechen",
];

// ---------------------------------------------------------------------------
// Risse – woran eine Figur kippt (subjektlose Verbalphrasen, ohne Pronomen)
// ---------------------------------------------------------------------------

const GEGENWART_RISSE: string[] = [
  "hat Schulden, von denen zu Hause niemand weiß",
  "deckt einen Diebstahl im eigenen Betrieb",
  "wartet auf einen Anruf, der nie kommt",
  "hat vor Jahren eine wichtige Aussage zurückgehalten",
  "sucht ein Kind, das die Familie verstoßen hat",
  "verkauft heimlich, was anderen gehört",
  "hält an einer Lüge fest, die längst zu groß ist",
  "will fort und kann die Alten nicht zurücklassen",
  "hat den Falschen belastet und schweigt seither",
  "schuldet einem gefährlichen Menschen einen Gefallen",
  "erpresst leise die, die etwas zu verlieren haben",
  "hat eine Krankheit vor allen verborgen",
  "trauert um jemanden, den keiner betrauern darf",
  "hat einen Brand gelegt, den man Unfall nannte",
  "verbirgt eine zweite Familie zwei Städte weiter",
  "unterschlägt seit Jahren kleine Beträge",
  "kennt das Geheimnis, das den Ort zusammenhält",
  "sucht Rache für etwas, das niemand mehr erinnert",
  "hat einem Sterbenden ein Versprechen gebrochen",
  "steht auf einer Liste, von der es nichts weiß",
  "verspielt langsam das Erbe der Geschwister",
  "hat einen Zeugen dazu gebracht zu schweigen",
  "hält ein Grundstück, auf das viele scharf sind",
  "fürchtet, dass eine alte Tat ans Licht kommt",
  "liebt jemanden, den zu lieben verboten scheint",
  "hat eine Unterschrift gefälscht und es bereut",
  "beschützt einen Menschen, der es nicht verdient",
  "sammelt Beweise gegen einen mächtigen Nachbarn",
  "kann eine Sucht vor allen gerade noch verbergen",
  "weiß, wo ein Verschwundener wirklich geblieben ist",
];

const FANTASY_RISSE: string[] = [
  "trägt ein Mal, das in der Stadt Tod bedeutet",
  "schuldet einer dunklen Macht einen Dienst",
  "hütet ein Erbstück, hinter dem viele her sind",
  "hat einen Eid gebrochen und fürchtet die Rache",
  "verbirgt eine Gabe, die als Fluch gilt",
  "sucht den Mörder aus einer alten Fehde",
  "hat der Gilde Geld unterschlagen",
  "kennt einen Weg durch die Mauern, den keiner kennt",
  "trägt die Botschaft eines Toten weiter",
  "liebt jemanden aus dem verfeindeten Haus",
  "hat einen Handel mit Schmugglern laufen",
  "verbirgt königliches Blut in den eigenen Adern",
  "sucht ein Kind, das man ihm einst nahm",
  "hat einen Gefangenen heimlich entkommen lassen",
  "hält ein Buch versteckt, das verboten ist",
  "schuldet einem Geldverleiher mehr als das Leben wert ist",
  "kennt den Verräter im Rat der Stadt",
  "hat einem Sterbenden ein Versprechen gegeben",
  "trägt eine Krankheit, die als Strafe der Götter gilt",
  "sucht Rache an einem inzwischen mächtigen Mann",
  "verbirgt, dass ein Erbe längst tot ist",
  "hat aus Not eine Reliquie gestohlen",
  "dient heimlich zwei Herren zugleich",
  "weiß, wo ein sagenhafter Schatz vergraben liegt",
  "fürchtet einen Fluch, den es selbst heraufbeschwor",
  "hält Kontakt zu den Geächteten in den Wäldern",
  "hat ein Versprechen mit einem Wesen aus dem Wald",
  "trägt Schuld an einem Brand, der viele nahm",
  "beschützt einen Flüchtigen vor der Wache",
  "sucht ein Wort, das eine alte Tür wieder öffnet",
];

const STEAMPUNK_RISSE: string[] = [
  "hat einen Fabrikunfall vertuscht, der Tote forderte",
  "stahl einen Bauplan aus einem großen Haus",
  "verbirgt eine Erfindung, die alles verändern würde",
  "schuldet einem Konsortium mehr, als es je zahlen kann",
  "hält ein Patent, das jemand mit Gewalt will",
  "hat eine Explosion als Zufall ausgegeben",
  "verkauft heimlich Ersatzteile an die Konkurrenz",
  "sucht den Ingenieur, der einen Toten baute",
  "trägt eine Prothese, die nicht bezahlt ist",
  "kennt den Fehler, der eine Brücke einstürzen lässt",
  "spioniert für eine Macht jenseits des Meeres",
  "verbirgt die Herkunft aus den Slums der Rauchstadt",
  "hat ein Kind in der Fabrik verunglücken lassen",
  "schmuggelt verbotene Chemikalien durch die Kanäle",
  "hütet die Aufzeichnungen eines verschwundenen Erfinders",
  "erpresst einen Fabrikherrn mit alten Briefen",
  "hat Arbeiter für ein Experiment geopfert",
  "sucht Rache an dem Haus, das die Familie ruinierte",
  "kennt den wahren Zustand der maroden Kessel",
  "verbirgt einen Automaten, der zu viel denkt",
  "hat Zahlen in den Büchern gefälscht",
  "dient der Gewerkschaft und der Direktion zugleich",
  "trägt eine Krankheit aus den Gießereien in sich",
  "sucht den Auftraggeber eines Anschlags",
  "hält einen entlaufenen Automaten versteckt",
  "hat eine Zeichnung verkauft, die geheim bleiben sollte",
  "beschützt einen Deserteur der Werkspolizei",
  "weiß, was im untersten Stollen wirklich gefördert wird",
  "fürchtet, dass ein alter Prozess neu aufgerollt wird",
  "liebt jemanden aus dem verfeindeten Konsortium",
];

const CYBERPUNK_RISSE: string[] = [
  "trägt Daten im Kopf, für die man töten würde",
  "schuldet einem Konzern einen unbezahlbaren Kredit",
  "hat einen Auftrag verpfuscht, an dem Menschen starben",
  "verbirgt ein Implantat, das nicht registriert ist",
  "sucht das Kind, das eine Firma als Pfand nahm",
  "verkauft Geheimnisse an die eigene Chefetage",
  "hält einen Zeugen versteckt, den viele suchen",
  "hat sich eine falsche Identität zu tief zugelegt",
  "trägt eine Sperre im Konto, deren Grund geheim ist",
  "kennt die Hintertür in ein großes System",
  "dient heimlich einer Bande und dem Konzern zugleich",
  "hat eine Erinnerung gekauft, die einem Toten gehört",
  "sucht Rache an dem Fixer, der es verkaufte",
  "verbirgt, dass ein Prototyp aus dem Labor entkam",
  "erpresst einen Manager mit dessen eigenen Daten",
  "hat einen Freund an die Werkspolizei verraten",
  "trägt eine Krankheit, die kein Konzern behandeln will",
  "schmuggelt Menschen aus der Konzernzone",
  "kennt den Ort eines Servers, den es nicht geben darf",
  "hält Kontakt zu einer verbotenen künstlichen Intelligenz",
  "hat Rechenzeit gestohlen und wird dafür gejagt",
  "beschützt einen Aussteiger vor seiner alten Firma",
  "weiß, was in den unteren Ebenen wirklich verschwindet",
  "verbirgt die Spuren eines gelöschten Menschen",
  "sucht den Beweis für einen vertuschten Skandal",
  "hat ein Versprechen an einen Sterbenden zu halten",
  "trägt einen Chip, dessen Besitzer noch lebt",
  "fürchtet, dass eine alte Aufzeichnung auftaucht",
  "liebt jemanden aus der feindlichen Bande",
  "hält den letzten Zugang zu einem verlorenen Netz",
];

const HISTORISCH_RISSE: string[] = [
  "verbirgt einen Glauben, der hier verboten ist",
  "hat einem Herrn Geld unterschlagen",
  "trägt ein uneheliches Kind zur Welt und schweigt",
  "kennt den wahren Erben eines großen Gutes",
  "hat einen Nachbarn fälschlich angezeigt",
  "schuldet einem Wucherer Haus und Hof",
  "verbirgt Briefe, die einen Mächtigen stürzen könnten",
  "sucht Rache für einen zu Unrecht Gehängten",
  "hat aus Not aus der Kirchenkasse genommen",
  "hält Kontakt zu Aufständischen im Umland",
  "verbirgt die niedere Herkunft mit gefälschten Papieren",
  "hat einen Deserteur in der Scheune versteckt",
  "kennt das Geheimnis einer Hochzeit, die keine war",
  "trägt eine Krankheit, die man für Strafe hält",
  "hat einen Zeugen bestochen zu schweigen",
  "sucht das Kind, das man ins Waisenhaus gab",
  "verbirgt verbotene Bücher unter den Dielen",
  "hat einem Sterbenden das Erbe abgeschwatzt",
  "dient heimlich einer fremden Krone",
  "weiß, wer in Wahrheit den Brand gelegt hat",
  "erpresst einen Pfarrer mit dessen Vergangenheit",
  "hat aus Eifersucht ein Gerücht in die Welt gesetzt",
  "beschützt eine Frau vor dem Zorn ihres Mannes",
  "trägt Schuld an einer Missernte, die keine war",
  "sucht den Kaufmann, der die Familie ruinierte",
  "verbirgt, dass ein Testament gefälscht wurde",
  "hält eine verbotene Liebe über Standesgrenzen hinweg",
  "hat Schmuggelware im Keller der Herberge",
  "fürchtet, dass eine alte Tat vor Gericht kommt",
  "kennt den geheimen Gang aus der belagerten Stadt",
];

const WESTERN_RISSE: string[] = [
  "hat einen Zug überfallen und den Namen gewechselt",
  "schuldet der Bank mehr, als die Ranch wert ist",
  "sucht den Mann, der die Familie erschoss",
  "verbirgt eine Vergangenheit als Revolverheld",
  "hält die Urkunde für Land, das viele wollen",
  "hat einen Unschuldigen hängen sehen und geschwiegen",
  "kennt die Ader Gold, von der keiner wissen darf",
  "trägt einen Steckbrief in der Innentasche",
  "hat Vieh gestohlen und es teuer verkauft",
  "beschützt einen Bruder, der ein Mörder ist",
  "verbirgt, dass der Brunnen bald versiegt",
  "schuldet einem Spieler eine tödliche Summe",
  "sucht Rache an dem Sheriff, der zusah",
  "hat Waffen an beide Seiten der Grenze verkauft",
  "kennt den Verrat, der einem Trupp das Leben kostete",
  "trägt das Geheimnis einer verlegten Bahnstrecke",
  "erpresst den Bankier mit dessen krummen Geschäften",
  "hat einem Sterbenden das Grubenrecht abgeschwatzt",
  "verbirgt eine Herkunft, die hier den Strick bedeutet",
  "dient dem Marshal und den Banditen zugleich",
  "weiß, wer das Wasser oben abgräbt",
  "sucht das Kind, das bei einem Überfall verschwand",
  "hält einen entflohenen Gefangenen versteckt",
  "hat die Poststation um ihren Lohn geprellt",
  "trägt Schuld an einem Feuer, das die Stadt fast nahm",
  "beschützt eine Zeugin vor den Männern der Ranch",
  "verbirgt, dass die Goldader längst erschöpft ist",
  "liebt jemanden von der falschen Seite der Grenze",
  "fürchtet, dass ein alter Kompagnon wieder auftaucht",
  "kennt den Ort, an dem die Beute vergraben liegt",
];

const SCIFI_RISSE: string[] = [
  "trägt Fracht an Bord, die nicht im Manifest steht",
  "schuldet einem Konzern das eigene Schiff",
  "sucht den Offizier, der eine Kolonie opferte",
  "verbirgt eine Infektion vor der Stationsleitung",
  "kennt die Koordinaten eines verschollenen Wracks",
  "hat einen Notruf ignoriert und schweigt darüber",
  "hält einen Passagier versteckt, den man sucht",
  "trägt Erinnerungen, die einer Löschung entgingen",
  "hat Rationen unterschlagen, als es eng wurde",
  "beschützt eine künstliche Intelligenz vor der Abschaltung",
  "verbirgt die Herkunft von einer geächteten Welt",
  "schuldet Schmugglern einen letzten Transport",
  "sucht ein Kind, das der Konzern als Pfand behielt",
  "kennt den wahren Grund für die Quarantäne",
  "hat ein Signal empfangen, das niemand kennen soll",
  "dient heimlich der Flotte und den Kolonisten zugleich",
  "trägt einen Defekt im Schiff, der nicht gemeldet ist",
  "sucht Rache an dem Captain, der meuterte",
  "verbirgt, dass die Terraformung längst gescheitert ist",
  "hält den letzten Datensatz einer verlorenen Erde",
  "hat einen blinden Passagier an Bord genommen",
  "erpresst die Leitung mit den Logbüchern",
  "weiß, was im gesperrten Sektor wirklich passiert",
  "beschützt einen Deserteur vor der Militärpolizei",
  "trägt Schuld an einem Druckabfall, der Leben kostete",
  "sucht den Ursprung einer Seuche zwischen den Welten",
  "verbirgt eine Fracht lebender Fracht im Laderaum",
  "liebt jemanden aus der feindlichen Fraktion",
  "fürchtet, dass ein altes Kriegsverbrechen ans Licht kommt",
  "kennt die Schwachstelle im Schild der Station",
];

const MAERCHEN_RISSE: string[] = [
  "hat einem seltsamen Wesen ein Versprechen gegeben",
  "verbirgt ein Kind, das nicht sein eigenes ist",
  "trägt einen Fluch, der bei Vollmond erwacht",
  "hütet einen Schatz, den drei Brüder suchen",
  "hat aus Not das letzte Brot gestohlen",
  "kennt den Weg in den Wald, aus dem keiner kehrt",
  "schuldet der weisen Frau am Moor einen Dienst",
  "sucht die Schwester, die der König verbannte",
  "verbirgt, dass ein Tier einst ein Mensch war",
  "hat ein Wort gebrochen, das man nie brechen darf",
  "trägt einen Ring, den viele mit Gewalt wollen",
  "beschützt ein Mädchen vor der Stiefmutter",
  "hält den Spiegel versteckt, der zu viel zeigt",
  "hat dem Müller sein Glück abgeschwatzt",
  "kennt den wahren Namen, der eine Macht bindet",
  "sucht Rache an dem Grafen, der das Dorf verriet",
  "verbirgt königliches Blut unter Lumpen",
  "hat einem Sterbenden ein Geheimnis versprochen",
  "trägt Schuld an einem Kind, das im Fluss ertrank",
  "dient heimlich der Hexe und dem König zugleich",
  "weiß, wo der verwunschene Prinz gefangen liegt",
  "hütet die letzte Feder eines seltenen Vogels",
  "hat einen Handel mit dem Männlein im Wald",
  "sucht das Tor, das nur zu Mitternacht offen steht",
  "verbirgt, dass der Brunnen Wünsche wahr macht",
  "beschützt ein sprechendes Tier vor den Jägern",
  "liebt jemanden, den ein Zauber verwandelt hat",
  "fürchtet, dass ein altes Versprechen fällig wird",
  "kennt das Lied, das den Berg wieder öffnet",
  "hält den Schlüssel zu einer Tür, die verboten ist",
];

const SUPERHELDEN_RISSE: string[] = [
  "kennt die wahre Identität hinter einer Maske",
  "hat Beweise gegen einen mächtigen Konzern",
  "verbirgt eine Kraft, die niemand kennen darf",
  "schuldet einem Verbrechersyndikat einen Gefallen",
  "sucht den Täter aus einer nie geklärten Nacht",
  "hat eine Quelle geschützt und dafür gelogen",
  "hält einen Zeugen versteckt, den viele suchen",
  "trägt Schuld an einem Einsatz, der schiefging",
  "hat sich mit der Halbwelt zu tief eingelassen",
  "beschützt ein Kind mit gefährlichen Fähigkeiten",
  "verbirgt eine Krankheit vor dem eigenen Team",
  "kennt das Leck in den Reihen der Polizei",
  "erpresst einen Politiker mit alten Akten",
  "sucht Rache an dem Helden, der zu spät kam",
  "hat eine Technologie gestohlen, die tötet",
  "dient heimlich dem Konzern und der Presse zugleich",
  "weiß, wer hinter der Anschlagsserie steckt",
  "trägt die Papiere einer gelöschten Existenz",
  "hat einem Sterbenden ein Versprechen gegeben",
  "verbirgt, dass ein Held längst die Seite wechselte",
  "hält den letzten Beweis eines vertuschten Unfalls",
  "beschützt einen Aussteiger vor seinem alten Boss",
  "sucht das Kind, das ein Experiment hervorbrachte",
  "hat aus Angst einen Falschen belastet",
  "kennt die Schwachstelle eines gefeierten Helden",
  "verbirgt eine zweite Identität vor der Familie",
  "trägt Schuld an einer Explosion in der Innenstadt",
  "fürchtet, dass eine alte Tat ans Licht kommt",
  "liebt jemanden von der anderen Seite des Gesetzes",
  "hält Kontakt zu einer gejagten Vigilantin",
];

// ---------------------------------------------------------------------------

const ROLLEN_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_ROLLEN,
  fantasy: FANTASY_ROLLEN,
  steampunk: STEAMPUNK_ROLLEN,
  cyberpunk: CYBERPUNK_ROLLEN,
  historisch: HISTORISCH_ROLLEN,
  western: WESTERN_ROLLEN,
  scifi: SCIFI_ROLLEN,
  maerchen: MAERCHEN_ROLLEN,
  superhelden: SUPERHELDEN_ROLLEN,
};

const RISSE_BY_GENRE: Record<string, string[]> = {
  gegenwart: GEGENWART_RISSE,
  fantasy: FANTASY_RISSE,
  steampunk: STEAMPUNK_RISSE,
  cyberpunk: CYBERPUNK_RISSE,
  historisch: HISTORISCH_RISSE,
  western: WESTERN_RISSE,
  scifi: SCIFI_RISSE,
  maerchen: MAERCHEN_RISSE,
  superhelden: SUPERHELDEN_RISSE,
};

/**
 * Setzt **eine** Figur zusammen: ein genre-passender Name (`randomName`, Kultur
 * über das Genre), eine Rolle und ein Riss. Geschlecht „egal" – die Bausteine
 * sind pronomenlos, der Name darf jedes Geschlecht haben.
 *
 * Form: `Name: <Rolle>; <Riss>.` – dasselbe „Name: …"-Muster, das auch das
 * zufällig erzeugte Szenario ins Feld schreibt, damit Würfel und KI sich mischen
 * lassen.
 */
function macheFigur(rolle: string, riss: string, genre?: string): string {
  const name = randomName({ gender: "egal", genre });
  return `${name}: ${rolle}; ${riss}.`;
}

/**
 * Würfelt Figuren fürs Feld „Figuren". Ins **leere** Feld kommen zwei bis drei,
 * beim **Ergänzen** eine weitere – dieselbe Logik wie bei den Regeln, nur über
 * zwei Baustein-Ebenen. Innerhalb eines Wurfs sind Rollen und Risse ohne
 * Wiederholung gezogen (`pickSome`), damit nicht zwei Figuren dasselbe tun.
 *
 * Ohne bekanntes Genre fällt die Wahl auf „Gegenwart"; über die Genre-Listen
 * wird **nie gemischt**.
 */
export function randomFigure(genre?: string, ergaenzen = false): string {
  const rollen = ROLLEN_BY_GENRE[genre ?? ""] ?? GEGENWART_ROLLEN;
  const risse = RISSE_BY_GENRE[genre ?? ""] ?? GEGENWART_RISSE;
  const anzahl = ergaenzen ? 1 : 2 + Math.floor(Math.random() * 2); // 2–3
  const r = pickSome(rollen, anzahl, anzahl);
  const k = pickSome(risse, anzahl, anzahl);
  return r.map((rolle, i) => macheFigur(rolle, k[i], genre)).join("\n");
}
